### ISSUE TITLE
redundant word in the logging prompt

### ISSUE THREAD

**Issue by ablimit** [KjellKod/g3log#102]
At line 55 in file src/logworker.cpp the word "flushed" appeared twice.

suggestion:
"Log content flushed flushed sucessfully to sink" --> "Log content flushed successfully to sink"

**Comment by KjellKod** [comment]
Thanks. Please put up a pull request to address it

**Comment by KjellKod** [comment]
Thanks. It was less to fix than I thought and exactly as you described it.
The fix is merged
