### ISSUE TITLE
clang 3.7 warning: braces around scalar initializer

### ISSUE THREAD

**Issue by jkhoogland** [KjellKod/g3log#107]
Hi
it would be nice to have the following warnings taken care of:

```
dev/3rd/Source/g3log/src/g3log/loglevels.hpp:75:39: warning: braces around scalar initializer [-Wbraced-scalar-init]
const LEVELS DEBUG {g3::kDebugVaulue, {"DEBUG"}},
                                      ^~~~~~~~~
```
and a lot more for the different levels...

I don't have a OSX El Capitan box around to fix this right now.
But it should just be a matter of taking of the extra braces..

If I get my hands around a El Capitan box i ll create a PR, 
unless you see time to do it before that..

Regards
Jiri

**Comment by KjellKod** [comment]
Hmm. They are not extra and are conforming to the standard c++11.

**Comment by jkhoogland** [comment]
Are you sure ?
Looking at the definition of the struct LEVELS I see the constructor taking a `const char*`

```
LEVELS(int id, const char* idtext) : value(id), text(idtext) {}
```

so 

```
{ "DEBUG" }
```

to me, seems like one level of brackets too much.

**Comment by KjellKod** [comment]
It's a std::string so it's brace initializer

**Comment by sevenjay** [comment]
[aggregate initialization](http://en.cppreference.com/w/cpp/language/aggregate_initialization)
```c++
    std::string ars[] = {std::string("one"), // copy-initialization
                         "two",              // conversion, then copy-initialization
                         {'t', 'h', 'r', 'e', 'e'} }; // list-initialization
```

**Comment by KjellKod** [comment]
// constructing seg from string copies
std::string arr[] = {std::string("one")};

Is just as valid as brace initialization: 
std::string arr[] = {{"one"}}; 

As well as brace initialization with many single chars
std::string arr[] = {{'o','n','e'}};

Ref: http://ideone.com/NtfKYP

**Comment by KjellKod** [comment]
Aha. I see what you mean: https://github.com/KjellKod/g3log/blob/master/src/g3log/loglevels.hpp

@jkhoogland  does the warning go away if you change the constructor to take in a `const std::string&` Instead of a `const char*`?

**Comment by sevenjay** [comment]
Maybe I ask what's different between passing `const std::string& idtext` and `std::string idtext`?
`const std::string& idtext` will do copy once when it uses `basic_string( const basic_string& other );` 
and `std::string idtext` will have a cheap move (not a deep copy) when it uses `basic_string( basic_string&& other );` from the temporary object?
Or we can implement constructor like 
```c++
    LEVELS(int id, std::string && idtext) : value(id), text(idtext) {}
```
to avoid copy?

I am learning move semantics, thanks.

**Comment by KjellKod** [comment]
Probably.

Why not play with it (put in some couts to see what's triggered) and once happy put up a pull request?

**Comment by KjellKod** [comment]
fixed in: https://github.com/KjellKod/g3log/pull/108
