### ISSUE TITLE
For MSVC shared libraries, exportall.def should be replaced

### ISSUE THREAD

**Issue by OfekShilon** [KjellKod/g3log#112]
Exporting _everything_ in the binary causes needless delays in the dll loading.   The actual list of stuff that requires exporting is extremely short:
1. class FileSink
2. struct LogCapture
3. class LogWorker
4. logLevel
5. initializeLogging
6. setFatalPreLoggingHook
7. setFatalExitHandler

These are typically decorated with g3log_API, defined as
# ifdef g3log_EXPORTS
# define g3log_API __declspec(dllexport)
# else
# define g3log_API __declspec(dllimport)
# endif

(with g3log_EXPORTS #defined in the dll project)

This syntax holds for at least MSVC and gcc, but I have only MSVC to test on.

**Comment by OfekShilon** [comment]
BTW, building as a shared library seems highly preferable - you want to be able to use singleton log objects (all the anonymous namespace at g3log.cpp) _per-executable_, and if you use static libs these are instantiated per-dll.
shared-library should probably be at least the default (if not the only) build config in CMake.

**Comment by KjellKod** [comment]
Both changes sound awesome. Can you open a pull request?

**Comment by OfekShilon** [comment]
@KjellKod  I started playing with this, and revealed another issue - not sure if it's in the project or in CMake.  Under the MSVC generator, the g3log_shared dll project creates an import lib with the name g3log.lib, *identical to the static lib* generated by the g3log project. This means that dependent projects (g3log_FATAL_XXX.vcxproj)  look for their dependencies in this import lib, and not the static lib generated by g3log which they actually reference.  After I narrow down the list of symbols exported by g3log_shared, these dependent projects fail to build.
Not sure why CMake names the IMPLIB after the solution and not the particular project. The right thing to do would have been to have CMake generate a g3log_shared project *without* an /IMPLIB linker directive, but I couldn't find how ([apparently this isn't trivial](http://stackoverflow.com/questions/34575066/how-to-prevent-cmake-from-issuing-implib)).

Any advice?

As always CMake-generated projects are hard to work with, since [all paths involved are hard-coded](https://cmake.org/Wiki/CMake_FAQ#Why_does_CMake_use_full_paths.2C_or_can_I_copy_my_build_tree.3F) (include paths, linker inputs, debug symbols etc. etc.).  These projects cannot be moved or source controlled or shared in any way. I'm considering adding a manually fixed VS solution. What do you think?

**Comment by KjellKod** [comment]
Let me take a look and see what's up. I mostly work with the OSX or Linux side and there CMake is easy.

I'll see if I can trigger this duplicate lib issue. If I understand you correctly however you would prefer to only have a shared lib, right? (And only with the above mentioned API exposed)

I can see if it's easy to make that by default and the static library could be an option (one or the other).

**Comment by OfekShilon** [comment]
I made the changes to make shared the default and export just the few
symbols that need exporting.  Should I make shared the only option? That
would resolve this issue - but how would it impact linux/osx?

On Aug 22, 2016 1:26 AM, "Kjell Hedström" <notifications@github.com> wrote:

Let me take a look and see what's up. I mostly work with the OSX or Linux
side and there CMake is easy.

I'll see if I can trigger this duplicate lib issue. If I understand you
correctly however you would prefer to only have a shared lib, right? (And
only with the above mentioned API exposed)

I can see if it's easy to make that by default and the static library could
be an option (one or the other).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/KjellKod/g3log/issues/112#issuecomment-241286244>, or mute
the thread

**Comment by KjellKod** [comment]
That can be taken care of with CMake options. You can always just make a pull request and we can look and try out the changes. 

I can try it out on OSX + Windows and get back to you

**Comment by OfekShilon** [comment]
Issue solved. in Build.cmake,
```
   add_library(g3logger_shared SHARED ${SRC_FILES})
   set_target_properties(g3logger_shared PROPERTIES
      LINKER_LANGUAGE CXX
      OUTPUT_NAME g3logger
      CLEAN_DIRECT_OUTPUT 1)
```

should be fixed to 
```
   add_library(g3logger_shared SHARED ${SRC_FILES})
   set_target_properties(g3logger_shared PROPERTIES
      LINKER_LANGUAGE CXX
      OUTPUT_NAME g3logger_shared
      CLEAN_DIRECT_OUTPUT 1)
```

**Comment by KjellKod** [comment]
Thanks.

Agreed that this can be cleaned up. The fix is slightly more involved since it has to be in sync with the building in g3sink's repository.

 I'm considering the following

1. Only have 1 build type option at a time: shared or static

2. Only use 1 name for the library and skip the "_shared". If I remember correctly all OSs involved (OSX, Linux, Windows) have specific suffix to file depending on whether it is static or shared library.

There was a community pull request late last year I believe or early this year (I've to go back and check) which targeted Windows builds and library types and something must have gotten screwed up in this section.  
--> I.e Maybe the Windows "_shared" was left intentionally for some reason? Only pull request digging will tell.

**Comment by OfekShilon** [comment]
I just implemented a similar decision in my fork (only shared, export only the needed parts).  Hopefully it's visible and maybe even useful.

Another question: have you considered unicode conformance?  It might make the library even more useful.  Ideally the code itself would be charset agnostic - in MSVC (at least) there are numerous macros for that -  and a single compiler switch would alternate character sets.

**Comment by KjellKod** [comment]
Hi,

Unless I am mistaken the unicode issue is a Windows issue only.  There are
several asian, middle-eastern companies that use g3log on Linux and it
seems to work for them.

I am not standing in the way of unicode changes but I am not pushing for
them either.

**Comment by KjellKod** [comment]
resolved elsewhere
