### ISSUE TITLE
Setting the minimum log-level at compile time?

### ISSUE THREAD

**Issue by felixendres** [KjellKod/g3log#116]
Hi, 
I read the documentation, but couldn't find whether one can disable log messages at compile time. glog has  a define GOOGLE_STRIP_LOG. If set, the log messages don't even appear in the compiled binary. Is that possible with g3log?

And related to that, is there something like glog's DLOG(...) macro, that is controlled via the NDEBUG define?

**Comment by KjellKod** [comment]
Hi

When the enabling/disabling of logging levels was discussed (years ago) the majority wanted runtime changing of it. I decided for a compromise.

There is a CMake compile option (see the API doc) that has to be enabled to get runtime enabling/disabling of levels. If you add custom logging levels at runtime that option needs to be turned on

Without the CMake option turned on you can only use the default logging levels and with no (albeit minuscule) runtime penalty for verifying the enabled/disabled state of the level. All default levels are always turned on.

If you need compile time disabling then the best way is to make that happen yourself. 

If you want to add it I'm happy to help out with ideas and code reviews for any pull request hat may come out of it.

**Comment by KjellKod** [comment]
No action at this time.
