### ISSUE TITLE
Debug assertion in wcsftime

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3log#121]
Is this due to the recent time changes possibly ?

Debug Assertion Failed!

File: minkernel\crts\ucrt\src\appcrt\time\wcsftime.cpp
Line: 1184

Expression: false

static const std::string time_formatted = "%H:%M:%S %f6";

The %f6 does not play well in msvc 2015 it seems, not sure what it should be yet

**Comment by KjellKod** [comment]
I have a pull request that should take care of it.
It's pending community review, please check it out

**Comment by cstamatopoulos** [comment]
The pull request seems to work for msvc 2015

**Comment by KjellKod** [comment]
Thanks for the feedback. I'll merge the pull request. It will fix things for many but for some it will cause issues with g3sinks

**Comment by KjellKod** [comment]
Fixed in : https://github.com/KjellKod/g3log/pull/119
