### ISSUE TITLE
building failed, not found  struct timespec in windows7

### ISSUE THREAD

**Issue by ycf8788** [KjellKod/g3log#122]
I create visual studio 2013 solution by cmake.
It say not found struct timespec when I building the solustion.
When I define struct timespec in time.hpp, also appear error,  it is "timespec_get func param error".
How to solve the problem?

**Comment by KjellKod** [comment]
You can try version 1 of g3log. Or g2log which is more forgiving for older compilers

**Comment by ycf8788** [comment]
Thank you for answer，Current version cann't apply to Windows?

**Comment by KjellKod** [comment]
It certainly can but not to VS2013

**Comment by KjellKod** [comment]
No current plan to support VS2013
