### ISSUE TITLE
MSVC wchar_t log messages

### ISSUE THREAD

**Issue by AndreasSchoenle** [KjellKod/g3log#123]
"Unicode" support was mentioned in #112. I also needed it in order to (almost) drop-in replace my current rather old homegrown log  implementation with g3log.  I took a shot [in this fork](https://github.com/AbberiorInstruments/g3log). 
It is only tested on windows and not in production yet. So I am not sure whether the code is ready for a pull request. 

I figured that no string conversions are desirable when creating the log message and that thus both wchar_t and narrow string messages need to remain possible within the same implemtation. Also the logging system should make minimal assumptions about the message encoding - rather the sinks should deal with it. I also did not want to touch the fatal log message handling which appends narrow string messages. 

Therefore my approach was to add a _wmessage member that will hold wchar_t based messages. The default message() method will concatenate the narrow string message to the wmessage (which will be converted to utf-8 assuming this is something reasonable for the default sink) if both are available. My sink implementations then deal with the _message and _wmessage members depending on their purpose. For example, a windows GUI element that shows current log messages will probably want everything as wchar_t while I write log messages to files in utf-8. 

If you are interested, I can create a pull request. 

Also, for my purposes I needed a quick way to add custom log levels without modifying the loglevels.cpp file and I wanted the full file path saved in the log message (I have a sink that outputs to DebugOut so all my MSVC TRACE(...) messages are replaced by log messages - but I need to maintain the ability to quick-jump to the source location). For this I keep the `const char *` from the **FILE** macro to avoid copying long strings.
Both small additions are also available as branches.

**Comment by KjellKod** [comment]
I took a quick peek at the code and the levels changes.

The levels changes look fine. Strictly speaking they are not needed but the change won't hurt either. Please  https://github.com/KjellKod/g3log/blob/master/API.markdown for details.

please put up a pull request for the wchar changes and I will try it on OSX and Linux. At first glance what struck me what that there are a few type changes but overall the logic is the same.
If you used "typedef" or the "using" keyword them you could replace these types for your typedef. If these defines are localized to one file (Say a new file : options.hpp) then the define can set wchar_t and wostringstream instead of the type it currently has. I.e he defines would stay in one file only and 
The types would change accordingly. The code logic changes would be minimal.

**Comment by AndreasSchoenle** [comment]
Thanks for the quick look at the code. I have done a pull request for the wchar_t code only (the addlevel and filepath parts are very small independent additions). I am not sure whether I understand what you mean with type changes, though. 
I wanted to make the wchar_t support optional, but if enabled, I wanted it to co-exist to avoid conversions on the message creation side. Thus the ifdef guarded additions.
If you have a proposal how to do it more elegantly, please let me know and I will try my best.

**Comment by KjellKod** [comment]
Here's an example:
// options.hpp

#ifdef ENABLE_WIN_WSTRING_SUPPPORT
using char_type=wchar_t
using ostream_type = std::wostringstream;
#else
using char_type=char;
using using ostream_type = std::ostringstream;
#end

Then in logcapture.hpp, instead of:
std::wostringstream &wstream() { .... } and std::ostringstream &stream() {
... }

It would be:
ostream_type &stream() { .... }


So, the* #ifdef's* would be reduced to one location  or at least greatly
reduced.
The code duplication would be a minimum.

**Comment by KjellKod** [comment]
It should also be wrapped in "namespace g3 { ..." the declarations in
options.hpp to avoid potential clashes with other types outside of the
g3log library.

**Comment by KjellKod** [comment]
Here's an example:
// options.hpp

```
namespace g3 {
#ifdef ENABLE_WIN_WSTRING_SUPPPORT
using char_type=wchar_t
using ostream_type = std::wostringstream;
#else
using char_type=char;
using using ostream_type = std::ostringstream;
#end
```

Then in logcapture.hpp, instead of:
```std::wostringstream &wstream() { .... } and std::ostringstream &stream() {
... }
```

It would be:
```
ostream_type &stream() { .... }
```

So, the* #ifdef's* would be reduced to one location  or at least greatly
reduced. The code duplication would be a minimum.

**Comment by KjellKod** [comment]
Hmmm. This was more complex then I thought. I assumed these were interchangeable on Linux / OSX but I think I was wrong:  http://stackoverflow.com/questions/8788057/how-to-initialize-and-print-a-stdwstring

**Comment by AndreasSchoenle** [comment]
Thanks. And yes, this would be possible if I wanted ONLY wchar_t messages. 
Sorry for not making this clear enough: 
My thinking was that most log messages will be available as narrow strings much more easily and only a few messages, namely coming from the GUI framework will be wchar_t. 
To avoid doing any kind of conversion when creating the log message (potentially slowing down the thread from which I log) I want the message object to hold a std::string and, optionally, an ADDITIONAL std::wstring and the sink to do the work. 

If both are set (i.e. a std::wstring fatal message where g3log adds the stacktrace as narrow string) the standard formatting will concatenate them bit every sink hand can handle messages any way it wants.
If I would opt for either wstring OR narrow string I will always have potential conversions upon message creation. In fact for wstring I will have them whenever incorporating e.g. an exception message retreived with what() into my log output.

In fact, to avoid any kind of conversion the message object would also have to store the encoding of its message members - but it seems like overkill. So for my app I just defined that the narrow message is utf-8 and the wide message utf-16 and in the few instances where I have some string in some locale dependent encoding I want to add to my log message I do the conversion grudgingly prior to message creation.

**Comment by AndreasSchoenle** [comment]
Yes, string encodings and locales are messy. In our project we usually have 3 encodings to deal with. UTF-16/UCS-2 for the Windows AP (stored in std::wstring)I, UTF-8 for files and all other kinds of persistent data storage and the system locale for calls to narrow string operating system APIs (mainly fstream and console input and output). On Linux the latter can be made UTF-8 but the Windows standard libraries do not allow this and we typically use the non-portable wide-character versions (an open() routine accepting wchar_t filenames, std::wcout, ...). In any case, we now try to avoid the third encoding and it is mostly possible.

The wchar_t or char16_t strings in UTF-16 encoding are necessary to avoid conversion every time we call a windows (and MAC OS X) API function and therefore many log messages are more naturally prepared using this encoding. 

Due to all this mess my feeling was that the logging framework itself should be agnostic to encoding issues. It just offers to store a std::string and a std::wstring in the log message (as a side remark, this may also be useful on Linux as QString uses UTF-16 internally). 

The only conversion g3log itself makes in its standard formatting function shall assume that the std::wstring is in UTF-16 and the std::string is in UTF-8. This assumption becomes meaningless as soon as someone implements a custom sink. In fact, even the provided file sink could deal with this if it would allow plugging in a custom message formatting function (something I wanted to do in the beginning but failed due to the private member) or at least converter.

This approach allowed me to make g3log a (much better) drop-in replacement for my current solution and even avoid a lot of UTF-8 to UTF-16 conversions I had on the log message creation side making that slower than need be.   
The alternative is to bury this and just say that people should convert to UTF-8 upon creation of the log message. However, this would mean a slowdown wherever the strings already exist or where they are much more easily prepared in UTF-16 because the string arguments to the formatting function are in UTF-16. Of course, I never really tried how much slower logging would get.

**Comment by KjellKod** [comment]
>> In fact, even the provided file sink could deal 
>> with this if it would allow plugging in a custom 
>> message formatting function (something I 
>> wanted to do in the beginning 

That's certainly easy to do. A custom sink has to provide one of two function APIs when it is added to the logger (I see now that e the sink example in the API doc is truncated, it should cover this)

1. A std::string receiving function. This is not what you want since it then follows the default formatting as laid out in the LogMessage class

Or 

2. A LogMessage receiving function. Here you can provide your own formatting. Each member in the LogMessage class is public so it's easy access

Here's an example of such a sink:
https://github.com/KjellKod/g3sinks/tree/master/snippets

There are more examples in the unit tests

**Comment by KjellKod** [comment]
(Ignore the enumeration it should be 1 and 2)

**Comment by AndreasSchoenle** [comment]
Thanks.
I have already implemented several custom sinks with LogMessage receiving functions to exactly this end with one of them being my file sink, sorry for the misunderstanding. 
What I meant is that when trying to "plug in" a custom LogMessage receiving function into your file sink implementation the fact that `filestream()` is a private method stopped me. 

Any thoughts on whether the pull request is worth considering at all?

**Comment by KjellKod** [comment]
I guess I don't understand the problem. 
Filestream is a function inside of the default logging sink. If you are rolling your own sink then you don't need it.

Feel free to rip, copy, borrow what you need from the default sink. The code is made public domain.

If you need to access the LogMessage struct then everything there is public:
https://github.com/KjellKod/g3log/blob/master/src/g3log/logmessage.hpp

**Comment by KjellKod** [comment]
added as a permanent branch: https://github.com/KjellKod/g3log/tree/wchar_support
