### ISSUE TITLE
CMake warnings because of unclear policy version ("CMP0054") in 'Build.cmake'.

### ISSUE THREAD

**Issue by dasmysh** [KjellKod/g3log#125]
A current version of CMake will show several warnings because it is not clear which policy to use when comparing string literals (see [CMake Help](https://cmake.org/cmake/help/v3.1/policy/CMP0054.html))

The issue can be resolved by putting
`cmake_policy(SET CMP0054 NEW)`
at the beginning of the file.

**Comment by KjellKod** [comment]
Perfect. Can you put up a pull request?

**Comment by dasmysh** [comment]
Did that. See #126 .

**Comment by KjellKod** [comment]
I'll see if I can update Travis. The CMake changes is currently braking the CI for this pull request

**Comment by KjellKod** [comment]
bump

**Comment by KjellKod** [comment]
merged: https://github.com/KjellKod/g3log/pull/136
