### ISSUE TITLE
More flexible log name

### ISSUE THREAD

**Issue by LePelicaN** [KjellKod/g3log#127]
Hi,

I'm back. :)
This time, I don't have an issue I can't solve but I was wondering if the solution wouldn't be better integrated in the library.

So, my situation is the following one : I would like to be able to name my file "my_project.log" and nothing else. By default, the current behavior is to add "g3log" and the date at the file creation.
I went to check your backlog and found a closed issue about the g3log optional (issues#75).

And therefore, here are the solution I've found :
* On my side, I could create a new sink but it would be really close to your FileSink. In fact, only createLogFileName would diverge.
* Another solution could be to have the date part optional too in the FileSink class.
* Last, and I'm getting perhaps falling a bit far for the tree now, I was wondering if the best behavior won't be to propose a dependency injection that would allow to add any postfix wanted. The default one would be something like : addIdAndDate.
The code of createLogFileName would end up something like :
```C++
std::string createLogFileName(const std::string &verified_prefix, const std::function<std::string()>& postfix_generator) {
      std::stringstream oss_name;
      oss_name << verified_prefix;
      oss_name << postfix_generator();
      oss_name << ".log"; 
      return oss_name.str();
}
```
(I'm even wondering if the ".log" part should be in the postfix_generator now.)

Do you see what I mean here? What do you think about all this?
If you think it's worth a try but don't have time, I can work on a pull request.

Thanks

**Comment by KjellKod** [comment]
Have you tried the log rotate sink at g3sinks? It allows you to name the file anything you want

**Comment by LePelicaN** [comment]
Hi,

Thanks for the fast answer.
I've seen it but didn't try yet since I was hoping to only package the main project.

**Comment by LePelicaN** [comment]
Hi,

LogRotate works correctly but I find myself with more than I want. I only need a simple sink to a file. Basically I only want the FileSink with a more simple name.

For now, I duplicate the three filesink files to my project and simply patch them to remove the date part.
I'm not really proud of this solution but it works.
I'm going next to automate the patch with the PATCH_COMMAND of ExternalProject_Add so it should better.

Anyway, I still think that it would be a good feature to be able to specify any file name for the basic file sink.
You don't seem to agree. Can I ask you why?

Thanks

**Comment by KjellKod** [comment]
I don't disagree. I just don't want to add the feature since it exist already in g3sinks.

If you, or someone else puts up a pull request for it then it has very high chance of getting in.

**Comment by KjellKod** [comment]
to be resolved by "community"  pull request if there is enough interest.

**Comment by LePelicaN** [comment]
Ok. Thanks a lot.

I will try to find some time to issue the pull request.
