### ISSUE TITLE
Signal Safety

### ISSUE THREAD

**Issue by bobkocisko** [KjellKod/g3log#130]
I am in the process of rolling my own fatal signal handling so that I can change the way fatal signals are reported in the log file and also add more details to the stack trace such as source file and line of the signal.  In the process I have been studying up on signal handling and also diving into the source of g3log to see how it is done here.  In the process I have come to be concerned about whether g3log is properly preventing corruption during signal handling.

For a simple example, let's look at the following lines of code.

``` cpp
// g3log.cpp
void initializeLogging(LogWorker *bgworker) {
  ...
  std::lock_guard<std::mutex> lock(g_logging_init_mutex);
  ...
}
void shutDownLogging() {
  std::lock_guard<std::mutex> lock(g_logging_init_mutex);
  ...
}
```

According to what I've read, acquiring a mutex takes more than one cpu instruction and so is not atomic.  This means that literally in the middle of the mutex acquire operation in `initializeLogging(...)`, a signal handler such as SIGTERM could begin running, which calls `shutDownLogging()` while running.  Now I believe that would probably result in bad things happening since the same mutex was only partially acquired and now is attempting to be acquired again.

I propose adding the following to the code
- Block all signals in the worker thread (via `pthread_sigmask(...)`), just to make sure the OS won't interrupt the worker thread to run a signal handler for the process and to limit the amount of code-specific signal blocking required.
- Around all `std::lock_guard<std::mutex>` statements and section of code that they protect, add signal blocking to make sure that those statements aren't interrupted mid-flight.  This could be avoided in sections of code that are never called by the signal handler.

What do you think? Are these good recommendations?  If so I can submit a pull request.

**Comment by KjellKod** [comment]
Thanks for the suggestion. 

A mutex can only be aquired once. So even if it is many instructions to take it you are guaranteed that only one thread can take it.

At shutdown scenario it's possible that multiple "crashes" happen. This can be seen sometimes in g3log as multiple SEGFAULTS or similar. It's still, AFAIK, fairly benign and results in multiple stacktraces before the shutdown of the logging has closed for more input.

Until I see evidence that it is not good enough I do not plan to change it.

**Comment by bobkocisko** [comment]
What I mean is that one thread, while it is in the middle of attempting to take the mutex, can be interrupted by the signal and proceed to the signal handler running in that same thread.  That will attempt to take the mutex again.  But it wasn't actually taken.  Or was it?  Now we're into unknown territory, because what is the state of the mutex at this point?  Additionally, if the mutex has already been taken by the thread that is interrupted, then it will allow that thread to take it again, meaning that the instructions which are supposed to be protected by the mutex are now vulnerable to unknown states due to race conditions.  Admittedly it's probably not terrible because even if it causes another segfault then you have a double crash and we're in shutdown mode anyways.  But it seems safer to just add blocking around the mutexes.  Now it could be a concern that the additional system call to block the signal would add a slight performance drag, but in that case I would recommend a compiler switch which could be turned off when the user prefers to risk incorrect behavior in exchange for speed.

**Comment by KjellKod** [comment]
You mean that the thread would get a segfault while it takes the mutex?    .... Yes if the g3log contains bugs in that area of the code it could absolutely happen. Or if the memory on the program is corrupted. 

I see you point. The thing is, dealing with crash handling is, unfortunately, undefined behavior from a standard point of view. There are also huge differences between Linux, OSX, Windows. 

For g4log I plan to make this simpler. Initially only supporting Linux (gcc) and OSX (gcc, clang). 

That said. Feel free to make a pull request. If I don't agree about the approach (I don't disagree either at this point) then please be aware that *many* users are viewing these pull requests and they will use them if they think it make sense.

**Comment by bobkocisko** [comment]
Mmm no, I mean that even if there are no bugs in the code it could get a segfault because of my understanding of the nature of signal interruptions.  But anyway, I am working on a pull request right now so perhaps that will help to clarify my suggestion.

**Comment by bobkocisko** [comment]
Ok today turned out to be a lot deeper research day.  This article* is very helpful to understand the intricacies and complexities surrounding signal handling.  It's only 135 'pages' long. :-)  

There is simply no way to know the state of the application when a signal handler begins and so in both Windows and POSIX there are only a few system functions permitted to be called from within a signal handler.  `man 7 signal` details them.  And none of those functions succinctly and neatly solve inter-thread communication problems nor provide proper protection for interacting with mutexes.  So it seems better to pursue some alternatives.

One alternative is what I was proposing earlier, to surround every mutex access lock in the code with `pthread_sigmask`.  But on 'page' 38 of the article--meaning press Page Down 38 times on a 1920x1080 screen in Google Chrome at 125% zoom--there is a chart showing benchmarks of a few key signal functions and `pthread_sigmask` is actually more expensive than `sigaction`!  Now since g3log is used in performance-critical applications, I don't think we want that kind of slowdown on every LOG call.

Another alternative would be to add a secondary background thread to g3log which has the sole function of calling `sigwaitinfo` in an endless loop and processing any signals that arrive.  The good news here is that there would be no signal handler involved for most of the signals and so none of the restrictions placed on signal handler code would apply.  This means that after receiving any of the desired signals, that secondary thread would be free to invoke code involving mutexes to interact with the primary background thread by posting a fatal message.  Now one annoyance with this plan is that we would still need a signal handler to deal with SIGSEGV and SIGBUS because without a signal handler registered for these two signals, any segfaults will not pause the application's execution--which is of course bad news.  So to handle these properly we would register a handler in the main thread for these two signals only and it would first set a `static volatile sig_atomic_t` flag and then call `pthread_kill` to interrupt the secondary background thread.  Both of these operations are legal in a signal handler.  Then the signal handler would sleep forever until the app gets shutdown by the primary background thread.  Another downside with this plan is of course that some users may be strongly against the addition of another thread into their programs.  However for my current project that is not a concern, especially since this thread will be just sleeping most of the time.

Another alternative would be to rework the `shared_queue::wait_and_pop` method so that it uses low-level OS calls rather than the high-level `std::condition_variable`.  For POSIX I would suggest using `poll` or `select` to wait on one `signalfd` descriptor and one `eventfd` descriptor simultaneously.  The `eventfd` descriptor would replace `std::condition_variable` and the `signalfd` descriptor would replace `sigwaitinfo`.  This plan would also require the use of a signal handler to handle SIGSEGV and SIGBUS as described above.  Now one concern I have with this plan is that it would introduce new platform-specific code in multiple code files such as `shared_queue.hpp`.  That may not be a big deal, but I like how the crash handler code is currently neatly tucked into two cpp files and I hate to propose a solution which starts to modify more files to be platform-specific.  However, the up-side with this plan is that there wouldn't be any more threads than we currently have.

Do you have a preference as to which of these approaches I pursue for my pull request?  If you don't, I would probably go with the second alternative (adding a secondary background thread) because it seems like that would have the best chance of avoiding any regressions as well as keeping the platform-specific code separate from the core code.  And as I mentioned before, I have no real concern about adding another thread to the library.

P.S. My focus has been almost exclusively on Linux/POSIX which is all I need at the moment.  The basic principles appear to be the same for Windows signal handling but I'm not sure.

\* ftp://linuxmafia.com/faq/Devtools/signals.html

**Comment by KjellKod** [comment]
I'm curious what will come out of your second approach.

**Comment by KjellKod** [comment]
Any actions coming out of this? I'm closing this for now but I am looking forward to pull request or if you want me to review something on a fork of g3log. 

cheers
Kjell

**Comment by bobkocisko** [comment]
Kjell, sorry for disappearing.  I was researching this for a project at work but then I had to switch away from that project right after I sent you the last message so I haven't started doing anything yet.  I've been planning to work on it in personal time but it hasn't happened yet.  It's high on my personal time projects list but I can't promise when it will happen.  It makes sense to close this for now.

**Comment by KjellKod** [comment]
No worries. Let me know if you take it up again
