### ISSUE TITLE
some warnings

### ISSUE THREAD

**Issue by ctapmex** [KjellKod/g3log#14]
Hi.
some warnings in mingw 4.9.3 
g3log\src\g3log\stacktrace_windows.cpp:28:9: warning: #pragma once in main file

g3log\src\g3log\stacktrace_windows.cpp:85:9: warning: unused variable 'noErrors' [-Wunused-variable]
    auto noErrors = TRUE; // Why, Oh Why have Microsoft redefined bool?
         ^

**Comment by KjellKod** [comment]
Tx

**Comment by KjellKod** [comment]
Fixed in https://github.com/KjellKod/g3log/pull/17
