### ISSUE TITLE
c++98 version

### ISSUE THREAD

**Issue by geronimo22** [KjellKod/g3log#140]
Hello - just checking if there's a version of g3log that works with C++98 compiler?

**Comment by KjellKod** [comment]
You can try g2log and replace all c++11 constructs för posix alternatives. I.e std::thread, mutex etc 

For the function that deals with std::futures I would just remove them completely

**Comment by KjellKod** [comment]
I'm closing this since there is no action on g3log or the g2log repositories. Feel free to reach out to my personal email if you need further advice.
