### ISSUE TITLE
Log Macros issues in if statements

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3log#142]
Currently you can get some subtle bugs introduced when you do something like this

    if (someTest)
      LOG(WARNING) << "Log issue";
    else
       // do something

The else function will never be reached if someTest = false as the else is attached to the if from the Macro.
Some interesting things could happen as well if `if(g3::logLevel(level))` returns false as the else will be called in that case.

There are also other ways to do it via `do while` or `if (1) else`.

I know I can use LOG_IF and then do something like if (!someTest) but this will cover all cases I think

**Comment by KjellKod** [comment]
Please put up a pull request if you know how to address it.

**Comment by cstamatopoulos** [comment]
Well there are 3 ways to kind take care of it, none being nice ! 

    #define FOO(X) do { code; } while (0)
    #define FOO(X) if (1) { code; } else

These first one out of these 2 is more common as far as I am aware.
Both of these have no issue with adding a ';' after the Macro statement

Contrary just wrapping with curly braces does result in a compile error if you add a ';' after the Macro statement when an else statement is following. The issue only occurs when the if does not have any scope guard. In every other case it is fine...

**Comment by KjellKod** [comment]
In the first code snippet you had 
LOG(WARNING) << "Log issue"

Are you saying that this occurs because the coder didn't add a ";" semicolon after the log statement?

**Comment by cstamatopoulos** [comment]
No that was an oversight.

Here is the full expanded macro in such a case

    if (boolean)
      if(g3::logLevel(level)) INTERNAL_LOG_MESSAGE(level).stream();
    else
      foo();

As you can imagine the else foo clause in this case is matched to the if of your Macro so if boolean = false it will never be called.

**Comment by KjellKod** [comment]
One possible way format would be to use the `?` operator instead of the if-cases. I see the issue here and I'm glad you brought it up.

**Comment by cstamatopoulos** [comment]
Well the easy way is to always use scope guard in your if else when g3log is involved.

I had seen in the past but never mentioned it before. I was refactoring some code recently and wanted to add some logging and I found out that the actual code was always skipped due to that.
I had forgotten that I had seen in the past so I was bitten by it and wanted to make sure that this is somehow addressed but more importantly known.

**Comment by KjellKod** [comment]
having the semicolon at the end is not possible. The stream input cannot be captured if that is there. 
`if(g3::logLevel(level)) INTERNAL_LOG_MESSAGE(level).stream();`

Likewise 
`if(g3::logLevel(level))  {INTERNAL_LOG_MESSAGE(level).stream();}`
or 
`if(g3::logLevel(level))  {INTERNAL_LOG_MESSAGE(level).stream();}`

**Comment by KjellKod** [comment]
@cstamatopoulos , I confirmed a suspicion that this is no simple task (Or I am just too tired now to code...)
Ref: http://ideone.com/tlphQ5

If you find a solution, feel free to play around with the ideone draft, then I will look into this some more. As it is now I am unfortunately forced to suggest that you use `{` around your if-statements. 

I haven't been hit by this myself most likely since  I.M.O the most common c++ coding style is to always have `{` brackets for if-statements. 

This is of course a terrible reply to the issue you opened and if you see a working solution (so far I have not seen one) then I would very much be interested. 

Thanks
