### ISSUE TITLE
I got a funky build message from the latest release...

### ISSUE THREAD

**Issue by BoredBored** [KjellKod/g3log#149]
Note: My OS is ubuntu 16.10

So what I did was 
1. download the tar.gz of the stable release
2. extracted it
3. went to the folder & opened the terminal
4. typed in: sudo su;mkdir build;cd build;cmake -DCMAKE_BUILD_TYPE=Release ..;make
and when it does 'make' I get some build errors (shown below)

[![Screenshot from 2017-01-20 11-14-28.png](https://s29.postimg.org/yd17bnmgn/Screenshot_from_2017_01_20_11_14_28.png)](https://postimg.org/image/4l44wgzn7/)

also I was wondering, is this a header only library?

**Comment by KjellKod** [comment]
From your screenshot these looks like warnings, not errors, right?

It is actually part of the example executables (fatal choice)  and illegal format examples that can, on some OS, create a crash. It is an example to showcase that the logger can catch a sigsegv and present the stackdump and shutdown in an orderly manner. 

g3log is not a header only library.
