### ISSUE TITLE
capturef should use the _Printf_format_string_ annotation on MSVC

### ISSUE THREAD

**Issue by saul** [KjellKod/g3log#15]
See https://msdn.microsoft.com/en-us/library/vstudio/ms235402(v=vs.100).aspx

The capturef signature can be changed to:
```cpp
void capturef(_Printf_format_string_ const char* printf_like_message, ...) __attribute__((format(printf, 2, 3)));
```

It may make more sense to have two seperate declarations - one for GCC, one for MSVC and one for others.

**Comment by KjellKod** [comment]
Hi Saul, 

It sounds like a good suggestion.  If you want to expediate this, feel free to do a pull request. 
Cheers
Kjell

**Comment by KjellKod** [comment]
@saul this issue is nearing one year mark. So far no one else has chimed in and I have not seen a pull request to deal with the Windows part of this so it is a candidate for being closed.

**Comment by KjellKod** [comment]
resolved here: https://github.com/KjellKod/g3log/pull/129
