### ISSUE TITLE
Continue logging after a fork

### ISSUE THREAD

**Issue by ranft** [KjellKod/g3log#151]
At the moment I struggle to get the log library to work in a daemon, since after the fork() call the log stops in the child process. The following program gives only the messages from the parent process, while the child process keeps silent.

    #include <iostream>
    
    #include <unistd.h>
    
    #include <g3log/g3log.hpp>
    #include <g3log/logworker.hpp>

    struct StdoutSink {
      void ReceiveLogMessage(g3::LogMessageMover log_entry) {
         std::cout << log_entry.get().toString() << std::flush;
      }
    };

    int main()
    {
        auto lw{g3::LogWorker::createLogWorker()};
        auto stdoutHandle{lw->addSink(std2::make_unique<StdoutSink>(),
                                      &StdoutSink::ReceiveLogMessage)};
        g3::initializeLogging(lw.get());

        LOG(INFO) << "Startup";

        const auto pid = fork();
        LOG(INFO) << "pid=" << pid;
        return 0;
    }

When I run the software, I get the following output:

    $ g++ -std=c++11 demo.cpp -odemo -lg3logger -lpthread && ./demo
    2017/02/14 10:58:51 0	INFO [foo.cpp->main:21]	"Startup"
    2017/02/14 10:58:51 130	INFO [foo.cpp->main:24]	"pid=30073"

But the line I expect from the child is missing.

**Comment by KjellKod** [comment]
In C++ it is undefined behavior to have threads running and then the process are forked. It might have worked for you before but it is just a matter of time before you will start to get weird crashes. 

Any threading such as the g3log initializations should be done after the fork.  Even better: don't mix threaded code and forked code at all. 

Ref: http://www.linuxprogrammingblog.com/threads-and-fork-think-twice-before-using-them

**Comment by KjellKod** [comment]
If you need to juggle ideas on how to proceed with this then (_after googling the common issue of forks and threads_) then feel free to reach out. I have run into this issue before and knows a few ways around it. You can reach me at `Hedstrom at KjellKod dot cc`
