### ISSUE TITLE
g3log crashing in dll

### ISSUE THREAD

**Issue by javiherbar** [KjellKod/g3log#154]
Hi, i'm having some issues implementing g3log into a dll.

I've successfully implemented the logger inside the main function of a test program, but when I try to implement it on a dll, it crashes.

This happens when creating the logworker, via the command:
`std::unique_ptr<LogWorker> worker{ LogWorker::createLogWorker() };`

So far, I've tried defining the worker as a global pointer and as a unique pointer, both in the definition space and inside the DllMain, crashing in both situations.

I really appreciate any help you could give me.
Thanks in advance

**Comment by KjellKod** [comment]
The global approach does not work. The g3log relies on proper RAII scoping. 

Please see windows specific DLL resolutions in previous issues regarding this
1. https://github.com/KjellKod/g3log/issues/88#issuecomment-219030139
2. https://github.com/KjellKod/g3log/issues/91
