### ISSUE TITLE
crash on xp with v140_xp toolset

### ISSUE THREAD

**Issue by wangjieest** [KjellKod/g3log#155]
I used g3log on vs2015 and then support xp. choose the v140_xp toolset .
with vs2015's issue, add compile flags /Zc:threadSafeInit- (which removes magic static).
it crashes.

**Comment by ctapmex** [comment]
cpu  - AMD ?

**Comment by KjellKod** [comment]
What crashes? VS2015?

I haven't run it in a long time, have you @ctapmex?  _My fear with VS2015 is that it might not be C++11 compliant._ 

@wangjieest please explain more about the issue.

**Comment by wangjieest** [comment]
issue as https://connect.microsoft.com/VisualStudio/feedback/details/1789709/visual-c-2015-runtime-broken-on-windows-server-2003-c-11-magic-statics says. magic static has bugs on xp when as a dynamic loaded dll. and It seems no guys will fix it. 
so there should be some workarounds.
I found it crashes because the thread_local keyword on
 thread_local const auto os =
         time_point_cast<nanoseconds>(system_clock::now()).time_since_epoch() -
         time_point_cast<nanoseconds>(high_resolution_clock::now()).time_since_epoch();

cause timespec_get is called on init log.
 I fixed it by changing the thread_local to static .

**Comment by ctapmex** [comment]
There is also an error when working on AMD processors in winxp
https://github.com/colorer/g3log/commit/ad3e05cf17750b852556d59c313fe3ebfab5a488

**Comment by wangjieest** [comment]
@ctapmex yes, I also found some crashes based on CPU.
there is a overflow of now_ns in timespec_get function. 
because the first high_resolution_clock::now() may get the bigger number which makes ts ->tv_nsec an negative number.
internal::to_string function may throw exception because "zeroes - value.size()" become negative.

**Comment by KjellKod** [comment]
I don't see how `ts->tv_nsec` can ever be negative but I might be missing something obvious. 
Are you on a 32 bit platform?

**Comment by wangjieest** [comment]
@KjellKod yes crash rate is about one in a million.

**Comment by KjellKod** [comment]
OK. 

I think a straightforward fix would be to check for negative values and then just force them to zero. Would that be an OK solution for you?

**Comment by KjellKod** [comment]
This should address the issue you mentioned last, when the time correction becomes negative: https://github.com/KjellKod/g3log/pull/159

**Comment by KjellKod** [comment]
@ctapmex can you open a pull request for the fix in https://github.com/colorer/g3log/commit/ad3e05cf17750b852556d59c313fe3ebfab5a488

**Comment by KjellKod** [comment]
time adjustement added in: https://github.com/KjellKod/g3log/pull/161
