### ISSUE TITLE
Select user own log file name without date / time attached and modification

### ISSUE THREAD

**Issue by jupiterh** [KjellKod/g3log#157]
Hi,

I set addDefaultLogger("app.log", "/var/log/dev"), then the g3log inserted date time tot the log file name "applog.g3log.20170328-215754.log". Any options / flags to disable g3log to modify the log file name?

In Linux application, I'd like to have a simple log file name such as /var/log/dev/app.log, and I can set up logrotate to rotate the log file size and to clean up old log files to prevent disk full.

Thank you and appreciate your tips.

**Comment by KjellKod** [comment]
Have you looked at the logrotate sink at g3sinks?
https://github.com/KjellKod/g3sinks/blob/master/README.md

From your description I think it fulfills all of your requirements

**Comment by jupiterh** [comment]
Thanks for your response. Sorry regardless of logrotate, there are other things we like to use a single log file name without date / time attached to it, is it possible to configure g3log not to modify the log file name?

Thank you for this great program, appreciate your comments.

**Comment by KjellKod** [comment]
That's exactly what you get with the logrotate sink. Please check the API and try it out

**Comment by KjellKod** [comment]
@jupiterh did it work out with the sink?

**Comment by KjellKod** [comment]
closing due to lack of response
