### ISSUE TITLE
Adding custom log levels to dynamic logging

### ISSUE THREAD

**Issue by Jawan81** [KjellKod/g3log#162]
Hi KjellKod
Thanks for your great logger. 
There is one issue I don't find a way to solve: I have defined additional debug levels (e.g. LEVELS ERROR) and want to activate/deactivate them dynamically. But as far I can see one can only do it for the preconfigured log levels (INFO, WARNING etc.) because there seems to be no way to add custom LEVELS to g_log_level_status in loglevels.cpp.
Or am I overlooking something?!
Thanks

**Comment by Jawan81** [comment]
I just noticed you seem to have already done some work on this subject ([commit](https://github.com/KjellKod/g3log/pull/161/commits/26912c4833301f2feccf5c6e0e7c90eb5ed3c241)). When do you think these changes will be merged to master or - even better - when will they become part of a new release?

**Comment by KjellKod** [comment]
With "setLogLevel" you can do exactly that. Please see my recent Pull Request(PR) -  feel free to comment on it. 

https://github.com/KjellKod/g3log/pull/161

The purpose of the PR is to make it easier for coders to understand and use dynamic logging 
I.e enabling/disabling/adding levels of their own choice without having to change the g3log source code.

All the modified and updated APIs have unit tests in the PR that showcase the usage

**Comment by KjellKod** [comment]
As soon as I've reviewed it and hopefully someone else have reviewed it I'll get it merged.

**Comment by KjellKod** [comment]
I'm planning on a release just before merging this since this release changes the scope from c++11 to c++14.

Since the logging level changes are quite important I might turn around and do a small release immediately after this and one more PR is merged

**Comment by Jawan81** [comment]
Thank you for the quick response!

**Comment by KjellKod** [comment]
Until it is merged you can still use the 'setLogLevel' function. If I remember correctly it'll add the level used as argument if it didn't exist already - that part of the API will stay the same

**Comment by KjellKod** [comment]
https://github.com/KjellKod/g3log/pull/161

**Comment by Jawan81** [comment]
The problem with setLogLevel is that it is only save to use it before initialization (as stated by the comment on the only_change_at_initialization namespace: "Only safe if done at initialization in a single-thread context"), but I will need be able to change the log level during runtime.
I solved the problem for now with an extra sink that delegates to the "real" sinks only if the respective log level of the message is active. This extra sink is the only one G3Logs reports to.

**Comment by KjellKod** [comment]
Thanks for the explanation. For the logging level to be synchronized for each message between threads it might need a different design. 

Already it IS using an atomic value for the status but I've not verified that it is in fact thread safe but I believe it is on x86_64 platforms.

The "only at initialization" is my warning to developers as I haven't proven it'll work across platforms

**Comment by KjellKod** [comment]
(Deleted and remade this comment)

Thanks for the explanation.

That is correct.

Just to clarify:
 If you add logging levels at a single thread context then once you have started up more threads you , can across threads,  safely disable and enable the individual logging level. These changes will be synchronized across threads.

It would certainly be interesting to make all of the logging level functionality (add, reset of levels) thread safe. At the moment I believe it may already be on some platforms but not on others.

**Comment by Jawan81** [comment]
I don't need to add custom log levels during runtime after the other threads are started, so what I want (enable/disable logging levels during runtime) should already work according to your explanation. But I find it weird to call something in the `only_change_at_initialization` namespace if this is exactly what I do _not_ do ;-). It will be hard to comprehend for other developers when they stumble over this code later.

**Comment by KjellKod** [comment]
I hear you and I've thought alongside the same lines. 

The way I am pondering doing this is the following:

```only_change_at_initialization``` is kept for `addLogLevel(...)`, `reset(..)` or any other function that changes the number of logging levels. 

Potentially new functions that I am considering
`changeLogLevel(LEVEL, bool)`, 
`enabledLogLevel(LEVEL)`, 
`disableLogLevel(LEVEL)`  
will be a new functions that changes the enabled/disabled status.  This will *not* be within the ```only_change_at_initialization``` namespace level but at ```g3``` level. 

`setLogLevel` will be removed since it was a SRP violation anyways and it is not thread safe to use it to add a new logging level in a multi threaded context environment. 

I hope this would make the API clearer. The caveat to this is that it is a *breaking* change but hopefully very easy for developers to adopt to the improved API. 

Does the outline above make sense?

**Comment by Jawan81** [comment]
This sounds great! I would really appreciate the new API (apart from the typo in `enabledLogLevel`: It probably should be `enableLogLevel`). 
It would be a very tiny but useful breaking change. So I think not only me would appreciate it. I give you both thumbs up to it!

**Comment by KjellKod** [comment]
Cool.

I'll let you know once the PR is up so you can review it.

Cheers
Kjell

* Contact Information
* Kjell Hedström
* Mobile:  +1 - 617.378.1915
* E-mail: Hedstrom@KjellKod.cc

**Comment by Jawan81** [comment]
Furthermore I would also appreciate if there was only 'one version' of g3log if you consider dynamic logging: Now you have have to choose during compile time of the library which version you want. If you choose the one without dynamic logging and you have custom log levels you must *not* use the access functions `setLogLevel`, `addLogLevel` etc., because they are not even compiled. 
If you want to change to dynamic logging you have to recompile the library. If you don't do anything then, your custom log levels are suddenly ignored. You now *have to* use `setLogLevel/addLogLevel` if you don't want them to be ignored.

This is what I mean with two g3log versions: If you switch from one to another the behaviour is different concerning custom log levels.

From my point of view it would be better if dynamic logging was always active and you _must_ call addLogLevel/setLogLevel anyway if you want to use a custom log level - whether or not you want to disable/enable it later during runtime.

This would have the following advantages:
- Only one version of the library: you wouldn't need to switch back and forth by recompiling/reinstalling
- Adding custom log levels would be the same whether or not you use dynamic logging as opposed to how it is now, where you either must or must _not_ call the access functions

The only disadvantage would be the tiny table lookup time, which is negligible in my eyes, especially because it runs in a different thread than my application. But this is my subjective opinion and I don't know if other users really need to squeeze out every tiny bit of performance. To be sure one could  measure the time difference and if it is as tiny as I expect it to be it might hopefully be worth to harmonize the interface.

**Comment by KjellKod** [comment]
I don't think that will change for some time.

There are more #define change one can make with the library.
One option for you could be to install them in different locations. I don't
really understand the use case but you could install one to /usr/local/lib
and the other one to a custom /usr/local/debug/lib.

that way you could have both installed and depending on what version/linked
version of your software you are running it would use one or the other.

Of course if you linked to the wrong version you would get a link error so
you wouldn't risk using the wrong one.




* Contact Information
* Kjell Hedström
* Mobile:  +1 - 617.378.1915
* E-mail: Hedstrom@KjellKod.cc

**Comment by KjellKod** [comment]
Please see pull request: https://github.com/KjellKod/g3log/pull/168

It was late when I added it so I will re-review it myself to make sure I didn't mess up. Please review it and see if it conforms to what we talked about. 

Thanks

**Comment by KjellKod** [comment]
solved in https://github.com/KjellKod/g3log/pull/170
