### ISSUE TITLE
Incorrect handling of DEBUG when G3_DYNAMIC_LOGGING is enabled

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3log#171]
loglevels.cpp uses DEBUG without checking CHANGE_G3LOG_DEBUG_TO_DBUG

```
#ifdef G3_DYNAMIC_LOGGING
      const std::map<int, LoggingLevel> g_log_level_defaults = {
         {g3::kDebugValue, {DEBUG}},  // error here
         {INFO.value, {INFO}},
         {WARNING.value, {WARNING}},
         {FATAL.value, {FATAL}}
      };

      std::map<int, g3::LoggingLevel> g_log_levels = g_log_level_defaults;
#endif
```

**Comment by cstamatopoulos** [comment]
Just need to change it to 
```
#if (defined(CHANGE_G3LOG_DEBUG_TO_DBUG))
		  {g3::kDebugValue, {DBUG}},
#else
		  {g3::kDebugValue, {DEBUG}},
#endif
```

**Comment by KjellKod** [comment]
Thanks Christos.

I have not forgotten about them, they are very high on my todo list. Right now I'm swamped with work but I'll get to them as soon as I can

Cheers
Kjell

**Comment by KjellKod** [comment]
fixed in pull request: https://github.com/KjellKod/g3log/pull/178

**Comment by macdew** [comment]
This appears to have regressed in loglevels.hpp, this now errors out in builds with this flag set.

**Comment by KjellKod** [comment]
@macdew : correct. I’ve verified this in - https://github.com/KjellKod/g3log/pull/178/files#diff-3264ab8e986152450ab1a0df676f7f5cL93

I’m re-opening the bug again

**Comment by KjellKod** [comment]
I was too quick to jump the gun on this one @macdew 
Looking through the code I see that the DBUG / DEBUG handling was moved from the hop to the cop file. 

I also see that we are building with this flag set, on Windows, every time. 
Please show how it’s breaking for you and what build options you are using.

Ref: 
1. https://github.com/KjellKod/g3log/blob/master/src/loglevels.cpp#L22
2. https://github.com/KjellKod/g3log/blob/master/appveyor.yml#L31

**Comment by KjellKod** [comment]
I’m confident this isn’t broken. I’m leaving the bug open for a short time @macdew waiting for you to debug your setup and potentially show that it is indeed broken. 
Please provide information of
A. System
B. Cmake build options
C. Code snippet that does no longer work. 

Please check 1-3 (especially 3) in my previous comment. Potentially you should update your code and that will fix this issue

**Comment by macdew** [comment]
Thanks for the quick response @KjellKod 

I may have jumped the gun too here.  I added DEBUG + CHANGE_G3LOG_DEBUG_TO_DBUG to my project definition, and this failed on loglevels.hpp line 93.  However, I realise that I did not rebuild g3log itself with CHANGE_G3LOG_DEBUG_TO_DBUG, which presumably I should do in order for the flag to take full effect?

**Comment by KjellKod** [comment]
Yes.

**Comment by KjellKod** [comment]
@macdew  can this be closed?

**Comment by macdew** [comment]
@KjellKod Yes I think so.  I rebuilt g3log today with said flag, confirmed that it was present in the generated definitions header, and can now build successfully with DEBUG defined globally.  Apologies for the noise.

**Comment by KjellKod** [comment]
thanks!
