### ISSUE TITLE
Windows build issues with CMAKE

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3log#174]
It has been sometime since I last pulled but in the past static and shared build used to work correctly.
Now whatever you choose you get a shared build (in windows and probably in any other platform as well).

It is pretty clear from the new cmake that the library is always shared
`ADD_LIBRARY(${G3LOG_LIBRARY} SHARED ${SRC_FILES})`

Instead it should have been something along the lines of 
```
   IF (G3LOG_BUILD_SHARED)
     ADD_LIBRARY(${G3LOG_LIBRARY} SHARED ${SRC_FILES})
   ELSE
     ADD_LIBRARY(${G3LOG_LIBRARY} STATIC ${SRC_FILES})
```
Also it seems that only 1 project is generated and not 2 compared to the past.
Nothing wrong with that but then the flag ADD_BUILD_WIN_SHARED is kind of misleading since you never really add another build but instead the ADD_BUILD_WIN_SHARED flag is only handled to export the symbols. If you want to have a shared build in MSVC that is the only way to export the symbols, unless you go down the path of __declspec(dllexport) and __declspec(dllimport). So if it is MSVC and someone wants to have a shared build this should be set always set
`set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)`
If cmake < 3.4 the cmake should fail since the shared build wont be usable as no symbols are exported.

**Comment by KjellKod** [comment]
Agreed that I should have cleaned it up better.

**Comment by cstamatopoulos** [comment]
This requires changes to 2 files

1st: Options.cmake
```
    option (ADD_BUILD_WIN_SHARED  "Build shared library on Windows" OFF)
       IF(ADD_BUILD_WIN_SHARED)
          MESSAGE("-DADD_BUILD_WIN_SHARED=ON") 
       ELSE() 
          MESSAGE("-DADD_BUILD_WIN_SHARED=OFF") 
      ENDIF()
```
To
```
    option (G3_SHARED_LIB  "Build shared library" ON)
       IF(G3_SHARED_LIB)
          MESSAGE("Building shared library") 
       ELSE() 
          MESSAGE("Building static library") 
      ENDIF()
```

By default we will always build a shared library so this wont affect *Nix, Mac

2nd : Build.cmake

Change 
`   ADD_LIBRARY(${G3LOG_LIBRARY} SHARED ${SRC_FILES})`
To
```
   IF(${G3_SHARED_LIB} STREQUAL "ON")
     ADD_LIBRARY(${G3LOG_LIBRARY} SHARED ${SRC_FILES})
   ELSE()
     ADD_LIBRARY(${G3LOG_LIBRARY} STATIC ${SRC_FILES})
   ENDIF()
```
   
Here is where we specify what library based on what the user asked

And
```
   IF(NOT ${ADD_BUILD_WIN_SHARED}.x STREQUAL ".x")
      IF(NOT(CMAKE_VERSION LESS 3.4) AND MSVC)
         set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
      ENDIF()
   ENDIF()
```
To
```
   IF(${G3_SHARED_LIB} STREQUAL "ON")
      IF(NOT(CMAKE_VERSION LESS 3.4) AND MSVC)
         set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
      ELSE()
         message( FATAL_ERROR "No symbols will be exported." )
      ENDIF()
   ENDIF()
```
Finally if user requested shared on MSVC, better have CMAKE > 3.4 otherwise fail.

**Comment by KjellKod** [comment]
Thanks Christos.

I have not forgotten about them, they are very high on my todo list. Right now I'm swamped with work but I'll get to them as soon as I can

Cheers
Kjell

**Comment by cstamatopoulos** [comment]
No problem, I just provided a sample implementation hoping it is helpful!
Also note that the new way you are doing the git versioning uses bash.
That is not going to work on Win.

**Comment by KjellKod** [comment]
Do you know how to get to the information on Windows -without access to
bash?

* Contact Information
* Kjell Hedström
* Mobile:  +1 - 617.378.1915
* E-mail: Hedstrom@KjellKod.cc

**Comment by cstamatopoulos** [comment]
Not sure exactly what you are trying to achieve here but check this out.

in cmd 
```
C:\Users\Christos>cd c:\src\g3log

c:\src\g3log> git rev-list --branches HEAD | find /c /v ""
526

c:\src\g3log>
```

in powershell
```
PS C:\Users\Christos.GSI> cd C:\src\g3log\
PS C:\src\g3log> (git rev-list --branches HEAD | Measure-Object -line).Lines
526
PS C:\src\g3log>
```

**Comment by AndreasSchoenle** [comment]
I have added the G3_SHARED_LIB option into my mull request #178. Hope this is ok.

**Comment by KjellKod** [comment]
@AndreasSchoenle  thanks I'll look into it. 

I tried to duplicate the git version issue with a beta-testing of the AppVeyor cloud CI for windows.  I've just started to use it so there's a few issues with it but regardless the git version parses just fine on that one. 

Ref: https://ci.appveyor.com/project/KjellKod/g3log/build/1.0.4

@cstamatopoulos what is the error message you get when it tries to parse the error message?

**Comment by cstamatopoulos** [comment]
Extracting git software version
CMake Error at CMakeLists.txt:75 (math):
  math cannot parse the expression: "/255": syntax error, unexpected
  exp_DIVIDE, expecting exp_PLUS or exp_MINUS or exp_OPENPARENT or exp_NUMBER
  (1)


CMake Error at CMakeLists.txt:76 (math):
  math cannot parse the expression: "%255": syntax error, unexpected exp_MOD,
  expecting exp_PLUS or exp_MINUS or exp_OPENPARENT or exp_NUMBER (1)

**Comment by KjellKod** [comment]
@cstamatopoulos and just to rule out cmake version issue, what is the cmake version you are using?

**Comment by cstamatopoulos** [comment]
@KjellKod Latest and brightest 3.8.0

**Comment by cstamatopoulos** [comment]
@KjellKod The problem is that ${GIT_VERSION} is empty since the previous line fails

**Comment by cstamatopoulos** [comment]
@KjellKod This seems to work for me, I can also check for cmd line instead of powershell

`execute_process(COMMAND powershell "cd ${CMAKE_SOURCE_DIR}; (git rev-list --branches HEAD | Measure-Object -line).Lines" OUTPUT_VARIABLE GIT_VERSION)`

Cmake output
> 
> A 64-bit OS detected
> Extracting git software version
> git build version: 526
> 
> version base: 2
> version remainder: 16
> Software Version: 1.3.2-16

**Comment by cstamatopoulos** [comment]
@KjellKod I can confirm that this also works
`execute_process(COMMAND cmd "/c" "cd ${CMAKE_SOURCE_DIR} & git rev-list --branches HEAD | find /c /v """ OUTPUT_VARIABLE GIT_VERSION)`

**Comment by KjellKod** [comment]
@cstamatopoulos thanks.  That seems to work with the cloud CI.  The windows build version issue should be fixed with the merged pull request: https://github.com/KjellKod/g3log/pull/180

**Comment by KjellKod** [comment]
left for windows 
- static/shared library building
- exporting options
- log level: dbug instead of debug
- ref also ```the G3_SHARED_LIB option into my pull request #178. ```

**Comment by AndreasSchoenle** [comment]
> execute_process(COMMAND cmd "/c" "cd ${CMAKE_SOURCE_DIR} & git rev-list --branches HEAD | find /c /v """ OUTPUT_VARIABLE GIT_VERSION)
Does NOT work for me. CMake gives an error about tokens not separated by whitespace and the version is always zero. I believe find is not so easy to get working. See also [here](http://stackoverflow.com/questions/34905194/cmake-how-to-call-execute-process-with-a-double-quote-in-the-argument-a-k-a-u).

I have thus included the powershell version in my pull request. 
Also I beleive instead of "cd ${CMAKE_SOURCE_DIR}" one should rather set the WORKING_DIRECTORY of execute_process. Again, all works fine without it as long as the build directory is below the source directory. But this is often not the case when using CMake.

I will make a small pull request for this change only.

**Comment by cstamatopoulos** [comment]
Powershell is definitely easier to work with.
I think that from Win7 and onwards it is always installed so it should be OK

**Comment by KjellKod** [comment]
Thanks

**Comment by KjellKod** [comment]
@cstamatopoulos  
Please see and try out @AndreasSchoenle 's pull request which addresses what I believe are the remaining items for Windows: https://github.com/KjellKod/g3log/pull/178

If you find issues please comment on the pull request or here.

**Comment by cstamatopoulos** [comment]
I think everything looks fine !
I quickly build both static and release libraries with no issues.
Will be doing some more testing tomorrow to verify that all is good.

**Comment by KjellKod** [comment]
fixed in pull request: https://github.com/KjellKod/g3log/pull/178
