### ISSUE TITLE
Wrong time under Linux since v1.3

### ISSUE THREAD

**Issue by Jawan81** [KjellKod/g3log#175]
We have updated from v1.2 to v1.3 recently, but now the time in the log messages is completely wrong. On my machine the year is displayed to be 2064, on other machines it's 1928.
We use Ubuntu 64bit and 32bit VMs and an embedded target with a custom 32-bit Linux. The error occurs on all machines.
When I debug and step into the timespec_get function in time.cpp (which was reworked from v1.2 to v1.3) on Ubuntu 64-bit here are example values for the local variables:

os_system: 1492790720620630988
os_high_resolution: 1492790720620631654
os: -666
now_ns: 2985581499719334545
ts->tv_sec: 2985581499
ts->tv_nsec: 719334545

This results in the following time in the log output:
2064/08/10 10:11:39 719334

**Comment by KjellKod** [comment]
Hi Jawan81

I've verified the issue and am working on a solution.

**Comment by KjellKod** [comment]
Just FYI: the https://www.epochconverter.com/ gives that the os_system and os_high_resolution are correct. the negative diff will just have an impact on the fraction of seconds and not the year.

**Comment by KjellKod** [comment]
I consider this a high priority issue and hope to have a resolution merged sometime tomorrow. 
I'm sorry for this. This somehow slipped between the verification cracks.

**Comment by KjellKod** [comment]
FYI: I've a solution for this. As soon as I've a pull request up I'll let you know so you can try it.

**Comment by Jawan81** [comment]
Thanks for working on the fix so quickly.

**Comment by KjellKod** [comment]
Family stuff is slowing me down. I've verified a fix for this and it'll be out in a few days. I just can't say when exactly.

Thanks for raising the issue!

**Comment by KjellKod** [comment]
Corrected in: https://github.com/KjellKod/g3log/pull/177

**Comment by KjellKod** [comment]
@Jawan81 Thanks for reporting this.
