### ISSUE TITLE
Current master does not build (cmake) under Windows.

### ISSUE THREAD

**Issue by dasmysh** [KjellKod/g3log#179]
There is a block in CMakeLists.txt that extracts the git version. This does not work on systems that so not have access to bash. See [this line](https://github.com/KjellKod/g3log/blob/master/CMakeLists.txt#L73).

**Comment by KjellKod** [comment]
Thanks.  Currently there are a couple of issues with building under Windows. 
This is on the high priority list. 

Ref: https://github.com/KjellKod/g3log/issues/174#issuecomment-298110146

**Comment by KjellKod** [comment]
Reported here: 
https://github.com/KjellKod/g3log/issues/174#issuecomment-298110146

**Comment by KjellKod** [comment]
@dasmysh please see the issue referred to above for progress.
