### ISSUE TITLE
Support for g3log on (C++98)

### ISSUE THREAD

**Issue by amitjain04** [KjellKod/g3log#18]
Is it mandatory to have application build on C++11 or we can integrate g3log on C++98 too. Please confirm.

**Comment by KjellKod** [comment]
For C++98 it's better to use g2log. https://bitbucket.org/KjellKod/g2log/src

 Even so there are a few things that might have to be changed in the g2log source code.

One option that I highly recommend is to use the C++11 library by Anthony Williams. It's called justthread and gives the power of the concurrency of C++11 without changing compiler see http://www.stdthread.co.uk for more information

Another option is to stick to C++98 and just carefully replace the C++11 features. It is NOT that hard to do and several companies have already done it.

We can continue this offline and I will try to help you out. You can reach me at Hedstrom@KjellKod.cc. It would be good to know what your system requirements are (OS, compiler).

Cheers
Kjell
