### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by mobileben** [KjellKod/g3log#183]
I've been currently using g3log for my client/server code. It has been working well, and I'm now in the process of wanting to integrate the client code into an iOS project. Are there plans for supporting this?

**Comment by KjellKod** [comment]
Hi @mobileben 

It would be super cool to have it iOS. Unfortunately I have no experience of iOS development.  And not that much on OSX either for that matter (although on OSX you can do "brew install g3log" ;)

For the effort of supporting g3log on iOS I would have to rely on the community.

**Comment by mobileben** [comment]
@KjellKod I'll be working on this tomorrow.

**Comment by KjellKod** [comment]
resolved with PR https://github.com/KjellKod/g3log/pull/198
