### ISSUE TITLE
clang-tidy complaint about INTERNAL_LOG_MESSAGE

### ISSUE THREAD

**Issue by Jawan81** [KjellKod/g3log#192]
A minor issue: We are using clang-tidy to check our code and it always complains about the g3log INTERNAL_LOG_MESSAGE macro (meaning: everywhere we use the logger):

```
some_file.cpp:152:9: warning: do not implicitly decay an array into a pointer; consider using gsl::array_view or an explicit cast instead [cppcoreguidelines-pro-bounds-array-to-pointer-decay]
        LOG(WARNING) << "Some Message";
        ^
/usr/local/include/g3log/g3log.hpp:138:44: note: expanded from macro 'LOG'
#define LOG(level) if(g3::logLevel(level)) INTERNAL_LOG_MESSAGE(level).stream()
                                           ^
/usr/local/include/g3log/g3log.hpp:131:68: note: expanded from macro 'INTERNAL_LOG_MESSAGE'
#define INTERNAL_LOG_MESSAGE(level) LogCapture(__FILE__, __LINE__, __PRETTY_FUNCTION__, level)
                                                                   ^
/usr/local/include/g3log/g3log.hpp:33:31: note: expanded from macro '__PRETTY_FUNCTION__'
#define __PRETTY_FUNCTION__   __FUNCTION__
                              ^
```

`__PRETTY_FUNCTION__` is defined as an array of chars (e.g. in [GCC](https://gcc.gnu.org/onlinedocs/gcc/Function-Names.html)) but LogCapture takes a pointer to char as an argument, which is something different in C/C++. 

A simple static_cast would help:

`#define INTERNAL_LOG_MESSAGE(level) LogCapture(__FILE__, __LINE__, static_cast<const char*>(__PRETTY_FUNCTION__), level)`

**Comment by KjellKod** [comment]
Hi

Could you make this change into a pull request?

**Comment by KjellKod** [comment]
Got it : https://github.com/KjellKod/g3log/pull/193/files

**Comment by KjellKod** [comment]
This looks fine. I have not had time to verify this yet but I will as soon as I get some free hours.

**Comment by KjellKod** [comment]
Interesting that clang complains about this. For all intents and purposes there is no difference _at all_ between `const char*` and `const char []` as explained in. 
 I will merge this but I do consider this a *Clang bug*

https://gcc.gnu.org/onlinedocs/gcc/Function-Names.html

**Comment by KjellKod** [comment]
Merged: https://github.com/KjellKod/g3log/pull/193
