### ISSUE TITLE
undefined reference to g3::log_levels::setHighest(LEVELS)

### ISSUE THREAD

**Issue by jmelion** [KjellKod/g3log#194]
compiled with GCC 5.4.0 with -DUSE_DYNAMIC_LOGGING=ON

Rest of the library works fine so I do not think this is a linking issue. Is there a pre-processor flag which should be defined but isn't around the section where the implementation of `setHighest` is defined?

**Comment by KjellKod** [comment]
How do you trigger this issue and what is the failure?

**Comment by KjellKod** [comment]
I.e. I have a bunch of test that I am running in `https://github.com/KjellKod/g3log/blob/master/test_unit/test_message.cpp` that is using this function.  

How do I trigger this issue?  (_since when I am building with or without the define it works accordingly to the cmake flag_)

**Comment by AndreasSchoenle** [comment]
@jmelion Most probably the library was compiled without -DUSE_DYNAMIC_LOGGING=ON but the program linking to it was compiled with it. You are on the save side if your program includes the generated header, the compiler will then tell you that the function is not available.
