### ISSUE TITLE
I can not build g3log on linux(CentOS 6.5 with gcc 4.8.2)

### ISSUE THREAD

**Issue by 345161974** [KjellKod/g3log#201]
Hi, 
I follow the build steps but I meet an error:

```
[root@localhost build]# make
[  9%] Building CXX object CMakeFiles/g3logger.dir/src/g3log.cpp.o
c++: error: unrecognized command line option ‘-std=c++14’
make[2]: *** [CMakeFiles/g3logger.dir/src/g3log.cpp.o] Error 1
make[1]: *** [CMakeFiles/g3logger.dir/all] Error 2
make: *** [all] Error 2
```
```
[root@localhost build]# g++ --version
g++ (GCC) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

for this error, I must upgrade my GCC? 
Can I build g3log with c++11 ?
My OS:
> CentOS 6.5, GCC 4.8.2

**Comment by 345161974** [comment]
I change the **Build.cmake** file the option **-std=c++14** to **-std=c++1y**，and it worked.

[https://unix.stackexchange.com/questions/265668/g-doesnt-recognize-standard-14-std-c14](url)

```
ELSEIF(${CMAKE_CXX_COMPILER_ID} STREQUAL "GNU")
   message( STATUS "cmake for GCC " )
   IF (APPLE)
       set(CMAKE_CXX_FLAGS   "${CMAKE_CXX_FLAGS} -Wall -Wunused -std=c++1y  -pthread -D_GLIBCXX_USE_NANOSLEEP")
   ELSEIF (MINGW)
       set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -Wall -Wunused -std=c++1y  -pthread -D_GLIBCXX_USE_NANOSLEEP -D_GLIBCXX_USE_SCHED_YIELD")
       set(PLATFORM_LINK_LIBRIES dbghelp)

       # deal with ERROR level conflicts with windows.h
       ADD_DEFINITIONS (-DNOGDI)
   ELSE()
       set(PLATFORM_LINK_LIBRIES rt)
       set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -rdynamic -Wunused -std=c++1y -pthread -lrt -D_GLIBCXX_USE_NANOSLEEP -D_GLIBCXX_USE_SCHED_YIELD")
   ENDIF()
ELSEIF(MSVC)
   set(PLATFORM_LINK_LIBRIES dbghelp)
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /utf-8") # source code already in utf-8, force it for compilers in non-utf8_windows_locale
   # ERROR level conflicts with windows.h
   ADD_DEFINITIONS (-DNOGDI)
   # support AMD proc on vc2015
   if(${CMAKE_CL_64} STREQUAL "0")
       set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /arch:IA32")
   endif()
endif()
```

**Comment by KjellKod** [comment]
I believe you can just change the CMake flags to be c++11 and I think (but am not sure) that will take care of it.

I do recommend upgrading to at least gcc 5.2 as they had several improvements especially in terms of performance that can have a big impact on any software you are compiling

**Comment by 345161974** [comment]
@KjellKod ok, ths. I've already built the g3log.

Ths for your recommend. I will give a try if gcc 5.2 would takes no serious problem to my software in dev.

you can close this issue. Ths!

**Comment by KjellKod** [comment]
Cool. I'll do that.

Just FYI. Gcc 7.1 was recently released and Gcc6 is also out. 

With Gcc7.1 there are promised some big performance improvement as well as giving almost full support for the latest c++ standard release c++17.

If you are considering upgrading compiler then I would suggest gcc7.1

Cheers
Kjell
