### ISSUE TITLE
Not all include directories exported.

### ISSUE THREAD

**Issue by dasmysh** [KjellKod/g3log#202]
Currently the library does not export all include directories. The generated header files are not accessible this way.

Fix:
Replace
`TARGET_INCLUDE_DIRECTORIES(${G3LOG_LIBRARY} PUBLIC ${LOG_SRC})`
by
`TARGET_INCLUDE_DIRECTORIES(${G3LOG_LIBRARY} PUBLIC ${LOG_SRC} "${CMAKE_CURRENT_BINARY_DIR}/include")`
[here](https://github.com/KjellKod/g3log/blob/master/Build.cmake#L138)

**Comment by KjellKod** [comment]
Hi @dasmysh

Please explain in detail. 

The generated header file should be installed at the same location as all other header files.  I.e for Linux/gcc for example this would happen at "make install"

 If this is not the case for you then please describe
1. Your platform (OS, compiler)
2. The exact build *and* install steps for the library
3. How you are linking the program or library with G3log when the error occurs
4. The error message from the compiler

**Comment by dasmysh** [comment]
Sorry for being so brief. I am not installing g3log but using it as s submodule that is included in another cmake project using `add_subdirectory(...)`. This way I can make my C++ projects self contained (which is nice because I can just pull the repo at a new PC and everything will build without any work on the libraries used).

In this case the original g3log headers are used from the original source location This happens automatically due to the `PUBLIC` keyword in `TARGET_INCLUDE_DIRECTORIES` (cmake will just include all public include directories of all libraries added by `target_link_libraries`). The generated headers are put in another directory (`${CMAKE_CURRENT_BINARY_DIR}/include`) that will not be included this way as it is not in the public 'search path'.
Changing the line as described above will put all directories in the public search path and everything is fine.

I am using
1. Win10 Visual C++ v14.1 (Visual Studio 2017)
2. As explained above, I do not install I use `add_subdirectory` in my main project. Everything else is handled by cmake.
3. Nothing special, i use `TARGET_INCLUDE_DIRECTORIES([...] g3logger)`. Everything else is handled by cmake.
4. It does not find the generated header when compiling my project. g3log will compile just fine (for the reason you mentioned).

**Comment by dasmysh** [comment]
I just realized that this might break the build for the installed library case. Maybe you can just set a variable (i.e. G3LOG_INCLUDES) to the paths that are needed in the `add_subdirectory` case. That way I need to add the include directories by hand but I can use the variable and no hard paths (which is not really possible for a general binary directory and multiple platforms).

**Comment by KjellKod** [comment]
Thanks

I think that's what I need for replicating the issue. 
I'll mark this as an improvement 

To expediate the change you can
- create a pull request with these changes
- create a hello world VS2017 example that would break unless this change is in. This is only to verify your case as well as the installed library case and would save me time.

**Comment by KjellKod** [comment]
I do not see an action point for me at this point. The author of the issue has not provided the means for a way forward.
