### ISSUE TITLE
Add in support for configurable kMaxMessageSize value

### ISSUE THREAD

**Issue by mobileben** [KjellKod/g3log#203]
Currently in ```logcapture.cpp``` there is a setting for how much space is available for the buffer available for ```vsnprintf```. 

When exceeded, a ```[...truncated...]``` message is displayed along with the output, which is of course truncated. 

I totally understand the need for constraints and while 2KB works in most cases, for me it's too small. I'm using it to capture server responses so I can use them in test cases without the server. The responses are larger than the limit. 

I'm more than happy to take this as I'm about to pull the latest into my fork and address this since I need it right now. 

The plan would be to add a static method to ```LogCapture``` to set a default value. If there is a worry on any contention of set/get, it could of course be made an ```atomic```. But I have no plans to do that right now.

**Comment by KjellKod** [comment]
I think having the option of changing the value makes sense 

Why not use a CMake option? (Ref the options file)
I would keep it something like this
1. If the option isn't set then keep the size as is
2. If the option is set, make the limit a high value either set by the option or just set to a predefined high value that is sufficient 

With 1 and 2 there is compilation fixation of the value and much easier than adjusting it through a code API

**Comment by KjellKod** [comment]
Thanks @mobileben 

Looking forward to the pull request

**Comment by mobileben** [comment]
The only thing about a compilation version is it makes it a bit more brittle when iterating. Essentially for my MacOS stuff, I build the Release and then ```make install```.  For my iOS stuff, I treat it as a pre-built as well and install it in a pre-built directory I have just for iOS (Release as well). I want to build it once and then "forget about it".

It is more of a PITA to have to rebuild or hold multiple variants of a library, so at least in my case, a code API is more attractive. Especially since the way I use ```g3log``` right now is it is wrapped in a class which takes a configuration file at start to configure it. So I can rapidly modify what it does without any re-building.

Oh, on the side. I did find that wrapping ```g3log``` logging in a class to call ```LogCapture::capturef```.  didn't work out too well. It's probably user error on my behalf. What I wanted to do was "hide" the underlying logger. This includes no header files from ```g3log``` being exposed to the app.

What I found was the it appears that even with using ```va_copy```, the formatting through ```vsnprintf``` doesn't work right. Essentially I had a method that would call ```LogCapture::capturef```. The method was variadic (non-template, so using the C va_args) which is why I was using ```va_copy```.  I thought that I was supposed to be able to call another variadic that uses ```vsprintf``` variants as long as I used ```va_copy``` but it's not looking like this is the case.

I do have the code done already. Just using it a bit more and will commit this weekend.

**Comment by KjellKod** [comment]
I understand your rationale. 
For the pull request. Please wrap the API call in the namespace `g3:: only_change_at_initialization`

**Comment by mobileben** [comment]
Ahh, okay. I was doing it within ```LogCapture```. But I can make a specific API call to do this. For example, right now I'm using:

```
void LogCapture::setMaxMessageSize(size_t max_size) {
   MaxMessageSize = static_cast<int>(max_size);
}
```

but it will be better served to do this: 

```
namespace g3 {
    namespace only_change_at_initialization {
      void setMaxMessageSize(size_t max_size);
    }
}
```
Is using that function name (```setMaxMessageSize```) okay with you? And do you have a particular file you want that implemented in? It may be best to be done with ```logcapture.cpp```, unless you want me put it in a specific file to just declare the ```extern``` for ```MaxMessageSize```  within ```logcapture.cpp```. But it may be nicer to keep it static and constrained to ```logcapture.cpp``` so it can't be tampered with.

Also please note that I dropped off the ```k``` with ```MaxMessageSize``` as it is no longer constant. I don't know if you have any naming convention related to globals.

All super simple to do, just let me know what works best to keep things clean.

**Comment by KjellKod** [comment]
sounds good. Go for it.

**Comment by KjellKod** [comment]
resolved and merged.
