### ISSUE TITLE
Format warnings for clang++ builds

### ISSUE THREAD

**Issue by mobileben** [KjellKod/g3log#204]
When building with clang++ get several warnings like the following:

> main_sigsegv.cpp:36:158: warning: more '%' conversions than data arguments [-Wformat]
>   ..."ILLEGAL PRINTF_SYNTAX EXAMPLE. WILL GENERATE compiler warning.\n\nbadly formatted message:[Printf-type %s is the number 1 for many %s]", logging.c_str());
> 

In this case it happens to be for a MacOS build.

**Comment by KjellKod** [comment]
Hi, this is intentional. Please look at what is compiling. It is an example which uses illegal formatting which could trigger segfaults. 

You can turn off building the examples using the CMake options

**Comment by mobileben** [comment]
This is my bad, sorry I should have looked at this more closely. 

Optionally, perhaps using a ```#warning``` in conjunction would make it a little easier for people to know these warnings are okay? 

Then again ... I'm the only one that has mentioned it thus far ...

**Comment by KjellKod** [comment]
Unfortunately there is no standard `#warning` macro that is recognized across platforms
