### ISSUE TITLE
Can we keep the library C++11 only?

### ISSUE THREAD

**Issue by ruipacheco** [KjellKod/g3log#207]
This is a very good library and compiles cleanly with gcc 4.8.5, the lowest version of gcc that supports C++11. Can we replace all usage of C++14 with C++11?

I'm happy to provide a PR if you agree.

**Comment by KjellKod** [comment]
Please add the PR and I'll take a look.

FYI:

One think I want to do in 2017 is moving towards less queuing complexity
and separate input channels to sinks vs log messages. I believe this would
have a radical performance increase without showing some of the bad aspects
of the lock-free loggers that I've so far seen on the market.  This work
all depends on how crazy my work situation is of course. G3log is done
off-business hours and with zero pay so obviously my day (sometimes night)
work takes precedence. If the queueing change takes place it'll likely be
using c++17.

Of course one option would be to let g3log be as is and instead spin up
g4log ;)
That's the path I took with g2log -> g3log

Cheers
Kjell


* Contact Information
* Kjell Hedström
* Mobile:  +1 - 617.378.1915 <(617)%20378-1915>
* E-mail: Hedstrom@KjellKod.cc

**Comment by ruipacheco** [comment]
I stand by g4log :)

It's too early to support C++17.
