### ISSUE TITLE
Add in variant of capturef that uses va_list 

### ISSUE THREAD

**Issue by mobileben** [KjellKod/g3log#209]
I'd ideally like to wrap g3log with my custom logger class. I'm currently doing this, but I'm forced to cobble it together in a couple of ways. First, I'm using macros to invoke my logger. Additionally, I've copied the implementation of ```LogCapture::capturef``` in my class. 

In many ways, this mirrors what g3log is already doing, but this way, it hides g3log as the underlying implementation for logging.

The reason for this request is that if I wrap ```LogCapture::capturef``` in another function that is variadic, ```capturef ``` will not behave properly. 

An example I made of wrapping is here:

```
static void wrapper_log(const char *file, const int32_t line, const char *function, Logger::Level level, const char *message, ...) {
    va_list args;
    va_start(args, message);
    va_list argsCopy;
    va_copy(argsCopy, args);
    Logger::log(file, line, function, level, message, argsCopy);
    va_end(argsCopy);
    va_end(args);
}

wrapper_log(__FILE__, __LINE__, __PRETTY_FUNCTION__, Logger::Level::Debug, "message with %d and %s", 10, "another string");

```
The output of this becomes:

> DEBUG [JKSLobby.mm->-[JKSLobby initWithViewController:gameSpace:delegate:]:111]	message with 236138912 and (null)

Where ```Logger::log``` is this class function which is more or less same code as ```capturef``` (the difference is that the first line is constructing ```LogCapture``` like this: ```LogCapture capture(file, line, function, toG3Level(level));```

The signature for ```log``` is this.

        static void log(const char *file, const int32_t line, const char *function, Level level, const char *message, ...) __attribute__((format(printf, 5, 6)));

If I also implement another function, but this one uses ```va_list```, the results are as expected.

        static void log(const char *file, const int32_t line, const char *function, Level level, const char *message, va_list args);

> DEBUG [JKSLobby.mm->-[JKSLobby initWithViewController:gameSpace:delegate:]:108]	message with 10 and another string

I realize also that using templates would be better overall, but I want g3log hidden, and by using templates, AFAIK, I have to include implementation in the header files.

**Comment by KjellKod** [comment]
I won't add his but am open for pull requests
