### ISSUE TITLE
How to use logger in free function?

### ISSUE THREAD

**Issue by ruipacheco** [KjellKod/g3log#211]
I'm currently declaring a logger in a class and that class occasionally calls free functions. Is there a way to call the existing logger from that function so it'll write to the same file?

**Comment by KjellKod** [comment]
If the logger is initialized then a global pointer to the logworker is available (ref:g3log.cpp/hpp) or are you talking about your logging sink?

**Comment by ruipacheco** [comment]
I initialized the log following what's on the website then called `LOG(INFO) << "...";` from a free function but I always got a message in the console saying that the logger was not initialized.

The free function was in a different set of files from where I initialized the logger.

**Comment by KjellKod** [comment]
Hmm. It's something missing from this.

Are you in the same library? (Which should still work)

What OS? 

Can you duplicate it in a "hello world" example program that you can share?

**Comment by ruipacheco** [comment]
Right, my bad. This was buried deep in my code.
