### ISSUE TITLE
Change std2 namespace for C++17

### ISSUE THREAD

**Issue by AnthonyCalandra** [KjellKod/g3log#212]
`stdN` where `N` is a sequence of digits will soon become reserved as of C++17 (assuming the current draft is accepted by the ISO). g3log currently defines a `std2` namespace which is considered undefined behaviour in C++17.

Source: http://eel.is/c++draft/constraints#namespace.future

**Comment by KjellKod** [comment]
Thanks. I knew of that one. Let's see when/if the proposal get accepted

**Comment by brycelelbach** [comment]
BTW, it's not a proposal; it's in the standard, which we just sent out for publication.

**Comment by KjellKod** [comment]
Nice.

I'll make sure to take care of it.

* Contact Information
* Kjell Hedström
* Mobile:  +1 - 617.378.1915
* E-mail: Hedstrom@KjellKod.cc

**Comment by KjellKod** [comment]
Currently g3log is running with c++11 options only. 
I'll see if I can make some nice wrapping to not deal with users that do not have the option of using c++14/17 and are internally using the `g3log/std2::make_unique`

**Comment by KjellKod** [comment]
@brycelelbach  nice seeing you here.    I talked to you a little at the `CppNow2017` :)

**Comment by KjellKod** [comment]
Removed bug label since g3log is currently not setup for c++17. 
This IS however a high priority fix and should be easy to address, albeit might break things for coders out there if they took advantage of the g3log fix for previously not implemented std functionality.

**Comment by KjellKod** [comment]
Resolved in https://github.com/KjellKod/g3log/pull/246
