### ISSUE TITLE
found = str.find_last_of("(/\\");  why searching for '(' as well?

### ISSUE THREAD

**Issue by maj-tom** [KjellKod/g3log#219]
In std::string splitFileName (logmessage.cpp) there's the line found = str.find_last_of("(/\\");
Why '\' and '/' make sense, why is it also checking '(', is that a typo?

**Comment by KjellKod** [comment]
Good question. I don't remember. It could be.

**Comment by KjellKod** [comment]
No action yet. unless PR.
