### ISSUE TITLE
g3log/generated_definitions.hpp not found

### ISSUE THREAD

**Issue by oliverdain** [KjellKod/g3log#223]
I have a project that is compiling g3log and using it via cmake. When I build for native mac everything works fine. For example, if I run `make VERBOSE=1` so I can see the build commands cmake generated I see something like:

```
cd /Users/oliverdain/Documents/code/revl/cpp/build/utils/sensor_data && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DBOOST_ALL_NO_LIB=1 -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_THREAD_PROVIDES_EXECUTORS -DBOOST_THREAD_USES_CHRONO -DBOOST_THREAD_VERSION=4 -I/Users/oliverdain/Documents/code/revl/cpp/utils/sensor_data/. -isystem /Users/oliverdain/Documents/code/revl/cpp/third_party/boost_cmake/boost/boost_1_63_0 -I/Users/oliverdain/Documents/code/revl/cpp/third_party/g3log/src  -g   -std=gnu++14 -o CMakeFiles/utils_sensor_data.dir/src/sensor_data_utils.cpp.o -c /Users/oliverdain/Documents/code/revl/cpp/utils/sensor_data/src/sensor_data_utils.cpp
```

Note that `g3log/src` but that no other g3log directories have been added to the include path. When I try to cross-compile things for arm (iOS) I get errors like:

```
In file included from /Users/oliverdain/Documents/code/revl/cpp/utils/sensor_data/src/sensor_data_utils.cpp:25:
In file included from /Users/oliverdain/Documents/code/revl/cpp/third_party/g3log/src/g3log/g3log.hpp:24:
/Users/oliverdain/Documents/code/revl/cpp/third_party/g3log/src/g3log/loglevels.hpp:10:10: fatal error: 'g3log/generated_definitions.hpp' file not found
#include "g3log/generated_definitions.hpp"
         ^
1 error generated.
```

That makes sense since the generated file has not been added to the include path. I can verify that the generated_definitions file was in fact generated:

```
$ pwd
/Users/oliverdain/Documents/code/revl/cpp/build-ios
$ ls -lh third_party/g3log/include/g3log/
total 8
-rw-r--r--  1 oliverdain  staff   612B Aug 28 17:30 generated_definitions.hpp
```

so I think I understand why things don't work when cross-compiling but I don't actually understand why things **do** work when not cross compiling. In a regular compile I still include g3log/g3log.hpp and that includes (unconditionally) loglevels.hpp which, again unconditionally, includes generated_definitions.hpp.

Any ideas why:

1. This actually does work in non-cross-compiling mode
2. How to get it to work when cross compiling?

**Comment by KjellKod** [comment]
When setting up and compiling G3log through CMake it'll put the generated file in the temporary CMake generated files and within the the include  path in the CMake build directory.

Maybe a better way is to build and install G3log as a library and then you link to it instead of merging it with your projects build structure?

**Comment by oliverdain** [comment]
Thanks for getting back to me so fast!

> CMake it'll put the generated file in the temporary CMake generated files and within the the include path in the CMake build directory

The issue is that I'm not seeing the latter. That is, projects with say that have a link dependency are g3log **are** seeing the g3log **source** directory added to the their include path but they are **not** seeing the generated build dir added. I suspect all you need to do is add a `target_include_directories` line somewhere.

> Maybe a better way is to build and install G3log as a library 

We're building for many different architectures and OSs (mac, linux, iOS on arm, iOS on 64-bit arm, Android, etc.) so I think that ends up being painful (at least I don't know of a non-painful way to do it).

**Comment by KjellKod** [comment]
Especially if you are building for multiple architectures I think it makes sense to link to it. That way it's just another library and path setup which I'm sure you already are dealing with for other 3rd party libraries. 

That said. G3log is public domain so feel free to fork it and do whatever changes you need. Since it is public domain you don't have to publish your custom changes (although it is nice if you do)

**Comment by KjellKod** [comment]
I am not seeing an action on my part for this.
