### ISSUE TITLE
Problematic implementation of LOG\LOGF macros

### ISSUE THREAD

**Issue by omerah** [KjellKod/g3log#224]
Hi,
There's a basic pitfall in the way LOG\LOGF macros were implemented:
`#define LOG(level) if(g3::logLevel(level)) INTERNAL_LOG_MESSAGE(level).stream()`
If we take the following code:
`if (x)
    LOG(INFO) << "This message";
else
    LOG(INFO) << "That message";`

After the preprocessing stage we get:
`if (x)
    if(g3::logLevel(level)) INTERNAL_LOG_MESSAGE(level).stream() << "This message";
else
    if(g3::logLevel(level)) INTERNAL_LOG_MESSAGE(level).stream() << "That message";   `

As you can see, the compiler has no way to know that the 'else' statement belongs to the first if statement and not the the second one (that comes from the definition of the LOG macro).

The correct way to write this macro would be:
`#define LOG(level) if(!g3::logLevel(level)){\
                                } else INTERNAL_LOG_MESSAGE(level).stream()`
Which will, after preprocessing, turn into:
`if (x)
    if(!g3::logLevel(level)){
    } else INTERNAL_LOG_MESSAGE(level).stream() << "This message";
else
    if(!g3::logLevel(level)){
    } else INTERNAL_LOG_MESSAGE(level).stream() << "That message";`

Which keeps the original logic we're interested in.

**Comment by KjellKod** [comment]
Looks good. Please put up a pull request

**Comment by KjellKod** [comment]
@omerah : have you considered opening up a pull request for this change?

**Comment by maj-tom** [comment]
The dangling else strikes again :)
I'll try to find time this weekend to do this as well as fix the test fails in the PR I sent before (started a new job so I've been overwhelmed).

**Comment by KjellKod** [comment]
Candidate for closing unless a PR shows up.  @omerah?

**Comment by omerah** [comment]
Hi,

Sorry, I am pretty busy, don’t have time to fix it at the moment :(

Thanks,

Omer.

**Comment by KjellKod** [comment]
@maj-tom 

Many thanks!
