### ISSUE TITLE
Buffer overrun in getSymbolInformation (stacktrace_windows.cpp)

### ISSUE THREAD

**Issue by lukeocamden** [KjellKod/g3log#225]
Hello, I think the following fragment is incorrect if MAX_SYM_NAME > 256

```
      char symbol_buffer[sizeof(SYMBOL_INFO) + 256];
      SYMBOL_INFO *symbol = reinterpret_cast<SYMBOL_INFO *>(symbol_buffer);
      symbol->SizeOfStruct = sizeof(SYMBOL_INFO);
      symbol->MaxNameLen = MAX_SYM_NAME;
```

I think that should read:

```
      char symbol_buffer[sizeof(SYMBOL_INFO) + MAX_SYM_NAME];
```

Or possibly instead do this:

```
      symbol->MaxNameLen = sizeof(symbol_buffer) - sizeof(SYMBOL_INFO);
```

What do you think?

Thanks!

**Comment by KjellKod** [comment]
As far as I can see this is not an issue.

**Comment by lukeocamden** [comment]
Sorry I missed some context: the key is the following line (which occurs a bit later in the function):

```
 if (SymFromAddr(GetCurrentProcess(), addr, &displacement64, symbol)) {
```

Which can write symbol->SizeOfStruct + symbol->MaxNameLen bytes into symbol_buffer, which writes of the end if the symbol is longer than 256 bytes (but still shorter than MAX_NAME LEN). Does that make more sense?

**Comment by KjellKod** [comment]
Maybe. Not sure.

Please put up a PR and I will review it
Thanks
