### ISSUE TITLE
In GCC the symbol __PRETTY_FUNCTION__ gets hidden

### ISSUE THREAD

**Issue by MartinNvp** [KjellKod/g3log#230]
In GCC the symbol `__PRETTY_FUNCTION__` is valid (in a function) but not a macro.
See: 
https://gcc.gnu.org/onlinedocs/gcc/Function-Names.html
https://stackoverflow.com/a/33806001/243879

So the macro def at the top of g3log.hpp
probably does not do what is intended, and just hides the `__PRETTY_FUNCTION__` symbol.

**Comment by KjellKod** [comment]
Interesting. It seems to work though. 

Have you seen it not working? If so, what version of gcc are you using?

**Comment by KjellKod** [comment]
Since it is working and no issue shown I'll mark this as "invalid" . I do appreciate the feedback and if you can show an actual issue then I'm happy to reopen and address this. 

Thanks

**Comment by zhengyidong** [comment]
Actually I met a crash by this, some gcc template thing uses this variable and lead to some error.
