### ISSUE TITLE
Remove reference to ERROR level in comments/documentation

### ISSUE THREAD

**Issue by ebertland** [KjellKod/g3log#232]
The documentation says that the default logging levels are DEBUG, INFO, WARNING, ERROR, and FATAL. Using LOG(ERROR) produces a compile error.

```
error: ‘ERROR’ was not declared in this scope
                                 LOG(ERROR) << "Wrote storage[" << (addr / mem_size) << "][0x"
                                     ^
/cb/home/jeff/ws/tools/g3log-1.3/include/g3log/g3log.hpp:138:36: note: in definition of macro ‘LOG’
 #define LOG(level) if(g3::logLevel(level)) INTERNAL_LOG_MESSAGE(level).stream()
                                    ^~~~~
```

I looked through the source and I cannot find an ERROR log level.

**Comment by ebertland** [comment]
I see that most documentation does not list ERROR in the default logging levels. This comment indicates ERROR is one of the default levels.
```
      /// reset all default logging levels to enabled
      /// remove any added logging levels so that the only ones left are
      ///  {DEBUG,INFO,WARNING,ERROR,FATAL}
void reset();
```
So why not include ERROR by default?

**Comment by KjellKod** [comment]
ERROR is not a supported log level. This is a documentation bug. Please address it with a pull request 

If you need that level please add your own custom level - this is documented extensively in the doc and the unit tests.


Thanks

**Comment by ebertland** [comment]
Sure, no problem.

**Comment by kishorenc** [comment]
@KjellKod I'm curious to know the reason for dropping `ERROR`. Seems like a standard logging level but I am sure you must have had a good reason.

**Comment by KjellKod** [comment]
I'm not dropping it. It was never there. 

g3log is made so that you can add custom levels easily. Please check the documentation and the test code.

**Comment by ebertland** [comment]
Here is what I am using:

/* Custom logging levels for use with g3log */
const LEVELS ERROR     {WARNING.value + 10, {"ERROR"}};
const LEVELS FULL_INFO {INFO.value - 10,    {"FULL_INFO"}};
