### ISSUE TITLE
shutDownLogging() is not in g3 namespace

### ISSUE THREAD

**Issue by ebertland** [KjellKod/g3log#233]
g3::shutDownLogging does not work, but g3::internal::shutDownLogging does work.

The example code shows this function in the g3 namespace.
```
   // If the LogWorker is initialized then at scope exit the g3::shutDownLogging() will be called. 
   // This is important since it protects from LOG calls from static or other entities that will go out of
   // scope at a later time. 
   //
   // It can also be called manually:
   g3::shutDownLogging();
```

(The reason that I am calling shutDownLogging explicitly is that I am writing a C++ library that may be called through a C API. In this case, I cannot use RAII for the logworker, since that would force main() to be written in C++. So I provide separate functions, callable from C, that initialize and shutdown logging. If there is an alternative, let me know.)

**Comment by KjellKod** [comment]
Are you in the windows world? If so a common concept is to use the "start" and "stop" hooks. Please see previous history of issues where this is discussed extensively

**Comment by ebertland** [comment]
I am in Linux.

I don't mind the start and stop hooks, and that is what I am using. The only issue here is whether it should be in the g3 namespace vs g3::internal.

**Comment by KjellKod** [comment]
Not to be nitpicking here but 
1. Shutdownlogging does stop the logging as it will set the logging ptr to null
2. G3log should be stopped with RAII or with stop hooks that utilizes similar effects. For information about the API please see 

https://github.com/KjellKod/g3log/blob/master/src/g3log.cpp
https://github.com/KjellKod/g3log/blob/master/src/logworker.cpp

If you see issues with the documentation or the API docs please add a pull request
