### ISSUE TITLE
Add bare bones setup example?

### ISSUE THREAD

**Issue by ruipacheco** [KjellKod/g3log#236]
Maybe I'm missing it but the repo does not contain any examples on how to do a barebones setup of g3log: the bare minimum include and code necessary to make the logger work.

It includes a lot of everything else, which is good, but scanning the code always leaves me wondering what is the minimum necessary to make things work and what is the meant to be exceptional.

**Comment by KjellKod** [comment]
Not sure what you are after. Both the readme and the API doc contains barebone examples

If you have something different in mind, please add a PR

Thanks

**Comment by ruipacheco** [comment]
Aye.
