### ISSUE TITLE
How to add source?

### ISSUE THREAD

**Issue by ruipacheco** [KjellKod/g3log#238]
I'm developing a library and I'd like to add the source to my project as I can't link a library to another library. I've managed to automate the download and build of g3log using CMake but when I noticed something strange when using it:

In logworker.hpp I've noticed it's trying to `#include "g3log/filesink.hpp"`. How is this supposed to be resolved? How can I setup my project so this is resolved correctly?

**Comment by KjellKod** [comment]
All header files are included through a directory level (G3log). This is a common practice that makes it easy to avoid filename collisions between libraries .

I.e instead of adding straight the .hpp files you add the the .hpp directory - named g3log

**Comment by KjellKod** [comment]
You can see in G3log how the include directives are setup in the CMake files

**Comment by KjellKod** [comment]
@ruipacheco is this resolved?

**Comment by KjellKod** [comment]
closing for now, feel free to reach out if you need help on this again.
