### ISSUE TITLE
OSX 10.12.5 Sierra - no member named 'raise' in the global namespace

### ISSUE THREAD

**Issue by skiz** [KjellKod/g3log#242]
I have attempted to install via homebrew, having the source in my project, and manually building & installing, and I keep getting the same error.  The only usage so far is just adding the headers:
```
#include <g3log/g3log.hpp>
#include <g3log/logworker.hpp>
```

I am consistently getting the error:
```
In file included from extern/g3log/src/g3log/g3log.hpp:25:
In file included from extern/g3log/src/g3log/logcapture.hpp:17:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/csignal:54:9: error: 
      no member named 'raise' in the global namespace
using ::raise;
      ~~^
```

My compiler command:
```
g++ -std=c++11 -g -Wall -Wextra  -Iinclude -D_THREAD_SAFE -I/usr/local/include -Iextern/g3log/src -c -o build/accounting.o src/accounting.cpp
```
g++ --version
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by KjellKod** [comment]
something in your setup is not correct. 
Ref: 
http://www.csl.mtu.edu/cs4411.ck/www/NOTES/signal/raise.html

if `csignal` is not available then please go through the necessary steps to install the missing c-libraries.   I.e. the issue is not an issue with g3log, it's with the setup of c-libraries that should exist in the runtime but either aren't there or cannot be found due to path issues.

**Comment by KjellKod** [comment]
I'd suggest that you make a simple "hello world" example that uses some c-api calls such as in the example in the link that I called out. If that works then you should be able to use the signal parts of g3log
