### ISSUE TITLE
build dependency with -std=c++14 

### ISSUE THREAD

**Issue by sw-yoonsung** [KjellKod/g3log#250]
I use gcc version 4.8.5 because of my company requirement.

When I build using cmake and make, compiler throw this message.

```
c++: error: unrecognized command line option ‘-std=c++14’
CMakeFiles/g3logger.dir/build.make:62: recipe for target 'CMakeFiles/g3logger.dir/src/logworker.cpp.o' failed
make[2]: *** [CMakeFiles/g3logger.dir/src/logworker.cpp.o] Error 1
CMakeFiles/Makefile2:173: recipe for target 'CMakeFiles/g3logger.dir/all' failed
make[1]: *** [CMakeFiles/g3logger.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

I knew the function 'std::make_unique<>()' is in c++14. So, I replace it to my make_unique code, not std.  But It still throw same message. 

I tried this log because only c++11 and no other dependency. Is it only c++11 right?

How can I solve this problem?

**Comment by KjellKod** [comment]
Hi

With your compiler version the c++14 option should be `-std=c++1y`

If that doesn’t work then a few pull requests ago I replaced the home made  `std2::make_unique` for `std::make_unique`

You can go back to the version before that pull request (see pull request history) and that should help you

I will tag that version later so it’s more obvious

**Comment by KjellKod** [comment]
Leaving it as opened until I’ve tagged the pre `std::make_unique`

**Comment by KjellKod** [comment]
The software is tagged for the last commit with c++11 support
https://github.com/KjellKod/g3log/releases/tag/1.3.1
