### ISSUE TITLE
Logging to same file/sink from multiple processes using g3log

### ISSUE THREAD

**Issue by jambamamba** [KjellKod/g3log#252]
If I have two processes, a.exe and b.exe, each links with g3logger.so and both a and b have the same sink /tmp/log.txt, will the two processes clobber each others log entries?

I know the logger is thread safe within one process, but how does it handle multiple processes using same sink? 

Thanks for making this logger, really appreciate your work.

**Comment by KjellKod** [comment]
Hi

Currently this is not a design feature of the Logger. My suggestion is to use the API to name the log files differently.

Cheers
Kjell
