### ISSUE TITLE
restoreSignalHandler should restore the original sa_handler

### ISSUE THREAD

**Issue by ebertland** [KjellKod/g3log#253]
restoreSignalHandler sets sa_handler to SIG_DFL. That's fine for an application that does not register a signal handler, but it if does, then it will be clobbered.

installSignalHandler should store oldact from sigaction (rather than passing nullptr to this argument), and then store that in a map<int, struct sigaction>. Then, restoreSignalHandler gets the old action from the map and passes it to sigaction.

As far as I can tell, there is no way to prevent g3log from clobbering an application or another library's signal handler except to define DISABLE_FATAL_SIGNALHANDLING.

**Comment by KjellKod** [comment]
Good point. 

Please put up a pull request from memory I recognize that it might not be as clear cut. I could remember wrong...

A possible alternative pull request tray would be easy to implement would be to create a “gSignals” modifying function. That way you could remove or add signals to your specific need. Ref: https://github.com/KjellKod/g3log/blob/master/src/crashhandler_unix.cpp

As it is it’s an “all or nothing choice”. Choose g3log’s signal handling or disable it and use your own.

**Comment by ebertland** [comment]
I decided to save and restore the original sigactions. By calling `g3::overrideSetupSignals({});`, I can disable all signal handlers and they are restored to the original ones.

This is working for me, both when I build my stand-alone application, which uses g3log's signal handler, and when I build it as a library and link it to another application that has it's own signal handler and stack trace reporting.

**Comment by KjellKod** [comment]
Addressed in https://github.com/KjellKod/g3log/pull/254
