### ISSUE TITLE
Minimum flags for Linux ?

### ISSUE THREAD

**Issue by andreacampanella** [KjellKod/g3log#258]
I'm trying g3log in my project, will run on a minimal linux embedded system (arm) , the idea is to statically compile it with the main application written in C++ , I'm trying to figure out which are all the flags I need to port from cmake to out make for Linux , I figured out I need : 

-Wall -rdynamic -Wunused -std=c++14 -pthread -lrt -D_GLIBCXX_USE_NANOSLEEP -D_GLIBCXX_USE_SCHED_YIELD 

Is that it?

**Comment by KjellKod** [comment]
Any feedback here? Otherwise I’ll go ahead and close it

**Comment by KjellKod** [comment]
Closing due to lack of response
