### ISSUE TITLE
Silence Warnings in CMake

### ISSUE THREAD

**Issue by codekrafter** [KjellKod/g3log#264]
I am trying to use g3log in my project, and I have it as a git submodule in my project. I use `add_subdirectory()` in cmake to add g3log to my project. It emitts lots of information about building it and I was wondering if I could silence those messages.

Thanks!

**Comment by KjellKod** [comment]
Some warnings are emitted as examples of compiler warnings when building “examples” you can turn these off. Check the Options.cmake

Other CMake messages are there to inform the user how the build is going. If you don’t like those messages then feel free to fork G3log and suppress or remove them in your forked version of G3log

**Comment by KjellKod** [comment]
You could also adress it by wrapping the message function similar to what is suggested here: 

https://stackoverflow.com/questions/38983007/remove-messages-from-an-included-cmakelist-txt

If you go down that route I’m happy to review your changes if you do a pull request later

**Comment by codekrafter** [comment]
Thanks! I ended up using those suggestions in my project. It is now silent!
