### ISSUE TITLE
unknown type thread_local using VS 2013

### ISSUE THREAD

**Issue by outkontroll** [KjellKod/g3log#270]
Similar to issue #87 there is an error during the (VS2013) compilation of the crashhandler_windows.cpp, thread_local is an unknown type. Including g3log/g3log.hpp fixes the error.

**Comment by KjellKod** [comment]
Please open up a pull request

**Comment by outkontroll** [comment]
Sorry for my late answer. I will create the pull req as soon as I have some time to do it, hopefully in this week.

**Comment by KjellKod** [comment]
pending to be closed

**Comment by KjellKod** [comment]
resolved in https://github.com/KjellKod/g3log/pull/273#pullrequestreview-131003348
