### ISSUE TITLE
issues on Win x64

### ISSUE THREAD

**Issue by AndreyMaksimov** [KjellKod/g3log#274]
Hi! 

Some issues on Win x64? VS2015:

![image](https://user-images.githubusercontent.com/22891940/41880405-9862f7c8-78e6-11e8-9555-816fc71b03a2.png)

**Comment by KjellKod** [comment]
Not sure what’s going on. It is used frequently on the windows side. To me it looks like the environment is not setup correctly so that it doesn’t support auto keyword or cannot find the symbols to see what it is. 

I.e I see nothing that indicates that this is a G3log issue

**Comment by AndreyMaksimov** [comment]
Thanks for the answer. x86 configuration runs with no problem. The issue is with x64 configuration

**Comment by KjellKod** [comment]
@AndreyMaksimov does `-A x64` help?

**Comment by AndreyMaksimov** [comment]
Yes, it helps. However there is some run-time error with Release/Dll configuration.. No problem with Debug. Anyway I switched to static (that is good for me). Now both configurations work.

So.. my final build script looks as following (VS2017):
`cmake -DG3_SHARED_LIB=OFF -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15" . -A x64
msbuild g3log.sln /p:Configuration=Release
msbuild g3log.sln /p:Configuration=Debug`

Thanks

**Comment by KjellKod** [comment]
Closed. Readme updated
