### ISSUE TITLE
Update windows build in Readme

### ISSUE THREAD

**Issue by AlexP11223** [KjellKod/g3log#275]
What's the point of `..` path in `cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 12" ..`? Why not just run it from the root dir? (that is `cd` VS cmd to it)

Probably should be just `cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 12"`

Also maybe should add note how to build x64 (`cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 12" -A x64`)

**Comment by KjellKod** [comment]
You normally want to avoid building in root directory when using CMake as lots of temporary files are being created. By using a build directory all those temporary files will stay there and can be deleted by just clearing that directory. 

Hmm. Not sure I’ve run into any issues with 64 bit before. Never had to specify that option

**Comment by KjellKod** [comment]
It’s an interesting situation when you run for both 32 but and 64 bit on the same system. 
This is more a CMake usage issue than G3log but maybe the README can be improved. 
The build environment has to be properly described - this is especially the issue in windows

The AppVeyor CI is currently running with G3log in a 64 bit system
```
cmake -G "Visual Studio 14 2015 Win64” (line is cut)
```
Example: https://ci.appveyor.com/project/KjellKod/g3log/build/1.0.153

**Comment by AlexP11223** [comment]
Ah, actually I misunderstood how `..` is supposed to work in cmake, I thought it was the output path. :)

I tried x64 (because it doesn't seem to work in x64 apps otherwise), worked fine with just `-A x64`.

The only issue was when I tried to build static lib (`/MT`, `/MTd`). 

With `cmake -DG3_SHARED_LIB=OFF` it was still using `/MD`, `/MDd`, so I had to edit `Build.cmake`:

```
IF (MSVC)
   set(CMAKE_CXX_FLAGS_RELEASE "/MT")
   set(CMAKE_CXX_FLAGS_DEBUG "/MTd")
ENDIF()
```

**Comment by KjellKod** [comment]
Got it. 

Please put up a pull request with the proposed changes. Please keep in mind that it. Weds to work both on 32 bit and 64 bit architecture 

Thanks
Kjell

**Comment by KjellKod** [comment]
Clarified in readme generic recommendations for Windows

**Comment by KjellKod** [comment]
Ref: https://github.com/KjellKod/g3log/pull/276
