### ISSUE TITLE
Callstack on Windows (MinGW)

### ISSUE THREAD

**Issue by coderalpha** [KjellKod/g3log#280]
Hi

We ran the sigsegv example to test the crash handler after compiling g3log with MinGW, but unfortunately, the call stack contains some mangled symbols and some of the entries (the more meaningful ones) are empty. This is a release build, in which case it makes sense that there is no symbol information available, but this is where the call stack in the log file is actually helpful. Is there some way to achieve a meaningful call stack in a release build?

>***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION   PID: 3432
>
>******* STACKDUMP *******
>
> stack dump [0]   strftime
> stack dump [1]   vsprintf_s
> stack dump [2]   vsnprintf_s
> stack dump [3]   ZN10LogCapture8capturefEPKcz
> stack dump [4]
> stack dump [5]
> stack dump [6]
> stack dump [7]
> stack dump [8]   BaseThreadInitThunk
> stack dump [9]   RtlUserThreadStart
> 
> Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION'

**Comment by KjellKod** [comment]
Make sure you have the right compiler flags for enabling symbol context `-g` on hv I believe.

The dump here seems to be the last part of the dump where G3log shuts down the process. I.e not where the issue happened but the last stages before exit

**Comment by coderalpha** [comment]
We tried the -g option, but the call stack was still not complete. We then tested with a debug build with the same result. However, when we disable the crash handler and use DrMinGW, the call stack contains the symbol information.

**Comment by KjellKod** [comment]
Interesting. 

I've the least experience with MinGW Im mostly on gcc maybe that's why I haven't seen this before. 

Let me know if you come up with a resolution. The MinGW support is so far provided by the community (not me)

**Comment by KjellKod** [comment]
Pending to be closed due to lack of information

**Comment by coderalpha** [comment]
I haven't found a solution yet! Will still investigate since this is one of the major reasons why I want to use g3log.

**Comment by KjellKod** [comment]
closed to lack of response
