### ISSUE TITLE
g3log breaks __attribute__ with clang on windows simulating cl

### ISSUE THREAD

**Issue by ngladitz** [KjellKod/g3log#282]
https://github.com/KjellKod/g3log/blob/14db37ad2313292e4d950fb0c959e92f3182ca48/src/g3log/logcapture.hpp#L53

`__attribute__` is required internally by e.g. clang intrinsic headers which are pulled in by e.g. `<future>` and which are broken by this.

Instead of defining `__attribute__` at all (which seems error prone and effects non-g3log code) perhaps a custom g3log specific macro should be used instead which expands to `__attribute__` where available.

**Comment by KjellKod** [comment]
Interesting. This was introduced 5 years ago and there are many clang compiler users who are using G3log without issues. 

Please give me a simple code example, a main.cpp, which uses G3log and where the functionality is broken by this. 

Please also explain environment, compiler setup and all flags passed in to the compiler
Thanks

**Comment by ngladitz** [comment]
Thank you for looking into this.

Here is a log from a test case that includes the source file, the compiler version (current LLVM windows installer i.e. http://releases.llvm.org/6.0.1/LLVM-6.0.1-win64.exe), invocation and output (shortened to only include two of the errors since the rest look similar).
To reiterate this specifically happens with Clang when it simulates cl (the Microsoft compiler; `__GNUC__` is not defined) not with Clang when it simulates gcc (`__GNUC__` is defined).

```
C:\Users\n.gladitz\Desktop\testcase>type test.cpp 
#include <g3log/logworker.hpp>

C:\Users\n.gladitz\Desktop\testcase>clang-cl --version 
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin

C:\Users\n.gladitz\Desktop\testcase>clang-cl test.cpp /I. /c 
In file included from test.cpp:1:
In file included from .\g3log/logworker.hpp:16:
In file included from .\g3log/sinkhandle.hpp:11:
In file included from .\g3log/sink.hpp:14:
In file included from .\g3log/future.hpp:28:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include\future:24:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include\ppltasks.h:27:
In file included from C:\Program Files\LLVM\lib\clang\6.0.1\include\intrin.h:34:
In file included from C:\Program Files\LLVM\lib\clang\6.0.1\include\x86intrin.h:29:
In file included from C:\Program Files\LLVM\lib\clang\6.0.1\include\immintrin.h:28:
C:\Program Files\LLVM\lib\clang\6.0.1\include\mmintrin.h(81,40):  error: cannot initialize a parameter of type '__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values) with an rvalue of type '__v2si' (aka 'int')
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
                                       ^~~~~~~~~~~
[...]
                                       ^~~~~~~~~~~~
C:\Program Files\LLVM\lib\clang\6.0.1\include\mmintrin.h(539,40):  error: cannot initialize a parameter of type '__attribute__((__vector_size__(4 * sizeof(short)))) short' (vector of 4 'short' values) with an rvalue of type '__v4hi' (aka 'short')
    return (__m64)__builtin_ia32_psubw((__v4hi)__m1, (__v4hi)__m2);
                                       ^~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by KjellKod** [comment]
Thanks. 

I would need something that is repeatable since this has never before been repeated . 

Please see my previous reply and attach such a main.cpp code example with exact instructions on compiler and compiler flags and with an description of what fails. 

Since this is not reproduced or encountered before I really need that information to take this further 

Thanks
Kjell

**Comment by ngladitz** [comment]
Hi, not sure what else you are asking for. I already included the source file, instructions and flags in the above log.

**Comment by KjellKod** [comment]
I’m not seeing a test.cpp source code file only a log har mentions it.

**Comment by ngladitz** [comment]
Sorry if this wasn't clear. The content is in the second line of the log.
i.e. test.cpp just contains
```
#include <g3log/logworker.hpp>
```

That is sufficient to reproduce the issue.

**Comment by KjellKod** [comment]
Have you tried changing the CMake so it detects “if GNUC or Clang”?

**Comment by KjellKod** [comment]
Sorry. Not CMake it would be the “if defined” statements that would need this logic. 
It can be solved with CMake too but that would be a bigger change

**Comment by KjellKod** [comment]
Potentially this is *the key issue*:
```
this specifically happens with Clang when it simulates cl (the Microsoft compiler; `__GNUC__` is not defined) not with Clang when it simulates gcc (`__GNUC__` is defined).
```

It’s possible that setup isn’t commonly used and therefore this has gone undetected 

At the moment I do not have access to Windows/Clang environment. I’d recommend changing the  file to detect if it’s either GNUC or Clang and if that’s the case setup `__attribute__`

At the moment you are in a better position to test this than I am. If you put up a tiny PR to address this the cloud CI, my own testing and the community can try out the other environments. 

Going forward I need to look into setting up the cloud CI for this type of Clang and Windows mix.

Thanks for your help in reporting this

**Comment by KjellKod** [comment]
fixed
