### ISSUE TITLE
There's no doc for customized format?

### ISSUE THREAD

**Issue by leonleeann** [KjellKod/g3log#287]
Hi, KjellKod,
    I have learnt a few of g3log recently, and admired who created it. Great job!
But before I can apply it into my real work, I have not find any doc for "customizing log format".
The most similar topic I found is in example/main_contract.cpp, though it is about to "customizing log header". I tried to modify the content of the "newHeader" const, but it had no effect.
I guess that the log format can be customized certainly, while maybe doing it has not same interface as customizing header?
The suggestion is : It is better let the "customizing log format" has same interface as "customizing log header",
 and has a demo/example like doing so with headers.
Please forgive my poor English, I'm a Chinese. Hope I correctly expressed it.
Thanks!

**Comment by KjellKod** [comment]
Please see the example for creating your own logging sink. You can do that from scratch or just copy-and-change the existing logging sink (see also the repo g3sinks).

A logging sink can EITHER have a function that receives a std::string. In this case it is already formatted for you. 

OR you can have a sink receiving the LogMessage object (see test examples and code + doc). In this case you have all the functions “getters” as well as “raw” access to all the logging message properties. With this you can format the string or other output (?) anyway you like. 

Good luck
Kjell

**Comment by KjellKod** [comment]
Ref: 
https://github.com/KjellKod/g3log/blob/master/API.markdown
