### ISSUE TITLE
seems CPackLists.txt not included if compiled with MSVC

### ISSUE THREAD

**Issue by etorth** [KjellKod/g3log#295]
Thanks for the awesome g3log.

I was trying to use externalproject_add(g3log) to include it in my project and compile it on appveyor.

```cmake
ExternalProject_Add(
    g3log

    GIT_REPOSITORY "https://github.com/KjellKod/g3log"
    GIT_TAG        "master"
  
    SOURCE_DIR "${MIR2X_3RD_PARTY_DIR}/g3log"
    INSTALL_DIR "${MIR2X_3RD_PARTY_DIR}/g3log/build"

    UPDATE_COMMAND ""
    PATCH_COMMAND ""

    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${MIR2X_3RD_PARTY_DIR}/g3log/build/install -DCMAKE_BUILD_TYPE=Release -DG3_SHARED_LIB=OFF -DG3_SHARED_RUNTIME=OFF

    LOG_BUILD 1
    LOG_CONFIGURE 1
    LOG_INSTALL 1
)

SET(G3LOG_INCLUDE_DIRS "${MIR2X_3RD_PARTY_DIR}/g3log/build/install/include")
SET(G3LOG_LIBRARIES    "${CMAKE_STATIC_LIBRARY_PREFIX}g3logger${CMAKE_STATIC_LIBRARY_SUFFIX}")

INCLUDE_DIRECTORIES(SYSTEM ${G3LOG_INCLUDE_DIRS})
LINK_DIRECTORIES(${MIR2X_3RD_PARTY_DIR}/g3log/build/install/lib)
```

this works on linux but with msvc it always complains can't find target install.vcxproj.
seems the target ``install" no generated.

I checked g3log's CMakeLists.txt, and looks like it only include CPackLists.txt if on Linux/darwin/mingw. Is this on purpose?

BTW, g3log built with VS17 Win64 succeeds.
I found all the g3log.lib and test executives, just can't install it automatically.

Thanks,
Etorth

**Comment by KjellKod** [comment]
Hi

Yes. The CPack was experimental at the time of writing. At that time the Windows support was nonexistent

**Comment by etorth** [comment]
Thanks for the information, any plan to support it? what's the difficulty if not?
Maybe I can help.

Best,
Etorth

**Comment by etorth** [comment]
Thanks for the information, any plan to support it? what's the difficulty if not?
Maybe I can help.

Best,
Etorth

**Comment by KjellKod** [comment]
closing this as I am not planning to undertake this. 
If more people are requesting it then one of the Windows users should be able to pick it up
