### ISSUE TITLE
Functionality Question: Remove Sink

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3log#296]
Have you ever considered a removeSink capability ?
I am thinking of a scenario were I would like to add logging say at a project level.
Project opens / gets created, and I create a logger at the project path to log stuff and when the project is closed I removeSink.

**Comment by KjellKod** [comment]
Yes. I believe it’s one of the long kept issues. It was made in a branch by a community member - it was pretty good but too hacky to be approved. He got pissed at someone critiquing the code and closed the PR. You have more info here
https://github.com/KjellKod/g3log/issues/106

**Comment by talih0** [comment]
I'd be interested to help on this. I'll review what was done before

**Comment by KjellKod** [comment]
thanks @talih0 
let me know if you have any questions.  It is very possible that the bug discussed on the original PR - which caused a poor workaround - is no longer there. It was apparently only for Windows 32 bit if I remember correctly.

**Comment by KjellKod** [comment]
Let me know if you have any issues on this. If one of you have a 32-bit windows to test onnit would be easy to verify if the nasty workaround for unique-ptrs is still something to consider

**Comment by KjellKod** [comment]
Update: I am planning on taking on this work as a client wants this implemented.

**Comment by KjellKod** [comment]
@cstamatopoulos : this is now implemented with https://github.com/KjellKod/g3log/pull/361
Thank you for pushing me on this. 

Kudos to @gimesketvirtadieni for the original idea for this.  https://github.com/KjellKod/g3log/pull/105
