### ISSUE TITLE
README claims C++11 compatibility, yet Build still adds flags for C++14

### ISSUE THREAD

**Issue by karololszacki** [KjellKod/g3log#297]
I see that since tag `1.3.1` the build requires C++14 (`std::make_unique` among other changes)
https://github.com/KjellKod/g3log/releases/tag/1.3.1

But README and GitHub repo description both still mention `C++11` and I was confused as to what was going on...
 
They both need updating.

**Comment by KjellKod** [comment]
Please put up a doc PR to address this 
At this point g3log is community driven and I review PRs but take no active part unless there’s a critical issue

Thanks

**Comment by KjellKod** [comment]
Updated readme.
