### ISSUE TITLE
CMake config does not create a target

### ISSUE THREAD

**Issue by michaelbgratton** [KjellKod/g3log#298]
In g3loggerConfig.cmake, I see that you're setting G3LOG_LIBRARIES and G3LOG_INCLUDE_DIRS, but I was expecting something like

```
add_library(g3logger SHARED IMPORTED)
find_package(Threads REQUIRED)
set_target_properties(g3logger PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${G3LOG_INCLUDE_DIRS}"
    IMPORTED_LOCATION "${G3LOG_LIBRARY}"
    IMPORTED_LINK_INTERFACE_LIBRARIES Threads::Threads
    )
```

so that us downstream folks can just depend on the "g3logger" target.

**Comment by KjellKod** [comment]
Not sure what you are asking for. 
Maybe putting up a non-breaking PR?
