### ISSUE TITLE
The headline on the front page still says c++11 though glog requires c++14

### ISSUE THREAD

**Issue by jjhegedus** [KjellKod/g3log#305]
I don't think there is a way to submit a pull request for the headline but it should still probably be updated.

**Comment by KjellKod** [comment]
Thanks. G3log supports c++11 through prior versions. 

I’ll see if I can update the headline

**Comment by jjhegedus** [comment]
Wow.  Impressive response time considering that you're letting the community manage g3log.  Thanks

**Comment by KjellKod** [comment]
Fixed

**Comment by jjhegedus** [comment]
Very impressive.  Thanks again
