### ISSUE TITLE
Error using g3log with HoloLens app

### ISSUE THREAD

**Issue by jjhegedus** [KjellKod/g3log#308]
I'm trying to get g3log working with a HoloLens app and I'm getting the following error when I launch my either directly on the device or on the simulator.  

`Unable to activate Windows Store App... process started, but the activation request failed with the error 'The app didn't start'`  It's a pretty unhelpful error but something I've seen before when I try to use a .lib that was built for a different architecture or even sometimes just for a different version of Windows.

So I think this error is due to an incompatibility between the way g3log is built and the way I have to build for the HoloLens.  HoloLens apps are UWP Windows Store apps and they require some pretty specific settings.  I was hoping to get a simple static lib as they are by far the easiest to consume from HoloLens apps.  When I looked at the configuration of the g3logger project it looks a little strange to me.  I'm not yet very familiar with CMake builds so this may just be my lack of understanding.  It was surprising to me that the Target Extension is set to .dll and the Configuration Type to Dynamic Library.  The build does generate the .lib file so I'm obviously not seeing the whole picture.  My guess is that I could take the source files and generate a build from them that would work for me but wanted to reach out to see if you had any suggestions before I do that.

Any suggestions would be greatly appreciated.

**Comment by KjellKod** [comment]
Never encountered this before. Maybe integrating G3log directly with your build system would remove it? It’s public domain so no need to share if you tweak it for your specific situation

**Comment by jjhegedus** [comment]
I created a new Visual Studio project to build it for HoloLens and got it working.  Not sure exactly what allows this to work when yours didn't.  If you're interested I could send you the project file that I was able to get working.

**Comment by KjellKod** [comment]
?
