### ISSUE TITLE
iOS builds don't honor disabling ENABLE_FATAL_SIGNALHANDLING settings for all architectures

### ISSUE THREAD

**Issue by mobileben** [KjellKod/g3log#309]
This is my bad. I left this out of the IOSBuild.cmake file. It turns out I need to disable fatal signal handling because it interferes with crash logging.

I already have a branch for this in my fork and have verified it works.

**Comment by KjellKod** [comment]
Done with: https://github.com/KjellKod/g3log/pull/310

Thanks!
