### ISSUE TITLE
32bit and 64bit side by side installs on Windows

### ISSUE THREAD

**Issue by jjhegedus** [KjellKod/g3log#314]
I've been able to create and install 32bit and 64bit side by side by specifying different install folders.  Wondering if this is the best option or if it would be better to use a methodology like boost where each variety of compilation is installed to the same folder but named based on the compiler options selected.  I've included the files generated for boost's serialization library below with a few options.  Many other options exist.

05/09/2018  08:08 PM        20,432,058 libboost_wserialization-vc141-mt-gd-x32-1_67.lib
05/09/2018  07:52 PM        24,426,862 libboost_wserialization-vc141-mt-gd-x64-1_67.lib
05/20/2018  08:37 AM         8,806,184 libboost_wserialization-vc141-mt-s-x32-1_67.lib
05/20/2018  09:38 AM        10,554,310 libboost_wserialization-vc141-mt-s-x64-1_67.lib
05/20/2018  08:21 AM        22,209,026 libboost_wserialization-vc141-mt-sgd-x32-1_67.lib
05/20/2018  09:22 AM        27,225,206 libboost_wserialization-vc141-mt-sgd-x64-1_67.lib
05/09/2018  07:37 PM         7,425,318 libboost_wserialization-vc141-mt-x32-1_67.lib
05/09/2018  08:00 PM         8,551,506 libboost_wserialization-vc141-mt-x64-1_67.lib

Really looking for opinions here.

**Comment by KjellKod** [comment]
Personally I prefer one location with the file name being specific

**Comment by jjhegedus** [comment]
Is it possible to set the library name when installing g3log?

**Comment by KjellKod** [comment]
Good question. I think it should be possible to set library prefix name through cmake  but I have not looked it up or used it in the past. If cmake supports it that should be the best way to solve it 

If cmake doesn’t support it you can always add another option in Options.cmake to specify build type or similar and prefix the library name with that

**Comment by jjhegedus** [comment]
Thanks I'll take a look at those and see what's possible.
