### ISSUE TITLE
Using g3log on the Magic Leap

### ISSUE THREAD

**Issue by jjhegedus** [KjellKod/g3log#315]
I'm running into a problem trying to get g3log working on the Magic Leap.  It seems that the Magic Leap is using a stripped down version of Linux that doesn't include execinfo.h.  Wondering if this is a showstopper that will require source code modifications with a new preprocessor definition to get around.  Also wondering if this is something you would be interested in supporting in g3log if that is the case.  I'm willing to do the work to make the changes but just wanted to check with you before moving forward.

**Comment by KjellKod** [comment]
That seems almost like a bug with MagicLeap if it is considered a developer
platform! I would raise the issue with them.
From:
https://www.gnu.org/software/gnulib/manual/html_node/execinfo_002eh.html .
if the platform is not supported but the Gnu lib is installed then the
execinfo.h should still be there but be just a `stub` that does nothing.

**Comment by jjhegedus** [comment]
I've raised it with them and they are "looking into it".  ;-)

In the meantime...
I'm not 100% sure but I don't think Gnulib is installed by default.  I'll verify and if it isn't, I'll see if I can install it.  If it is or if I can install it, that should allow g3log to compile, install and work with the limitation that calls to anything from execinfo.h will just silently do nothing?

**Comment by KjellKod** [comment]
Good question. I don’t know. I have never experienced a platform where it cannot be installed to run

**Comment by jjhegedus** [comment]
Guess I'll give it a shot and find out.

**Comment by jjhegedus** [comment]
I struggled with Gnulib and eventually tried adding a bare bones execinfo.h and execinfo.cpp with stubs.  This worked fine and I was able to get g3log compiled for the magic leap.  I also created a sink for writing logs using magic leap's ML_LOG macro and tested it successfully.

I was thinking that I would add the execinfo.h and execinfo.cpp files in the src and src/g3log folders respectively.  I would add an option (g3log_MAGIC_LEAP) for compiling for the magic leap in the CMakeLists.txt file and if that is set, include execinfo.cpp in the compilation.  I would create a CMake toolchain file for compiling for the magic leap using magic leap's mabu build utility and set g3log_MAGIC_LEAP in the toolchain file so if someone wanted to compile for the magic leap, all they would need to do is use the toolchain file.

Does that sound like a reasonable approach?

**Comment by KjellKod** [comment]
It does. 

Not sure it’s something that I want to add to G3log as it seems like a very unusual problem. 

If I may suggest something: create a separate repo and put it there and pull it down using whatever build chain you are using. 

That way G3log won’t have to be touched and you can install it independently. If the deva at MagicLeap corrects the platform deficiency then you just not longer have to install this workaround package. 

Another option is to fork G3log and keep this separate addition within that fork. As it’s “separate” it should be a small task to merge in future G3log changes to your fork

**Comment by jjhegedus** [comment]
I completely understand your hesitation.  Another thought I had was to create a magicLeapBuild folder under g3log and put the execinfo.h, execinfo.cpp, CMakeLists.txt and toolchain file in that folder.  The folder would be ignored when running the base g3log but we could add some instructions into the readme to drop into that folder to build for the magic leap.  Would that be any more palatable to you or would you really rather have it as a separate repo/fork?

**Comment by KjellKod** [comment]
A separate fork since it’s a one-off thing

**Comment by jjhegedus** [comment]
OK, sounds good
