### ISSUE TITLE
Recommendations for structured logging support

### ISSUE THREAD

**Issue by mobileben** [KjellKod/g3log#317]
Kjell,

This isn't an issue. Rather I want to see if I can move to using structured logging with g3log. My idealized state would be to have the logging come out as a JSON string. This will allow me to more easily run analytics on the client and server logs.

I think this should be possible with the proper sink and more than likely a pre-processing step on my side to pass through a JSON string as the message. I do already have a wrapper around g3log, so this would be easy to do with my current code base.

One of things I'm mulling over is whether or not the pre-processed string would inject certain data that g3log passes along (eg. file, line, level, etc) into the string or if the sink would do it. There is some redundancy of data floating around if I'm having to inject this into my JSON during pre-processing. Probably not the ideal thing to do, but I'm just going through the options. 

If I wanted to inject information at the end, I'd need to convert `std::string` -> JSON -> inject what I want -> `std::string`, which is a lot of extra work to be done. Have you ever had any thoughts to allowing some form of user data to be passed through with `LogMessage`? This may have some performance related issues as this data would more than likely need to be a `unique_ptr` or `shared_ptr`, especially if it's a JSON object/map being passed around.

Another very slight thing is that it would be nice to use the g3log threads to do the JSON work versus the calling thread. Not a big deal, just would be nice to have.

Anyways, just curious if you had any thoughts/recommendations around this.

Thanks!

**Comment by KjellKod** [comment]
Not sure I understand completely but I can try to answer

1. file, line, level etc is currently not written to the string message from the LOG calling thread. It’s added to the log message string through custom formatting  by the sink for sinks that receive the LogMessage struct. 

For sinks that receive a std::string the adding of log details happens also not from the LOG calling thread but from the log message dispatch thread that sends the log message to the sink 

2. By using the custom formatting option in sinks you could by having your own LOG call add json specifics to the std::string. A string is nothing more than a char array wrapped with more functionality so it is well suited for this. The final formatting and handling of the message data is the responsibility of the sink

3. `LOG(INFO) << 123 << “ test”;` Is using the stream operator at calling time. Details (level, file, etc) is handled at sink level. It would be an improvement to have all processing done later by the sink or just before sink processing but after the LOG calling thread. 

From a CPU perspective this would gain just a little compared to gain if I replaced the queues. At the moment I suspended the queue replacement work since I switched job and state and got less free coding time 

I hope this answers your questions. It was a late reply. For some reason I thought I had replied to you earlier

**Comment by mobileben** [comment]
Okay, so I had some more time to look into this. I have something basically working, however right now it isn't JSON. Rather it is key value pairs.

Output looks like

> key1=value1 key1=value2 ....

Closer, but not the ideal JSON format. 

I achieved this following what is done in `FileSink` and implementing `overrideLogDetails` and implementing my own custom log details.

Let me take a step back to better explain the desired outcome. An example of what an "ideal" output would be wold be something like:

> {
> 	"timestamp": 1562352227,
> 	"level": "INFO",
>	"file": "file.cpp",
>	"func": "void func()",
> 	"field0": 1,
> 	"field2": "2",
> 	"message": "Just some message"
> }

Although it would not be prettified like this in the stream and obviously time format doesn't really matter.

Most sink writers seem to follow the pattern of using something like this:

        std::cout << msg.toString(logDetailsFunc) << std::flush;

Typically `logDetailsFunc` is omitted, but this is a snippet from my writer where I am overriding the log details func.

Obviously if I want to output JSON, I can't quite follow that and would need to completely ignore using `toString`, since `toString` essentially appends `_message` to the log details (normal case). 

Ideally what would be helpful is having some additional "data" attached to `LogMessage` which would then allow writers to then manipulate that data into some output. Or the other option is to have some code which packages the message as needed before going to `LogCapture`.

For example, in the case above, I'd have to get `LogMessage`'s  `_message` string to be something like this:

`_message = "\"field0\": 1,\"field2\":\"2\",\"message\":\"Just some message\"";`

And then in the sink writer, I'd need to add the outer '{}' as well as add the `timestamp`, `level`, `file`, and `func` fields. All doable. Looking to find a streamlined way of doing this that's reasonably efficient.

Sorry if this was a bit too much rambling. Some of this is me just "talking out loud" about vectoring in on a good approach to solve. I do understand `g3log` isn't built for this. 

Just seeing your thoughts on this and if you have another possible approach.

**Comment by mobileben** [comment]
Okay, I'm closing this. I have it working. I'm cleaning up the code and need to add in some code to escape strings.

I ended up creating a json fragment builder. Not a full blown json serializer, but a little something more simple to get up and running.

The fragment builder is used to assemble the main message as well as the log details. The sink does final assembly of the fragments. 

Some parts of the code are probably not optimal since it requires some more processing to get everything formatted properly.

**Comment by KjellKod** [comment]
Cool! Sorry that I wasn’t much of a help. Did you end up modifying g3log or was it all done through the existing LogMessage (+ custom calling and custom sink)

**Comment by mobileben** [comment]
No worries. It was helpful to just go through the thought process here. There was no need to do any mods to `g3log`. The worse part, which I'm still doing, is moving the existing log calls over to the newer format. Sort of shocking just how many lines of logging I have.

To help with the transition, I made the existing log call pair the generated message with the key `message`, so it will be compatible with a fragment. This way it can get injected into the structured logging.

The solution ends up being a "front end" to pass `LogCapture` a JSON Fragment and a custom sink.

Populating a fragment looks something like

```
    fragBuilder_.addFragment("method", method)
                .addFragment("url", uri)
                .addFragment("request_id", requestId)
                .addFragment("user_agent", userAgent)
                .addFragment("ip_address", ipAddress);
```

Front end looks like

```
void logger::Logger::log(const char *file, const int32_t line, const char *function, Level level, const JsonFragmentBuilder& jsonFragmentBuilder) {
#ifdef USE_G3LOGGER
    LogCapture capture(file, line, function, toG3Level(level));
    // Assumption is fragment has already been escaped
    capture.stream() << jsonFragmentBuilder.getFragment();
#endif /* USE_G3LOGGER */
}

```

The sink essentially just looks like

```
void g3::ConsoleSink::writer(LogMessageMover message) {
    auto& level = logger::toG3Level(config.level);
    auto& msg = message.get();
    if (msg._level.value >= level.value) {
        JsonFragmentBuilder builder;
        auto now_s = std::chrono::time_point_cast<std::chrono::seconds>(g3::to_system_time(msg._timestamp));
        auto timestamp = static_cast<uint32_t>(now_s.time_since_epoch().count());
        builder.addFragment("level", msg.level()).addFragment("timestamp", timestamp);
        std::cout << '{';
        if (msg._level.value >= g3::kWarningValue || msg._level.value < g3::kInfoValue) {
            builder.addFragment("file", msg.file())
                    .addFragment("function", msg.function())
                    .addFragment("line", msg._line);
        }
        builder.appendFragment(msg.message());
        std::cout << builder.getFragment();
        std::cout << '}' << std::endl << std::flush;
    }
}
```

I will probably toy around with making a front end that is a little friendlier to build the fragments with. This certainly suffices for now.
