### ISSUE TITLE
How to compile the g3log with Crystax NDK for Android

### ISSUE THREAD

**Issue by NikitaFeodonit** [KjellKod/g3log#32]
I use the Crystax NDK as alternative of the Android NDK (see https://www.crystax.net/). I made Standalone Toolchain in the Msys2-x64 (Windows 7 x64):
```bash
mount e:/Dev/Tools/Android/crystax-ndk-10.2.1 /local32/crystax-ndk-10.2.1
export ANDROID_NDK_ROOT=/local32/crystax-ndk-10.2.1
$ANDROID_NDK_ROOT/build/tools/make-standalone-toolchain.sh --platform=android-9 --toolchain=arm-linux-androideabi-4.9 --stl=gnustl --system=windows-x86_64 --install-dir=$ANDROID_NDK_ROOT/standalone_toolchain/android-9/arm-linux-androideabi-4.9
export NDK_STANDALONE_TOOLCHAIN_ROOT=$ANDROID_NDK_ROOT/standalone_toolchain/android-9/arm-linux-androideabi-4.9
export PATH=$PATH:$NDK_STANDALONE_TOOLCHAIN_ROOT/bin:$NDK_STANDALONE_TOOLCHAIN_ROOT/arm-linux-androideabi/bin
```

And now I need help for next steps for building of the g3log. Please help me.

Thanks.
Nikita

**Comment by KjellKod** [comment]
Not sure what you need help with, please elaborate.

If you don't want to do it in public you can reach me at hedstrom at kjellkod dot cc

**Comment by NikitaFeodonit** [comment]
I have not delved into the work with cmake for Android. I made simply the Android.mk file:
```
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := g3log
LOCAL_CPP_EXTENSION := .cpp

LOCAL_SRC_FILES :=
LOCAL_SRC_FILES += src/crashhandler_unix.cpp
#LOCAL_SRC_FILES += src/crashhandler_windows.cpp
LOCAL_SRC_FILES += src/filesink.cpp
LOCAL_SRC_FILES += src/g3log.cpp
LOCAL_SRC_FILES += src/logcapture.cpp
LOCAL_SRC_FILES += src/loglevels.cpp
LOCAL_SRC_FILES += src/logmessage.cpp
LOCAL_SRC_FILES += src/logworker.cpp
#LOCAL_SRC_FILES += src/stacktrace_windows.cpp
LOCAL_SRC_FILES += src/time.cpp

LOCAL_C_INCLUDES := $(LOCAL_PATH)/src
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/src

TARGET_PLATFORM := android-9
LOCAL_CPPFLAGS += -std=c++11
LOCAL_CPPFLAGS += -pthread
include $(BUILD_STATIC_LIBRARY)
```

But I got the error:
```
../src/../libs/g3log/src/crashhandler_unix.cpp:21:22: fatal error: execinfo.h: No such file or directory
 #include <execinfo.h>
```
Android NDK has not this file:
http://stackoverflow.com/questions/8115192/android-ndk-getting-the-backtrace
http://stackoverflow.com/questions/11194963/can-i-get-a-c-stack-trace-when-android-app-crashes

If I exclude crashhandler_unix.cpp from Android.mk then I got the error:
```
../src/../libs/g3log/src/logcapture.cpp:52: error: undefined reference to 'g3::internal::stackdump(char const*)'
../src/../libs/g3log/src/g3log.cpp:65: error: undefined reference to 'g3::installCrashHandler()'
../src/../libs/g3log/src/g3log.cpp:233: error: undefined reference to 'g3::internal::exitWithDefaultSignalHandler(LEVELS const&, int)'
../src/../libs/g3log/src/g3log.cpp:236: error: undefined reference to 'g3::internal::blockForFatalHandling()'
../src/../libs/g3log/src/logmessage.cpp:197: error: undefined reference to 'g3::internal::exitReasonName(LEVELS const&, int)'
../src/../libs/g3log/src/logworker.cpp:71: error: undefined reference to 'g3::internal::exitWithDefaultSignalHandler(LEVELS const&, int)'
```

**Comment by KjellKod** [comment]
You need to change some source code. Did you read the full length of the link you sent me. Apparently on Android you can use Callstack.h instead and the usage is way easier

'''
#include <utils/CallStack.h>
..
CallStack cs;
cs.dump();
'''

My suggestion is that you fork g3log. Create a "android crash handler" branch and in that branch use new files for android crash handling and stackdump.

You should not be using the windows and Unix specific files as they apparently do not apply on your platform

**Comment by KjellKod** [comment]
Hi Nikita, 

How are progress on this?  I will close this issue unless you have more to add to it. If you decide to continue to pursue this then I would love to see a pull request on g3log with Android support ... for now I do not have the environment to implement this support myself.

**Comment by NikitaFeodonit** [comment]
I have little knowledge of the C/C++, therefore now I'm trying another library.

Thank you for your responsiveness.

**Comment by frk2** [comment]
Im beginning to do this work now on my fork : https://github.com/frk2/g3log

Will submit a PR when Im done! I'm trying to write a crashhandler_android.cpp (which implements crashhandler.hpp).

**Comment by KjellKod** [comment]
Sweet.

Looking forward to see it :)
