### ISSUE TITLE
Why is _timestamp generated when LogMessage is created, not when LogCapture is?

### ISSUE THREAD

**Issue by gir489** [KjellKod/g3log#322]
For measuring consistency between calls, it would be good to know what exact time the log function was called from the caller, not when the logger is about to send the queue to disk.

**Comment by KjellKod** [comment]
Good question.  I think it actually would make sense to create it within the LogCapture object. I think it's lost in time the reason why it isn't. 

In practice it likely doesn't matter much. 
There's no thread handover from the `LOG` call until the timestamp is created. The timestamp is created within the `LogMessage` object within the execution of the `LOG` line
```
LOG(INFO) << "first"; // timestamp is created before foo executes
foo();
```
There can be a CPU context switching  between the tiny sequence from then the `LogCapture` is created until it falls out of scope (within the `LOG` line's execution). This could also happen if the timestamp would be generated within the `LogMessage`. 

I see no issue with changing this however. If you want to address this change then please put up a PR

**Comment by gir489** [comment]
I must've misunderstood the code. I thought `LogMessage` was created when the queue executes. If this is the case, I see no need to move it one class up the chain, if it's grabbing the time from when the log function is called.

**Comment by KjellKod** [comment]
Easy mistake. The copy constructor is invoked during the thread handoff
(for thread safety reasons in case of multiple sinks)
