### ISSUE TITLE
Terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by ballpgoddard** [KjellKod/g3log#325]
I'm currently just trying to setup a custom std::cout sink that I have seen in g3sinks, but I keep seg-faulting. 

My custom sink is
```  
#pragma once
#include <string>
#include <iostream>
#include <g3log/logmessage.hpp>
struct CustomSink {
     void ReceiveLogMessage(g3::LogMessageMover message) {
        std::cout << message.get().message() << std::endl;
     }
};
```

And in main():
```
m_logworker = g3::LogWorker::createLogWorker();
auto sinkHandle = m_logworker->addSink(std::make_unique<CustomSink>(), &CustomSink::ReceiveLogMessage);
g3::initializeLogging(m_logworker.get());
LOG(DEBUG) << "Started!";
 ```

As a side note, I can't seem to call `message.get().toString()` inside my custom sink.

What am I messing up here?

**Comment by ballpgoddard** [comment]
the default file sink does work though.

**Comment by KjellKod** [comment]
It looks correct but it's not a complete code setup so I can't say what's wrong. 

I can speculate:

`m_logworker` looks suspect. This should be a temporary not a class variable. See this for example of a correct setup. 

https://github.com/KjellKod/g3log/blob/a6788f89be9b477e156747837909e69fdb009ce6/example/main_contract.cpp

The most common issues that I've seen where this was happening were. 
1. Not properly using RAII
2. DLL usage mayhem (1. above)

**Comment by ballpgoddard** [comment]
I'm on Linux, but I made m_logworker a temporary variable but am still getting the same seg-fault. It's just odd cause I had it working with 1.3.2 with c++11, but I needed the overrideLogDetails stuff for the defaultFileSink so I went to master with c++14 and now my previous custom cout handler won't work.

**Comment by KjellKod** [comment]
Interesting. It might be an environment/system/compiler issue then. 

I'd suggest using the cmake options to build all unit tests and examples and run them **all**, both all unit tests and all examples.

**Comment by KjellKod** [comment]
Also. If you want me to actual look at what's going on you have to provide a small runnable/crashing example.

**Comment by ballpgoddard** [comment]
I'm dumb.jpg. I was accidentally linking against some random .so of the 1.3.2 build. Thanks for the help!

**Comment by KjellKod** [comment]
lol. np. Glad you sorted it out. It happens to the best of us!
