### ISSUE TITLE
component and log level

### ISSUE THREAD

**Issue by jsearles57** [KjellKod/g3log#327]
I was wondering if it was possible to add or if there is a better way to accomplish this.  I would like to have a component and log level and be able to specify for each component the log level.  This would allow me to get fine grained control over exactly what logging I desire.  Right now I have each "component" use a specific log level range, but this is not ideal as it means when setting setHighest() there is no way to get logging from any component above this.

**Comment by KjellKod** [comment]
Not sure I fully understand what you mean.  I'll try. 

1. You can create arbitrary log levels of your own choosing.  Each log level conforms to a logging ID but they can share logging IDs also. 
2. Each component, or file, or whatever can have arbitrary number of logging levels. 
3. You can turn on/off logging levels (see examples).  If you want this runtime you take a small performance hit. 
4. It is at a global scale that logging levels  are turned on/off  
5. You **can** have loggin levels turned on/off with more fine-grained control (say per `file` or `component`) this is not supported by the g3log framework directly but you can easily write your own logging sink that can be called (see examples) where you specify what logging levels you want shown. 

G3log is made to be extendible through the logging sinks.

**Comment by stefan-baranoff** [comment]
I think the use example is something where log messages would gain a new (optional if we could?) field for 'component'; something like:
`LOGF(INFO, ConnectionHandling, "New connection from %s; handling request", conn_info->to_string());`
Or for the stream operator variant I can see a few paths:
`LOG(INFO, ConnectionHandling) << "New connection from " << conn_info->to_string() << "; handling request";` or possibly `LOG(INFO) << LOG_COMPONENT(ConnectionHandling) << "...`

Components would then be enabled/disabled the same way log levels are but independently from them.

In our specific case we tried to create multiple levels to cover this, but as our code has gotten larger and more complex we are finding it difficult to work with. A developer working on Module A may not care about highly verbose messages from Module Q. So, just enabling a global equivalent to something like a `-vvvvv` and getting "TRACE5" verbosity globally does not work as the log files become too large to work with. We can easily produce 100s of GB of log files in under 5 minutes with full verbosity enabled.

Right now the only three ways we see without and explicit 'module' part would be

1. Creating a custom sink to filter on files
2. Prefixing messages with a component "[Module D] message text here" and creating a custom sink that parses the first part to find the module and filter on it
3. Creating levels something like: `MODULE_A_DEBUG`, `MODULE_A_TRACE1`, `MODULE_A_TRACE2`, ... for as many different actual 'levels' as we wanted for that module and then going on to `MODULE_B_DEBUG`, `MODULE_B_TRACE`, ... and so forth.

There are problems with all of these approaches and we thought adding a second variable to cover modules/components that can be enabled/disabled just like, but independent of, levels would be the simplest solution.


We are happy to take a swing at adding the feature and putting in a PR for it but wanted to get your take before doing the work. We'd much rather not maintain our own branch of the project if we can avoid it.

**Comment by KjellKod** [comment]
if the feature is added it would have to be a new log call since it otherwise would break functionality for other users.  C++ does not allow macro overloading on number of arguments. 

Personally I think this feature is better suited in a forked version of g3log. It is however a feature request that keeps popping up so I’m happy to help out with advice and review. 

If you go ahead with a PR then you get the benefit of peer reviews by me and hopefully other users (regardless if you later go the route of a forked version of g3log)

I would suggest keeping in mind:
1. Do not break existing functionality 
2. How to extend with new functionality for the default and existing third party sinks without breaking them. 

(I.e it is easier with a breaking change but that has to happen outside of the main version of g3log)

**Comment by KjellKod** [comment]
Closing due to lack of response
