### ISSUE TITLE
Accessing Sink After Adding

### ISSUE THREAD

**Issue by jenfredwell** [KjellKod/g3log#330]
Hello,

This is more of a question.  Is there any way to access a Sink after it has been passed to `addSink`?  I have created a sync that logs to a remote location and would like to be able to update the IP address in that sink without re-creating it.  Is this possible?

Thanks.

**Comment by KjellKod** [comment]
Yes, you can use the API to call **any** public function on the sink. It'll be a thread safe async call that will return a future with the result.  

Please see the documentation https://github.com/KjellKod/g3log/blob/master/README.markdown#code-examples

**Comment by jenfredwell** [comment]
Thank you for the quick response!  I had misunderstood the `call` function to be used for **any** public function.  That is exactly what I'm looking for.  Thanks for the clarification.
