### ISSUE TITLE
abort thread ID

### ISSUE THREAD

**Issue by MrLoo1** [KjellKod/g3log#331]
Could you please release a version that supports thread ID? The latest release 1.3.2 does not seem to support placeholder thread ID formatting

**Comment by KjellKod** [comment]
I believe by default thread ID is now shown. You can provide your own logging sink and customize the formatting. 

Thread ID is available: 
https://github.com/KjellKod/g3log/blob/1.3.2/src/logmessage.cpp#L173

**Comment by KjellKod** [comment]
Another option is to use master and either use a custom sink with your own formatting or override the formatting function as shown here: https://github.com/KjellKod/g3log/blob/a6788f89be9b477e156747837909e69fdb009ce6/test_unit/test_message.cpp#L54

**Comment by MrLoo1** [comment]
> I believe by default thread ID is now shown. You can provide your own logging sink and customize the formatting.
> 
> Thread ID is available:
> https://github.com/KjellKod/g3log/blob/1.3.2/src/logmessage.cpp#L173

**Comment by MrLoo1** [comment]
> I believe by default thread ID is now shown. You can provide your own logging sink and customize the formatting.
> 
> Thread ID is available:
> https://github.com/KjellKod/g3log/blob/1.3.2/src/logmessage.cpp#L173

Thank you for your reply. I will carefully see how to do it. If you have an example of customize the formatting. could you please provide it for me?

**Comment by KjellKod** [comment]
Please see the documentation and unit tests. It’s well documented in both
