### ISSUE TITLE
Using logrotate.d for time based rotation

### ISSUE THREAD

**Issue by bmagistro** [KjellKod/g3log#332]
I have not had a chance to let things run long enough yet.  In parallel with the development and testing are there any issues you would be aware of with using logrotate.d to manage the log file?  I am aware of the rotate sink but am after a time based vs sized based rotation.  Within logrotate, my plan was to use `copytruncate` so that the file being written to does not change.

Thoughts?

**Comment by KjellKod** [comment]
I haven't tested it so you would have to do that. 
I recommend checking the code for the default sink (that I'm assuming you are using).  It doesn't open and close the file per write (for efficiency reasons) so currently having the file truncated in the middle of a write might cause an issue.
