### ISSUE TITLE
Set `__attribute__((noreturn))` where applicable

### ISSUE THREAD

**Issue by Shachar** [KjellKod/g3log#335]
I often use the following code structure:

```
int someFunc() {
  ABORT("TODO implement");
}
```

This produces a warning: Non-void function does not return a value. In other logging facilities, I would set the fatal handler to have the attribute `__attribute__((noreturn))`. This tells the compiler that the function does not return, and eliminates this warning.

For example of such an implementation, see https://github.com/Practical/practical-sa/blob/master/lib/asserts.h#L22

Using `CHECK(false) << "TODO: implement"` should result in a similar end result.

**Comment by KjellKod** [comment]
Not sure what you are asking for here. If you have a suggestion for improvement please open up a PR

**Comment by KjellKod** [comment]
Are you saying that you get compilation warnings for calls to `CHECK(expression)` where the expression evaluates to false?

**Comment by Shachar** [comment]
So, first, I found out that C++ has a standard attribute for indicating functions that don't return.

Almost. I'm saying that I get compilation warnings on `CHECK(expression)` where `expression` is *compile time* known to be false:

```
#include <stdlib.h>

void deadEnd() {
    abort();
}

int returning() {
    if( true )
        deadEnd();
}
```

This compiles with:
```
$ g++ -Wall demo.cpp -c -std=c++1z
demo.cpp: In function ‘int returning()’:
demo.cpp:10:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
```

This, however, compiles without warnings:
```
#include <stdlib.h>

[[ noreturn ]] void deadEnd() {
    abort();
}

int returning() {
    if( true )
        deadEnd();
}
```

All I'm asking is that you annotate the function you call in order to make fatal logs not return with `noreturn`.

**Comment by KjellKod** [comment]
Please put up a PR for this. 
G3log is at this time community driven. I am happy to review PRs and in rare cases will resolve bugs.

**Comment by KjellKod** [comment]
closed due to no action @Shachar . If you put up a PR for this I'll be glad to review it.
