### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by Croydon** [KjellKod/g3log#338]
**Is your feature request related to a problem? Please describe.**
Please create a new release, i.e. a git tag

**Describe the solution you'd like**
Having a new git tag

**Describe alternatives you've considered**
-none-

**Additional context**
There is interest of creating a g3log recipe for the C/C++ package manager [Conan](https://conan.io). It would be nice if we can package a newer version. The last version is from March 2018.

Thanks!

**Comment by gir489** [comment]
Sorry, I'm not sure what your issue is. You do know what a library is, correct? This has no purpose without a parent project to attach it too. If you are REALLY interested in just logging stuff to a disk, please use the included CMake build and test suites. Otherwise, you will need to manually integrate it to the Conan project you mentioned and build it yourself. If you are still confused, please reply back with further questions.

**Comment by Croydon** [comment]
Projects do releases. The last release g3log has done is [version 1.3.2 from March 2018](https://github.com/KjellKod/g3log/releases/tag/1.3.2).

I'm asking for a new one.

**Comment by gir489** [comment]
I understand that, but you can simply just fastforward the HEAD of which the project's [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) point at. Of which, you can dirty the submodule and push to arbitrary URLs for merging. Git has the tools to do this, I'm not sure why the hand-holding is required. If the project wishes to adopt g3log, they want a stable read to deploy logger, not some commits the team doesn't feel is ready for deployment.

**Comment by KjellKod** [comment]
@Croydon : I haven't done any new releases because since March 2018 there aren't any significant changes. There have been smaller changes on the master but not significant enough to warrant a new release. 

I might still create a new release but I hadn't planned to do that before the summer.

**Comment by KjellKod** [comment]
Also. Sorry for the late reply @Croydon. ClassPass laid me and 53% of the workforce off recently. I think this issue was created before I changed my email on github so the notification was sent to my inaccessible email at ClassPass.

**Comment by gir489** [comment]
I’m sorry to hear you lost your job. I lost my job too in December.

**Comment by Croydon** [comment]
@KjellKod Thanks for the answer and sorry to hear that you lost your job.

I hope that you are going to be alright 🙂

**Comment by KjellKod** [comment]
@gir489 damn that sucks.   For some reason my email is still messed up. I didn't see your replies at all. I need to figure out what's up. I dont' see the emails in my spam either. 

I hope @gir489  you are landing something new soon.  I'm still looking :/

**Comment by gir489** [comment]
We were discussing the virtues of C++ at work today, and STL deprecation came up and reminded me of this project. I hope you also have found work too, @KjellKod. Best wishes.

**Comment by KjellKod** [comment]
Thanks @gir489

I have. I'm Head of Engineering at Flowhub, Colorado since the beginning of
August.
I'll update my github profile :)


* Contact Information
* Kjell Hedström
* Mobile:  +1 - 617.378.1915
* E-mail: Kjell.Hedstrom@gmail.com

**Comment by KjellKod** [comment]
FYI: for anyone watching this closed issue. 
We have released g3log and g3sinks a short while back with support for c++17
