### ISSUE TITLE
Setting static (compile time) log levels

### ISSUE THREAD

**Issue by sflis** [KjellKod/g3log#341]
**Is your feature request related to a problem? Please describe.**
I'm currently working on a project that unfortunately lacks logging so I started working on adding that. g3log looked like a nice small log library for this task as it is asynchronous, it's easy to define custom sinks and has a nice logging mechanism (having the choice between streams and formatted strings). The only (big) issue is that this library seems more geared towards dynamic log level setting  while for our project it is more important to be able to set the log level statically (at compile time). The typical case being that log levels below `INFO` like `DEBUG` should be optimized away by the compiler in release builds.  Therefore I would like some mechanism where one could (at compile time) set a log level for which log messages below this level will be optimized away by the compiler. Alternatively disable specific log levels with the result as mentioned previously. 

**Describe the solution you'd like**
An example:
```c++
#define GLOGLEVEL 299
#include <g3log/g3log.hpp>
//Alternatively 
DISABLE_LOG_LEVEL(DEBUG)

int main(){
LOG(DEBUG)<<"This message will be optimized away by the compiler";
LOG(INFO)<<"This message will not be optimized away by the compiler";

}
```

**Describe alternatives you've considered**
For our project I have written a header file called g3logpatch.hpp which redefines the ` INTERNAL_LOG_MESSAGE` macro that instead calls a templated function called `get_stream` which either return  a `LogCapture` object or an object (`NullStream`) that has the same interface as `LogCapture` but has no side effects and thus gets optimized away by the compiler. 

```c++
#pragma once
#include <memory>
#include <g3log/logmessage.hpp>
#include <g3log/logworker.hpp>
#include <g3log/g3log.hpp>
//This null stream makes it possible for the
//compiler optimize away logging outputs when
//certain loglevels are disabled
class NullStream {
public:
    template<typename TPrintable>
    NullStream& operator<<(TPrintable const&)
    { return *  this; } /* no-op */
    NullStream& stream(){return *this;}
    void capturef(const char *printf_like_message, ...){}
};

#if (__cplusplus == 201703L)

#ifndef GLOGLEVEL
#define GLOGLEVEL 1
#endif

template <std::size_t I>
auto get_stream(const char *file,
                const int line,
                const char *function,
                const LEVELS &level){
    if constexpr(I >= GLOGLEVEL){
        return std::make_shared<LogCapture>(file,line,function,level);
    }else{
        return std::make_shared<NullStream>();
    }
}

#else//__cplusplus == 201703L
template <std::size_t I>
auto get_stream(const char *file,
                const int line,
                const char *function,
                const LEVELS &level){return std::make_shared<LogCapture>(file,line,function,level);}

#endif

//Macro to disable a specific log level
//It only affects the specified level, i.e levels below
//will not be disabled. The log level to be disabled has
//to be defined when calling this macro
#define DISABLE_LOG_LEVEL(LEVEL)\
template <> inline auto get_stream<LEVEL##_VAL>(const char *file,\
                                                const int line,\
                                                const char *function,\
                                                const LEVELS &level) {return std::make_shared<NullStream>();}

//Redefine the log macro from g3log to use the get_stream selection function
#undef INTERNAL_LOG_MESSAGE
#define INTERNAL_LOG_MESSAGE(level) (*get_stream<level##_VAL>(__FILE__, __LINE__, static_cast<const char*>(__PRETTY_FUNCTION__),level))


//Convienience macro for defining a const level value to be used with
//get_stream
#define SET_LOG_LEVEL_DEF(LEVEL,VAL)\
    static const int LEVEL##_VAL = VAL;
//Convienience macro for adding a new log level by declaring a new
//g3log LEVELS object and calling SET_LOG_LEVEL_DEF so it can be used with get_stream
#define ADD_LOG_LEVEL(LEVEL,VAL)\
    const LEVELS LEVEL {VAL, #LEVEL};\
    SET_LOG_LEVEL_DEF(LEVEL,VAL)


//Adding level constants for existing
//log levels in g3log
SET_LOG_LEVEL_DEF(INFO,300)
SET_LOG_LEVEL_DEF(DEBUG,100)
SET_LOG_LEVEL_DEF(WARNING,500)
SET_LOG_LEVEL_DEF(FATAL,1000)
```
The nicest thing would of course be to set a log level which automatically disables all lower log levels, but as you can see in the code above I only managed that using `if constexpr()` which is a c++17 feature.  However with c++14 and c++11 one can still disable specific log levels.  From what I can see this should not affect the dynamic log level setting except that you will not be able to set the log level dynamically lower than you set it statically and expect output since those outputs have been optimized away by the compiler.

**Additional context**
I was considering working on a pull request but I decided to first bring this issue here so I could get input from you on anythings I have missed regarding side effects on the dynamic log level setting.

**Comment by KjellKod** [comment]
Hi please see the API documentation. You can choose to turn off DEBUG at will. https://github.com/KjellKod/g3log/blob/master/API.markdown#disableenabled-levels-at-runtime

And: https://github.com/KjellKod/g3log/blob/master/src/loglevels.cpp#L76

And check the file with unit tests that verifies this: https://github.com/KjellKod/g3log/blob/a6788f89be9b477e156747837909e69fdb009ce6/test_unit/test_message.cpp#L363

——
You could add the static compile turn off like you suggest. The problem is that such a repo change would affect everyone.  The API usage above has in reality such a tiny impact on the LOG call that it’s negligible. 
——
Another option than specifically call out in production (ref API) that DEBUG should be disabled would be to simply force a DEBUG level to return false in production. One ifdef in this function could take care of that.  

https://github.com/KjellKod/g3log/blob/master/src/loglevels.cpp#L136

G3log is public domain so you could make that tiny change on your own fork and it would still be very easy to pull in any newer changes to the library as your change would be in an isolated location.

**Comment by sflis** [comment]
Thank you for your response! 

> Hi please see the API documentation. You can choose to turn off DEBUG at will. https://github.com/KjellKod/g3log/blob/master/API.markdown#disableenabled-levels-at-runtime
> 
> And: https://github.com/KjellKod/g3log/blob/master/src/loglevels.cpp#L76

I was aware of the ability to turn off log levels at runtime, but for us it is important  to turn off certain log levels at compile time (i.e not leaving any trace in the binary) for performance, binary size and security reasons.     

I understand that my request might be out of the scope for this library. However, a lot of other log libraries support the possibility to remove log levels from the binaries at compile time, including the glog library which you state that g3log is inspired by, so I was a little bit surprised that g3log did not support this.  

> You could add the static compile turn off like you suggest. The problem is that such a repo change would affect everyone. The API usage above has in reality such a tiny impact on the LOG call that it’s negligible.

The header file I presented shows how you can add this feature without touching the g3log implementation with minimal API changes to the library (the exception being how you add new log levels) and adding a few new API features.  The reason for the small API change is that the member `LEVELS.value` is not a valid value in `constexpr` and thus not a valid argument parameter for the function `<level>get_stream(...)`.  If `LEVELS.value` would be declared as `const` there should be no need to declare an extra global `const int` to hold the log level value that are used for the template argument. In such case there would be no change in the API besides the added features.

**Comment by KjellKod** [comment]
@sflis mixing runtime on/off of levels (+ adding custom logging levels) with static control of logging levels is something I debated with folks in the early conception of g3log/g2log. 

Performance-wise it's negligible for most use cases. G3log is used in several industries, like network traffic security software, that is processing in _soft_ realtime so its exceedingly rare that this tiny check would be an issue. 

I'm not aware of how this could impact on a system from a security reason.  If the system is compromised I think there are bigger issues than what can show up in the binary!

Unfortunately, I don't see how this change can be added to the repo without breaking long-standing existing functionality (as you pointed out yourself). The ability to dynamically being able to add logging levels are one of the key features requested by the community at g3log's (and g2log's) inception. 

-- 
I don't think this should hold you back however. You can go ahead with your `static` change or the `static` change I suggested (I believe they would amount to the same thing, really) in your own fork of the library.  It's **public domain** so there's no need to have your changes being re-incorporated back into the library.  The change is easy enough that it would be very, very easy to merge in future `HEAD` changes from g3log into your own fork.

**Comment by sflis** [comment]
@KjellKod Thanks for your explanation.  

For now I'm happy having my header file that adds `static` log levels on top of g3log directly inside the project, but I'll consider to do a fork of g3log where this header file is added. As you said it should not be hard to keep it up to date with the main g3log repo.

**Comment by KjellKod** [comment]
SGTM. Good luck :)
