### ISSUE TITLE
Initializing g3log in a function

### ISSUE THREAD

**Issue by AlphaCluster** [KjellKod/g3log#35]
This seems like it should be doable. What I am trying to do is put g3log into another library that is already being used. Now due to this whole setup I would like to do some lazy loading of the logger. Basically I am trying to initialize the logger into a global via the initialize function (since it will be run the first time someone tries to use the library) and then drop messages in using the save function. Now this does work if the setup of the global variable is in the main function but once i move it out of the main function it tells me the logger is not initialized. So I am wondering if there is a way to do this? I feel like it should be easier then this to load the sinks up in a separate function. Thanks for any help!

``` c++
#include <iostream>
#include "g3log/g3log.hpp"
#include "g3log/logworker.hpp"
#include "g3log/std2_make_unique.hpp"

g3::LogWorker *mainLogger;

void init()
{
    auto defaultHandler = g3::LogWorker::createWithDefaultLogger("cooltest", ".");
    g3::initializeLogging(defaultHandler.worker.get());
    mainLogger = defaultHandler.worker.get();
}

int main(int argc, char**argv)
{
	init();


	g3::LogMessagePtr message{std2::make_unique<g3::LogMessage>("test", 0, "test", DEBUG)};
	message.get()->write().append("test message");
	mainLogger->save(message);
	//g3::internal::pushMessageToLogger(message);

    LOG(DEBUG) << "This is a test!";
    return 0;
}
```

**Comment by KjellKod** [comment]
DefaultFileLogger that is returned by '''createDefaultLogger(...)''' is a simple struct that holds the worker by a unique_ptr.  By RAII the worker is destroyed then the '''defaulthandler''' goes out of scope. 

You find all the information that you need in logworker.hpp/cpp

Here's a initialization example that works in your scenario but does not account for calling init multiple times. 

'''
void init()
{

   static std::unique_ptr<g3::LogWorker> gMainLogger = g3::LogWorker::createWithNoSink();

   auto defaultHandler = gMainLogger->addSink(std2::make_unique<g3::FileSink>("cooltest", "."), &g3::FileSink::fileWrite);
    g3::initializeLogging(gMainLogger.get());
 }
'''

For some reason it does not work if i keep the unique_ptr in global scope but it works great in function static scope. I suspect that is a gcc 4.9.1 bug but I haven't researched it.

**Comment by will2142** [comment]
I'd also found it a bit confusing that LogWorker::createWithNoSink() and LogWorker::createWithDefaultLogger() have different return types.  Is there a use case for this?

**Comment by AlphaCluster** [comment]
Yeah i am curious too why createWithDefaultLogger() doesn't just make a LogWorker but instead had a DefaultFileLogger that contains the worker?

Though that code example you sent does work and I think I would just advise people to avoid the DefaultLogger if you plan to do anything remotely advanced (using anything but LOG(level) macros).

**Comment by KjellKod** [comment]
The DefaultLogger gives exactly the same behavior as in g2log. It was added for easy migration from g2 to g3.

If someone wants to do calls to the API of the file writing sink they have the handler available but otherwise they could just ignore it.

Do you think it makes more sense to *not* have access to the sink handle and if that is required just force the user to use "createWithNoSink()" and later add the file writing sink? (for handle access?)

I would be OK with that solution too. The default logger could return the worker and the handle would just go out of scope (removing API access th the sink)

**Comment by will2142** [comment]
I think it would make more intuitive sense to have a consistent return type for the two "createWith*" functions.  But I understand the desire to maintain backward compatibility, so you could just provide some documentation.  Maybe some doxygen comments?

**Comment by KjellKod** [comment]
I think I will take the approach to make the API consistent and provide comments as well as clarify this in the README.

It is a "breaking change" but the fix for users is tiny and easy to do.

**Comment by KjellKod** [comment]
@will2142 , @AlphaCluster   please take a look at pull request
https://github.com/KjellKod/g3log/pull/38

The API changes are:
```static LogWorker::createWithNoSink()
              ---> renamed:   static LogWorker::createLogWorker()```

```static LogWorker::createWithDefaultLogWorker 
             --> renamed and also no longer static
                    std::unique_ptr<FileSinkHandle> addDefaultLogger(...)
```

**Comment by KjellKod** [comment]
https://github.com/KjellKod/g3log/pull/38
