### ISSUE TITLE
libfmt support

### ISSUE THREAD

**Issue by gamelaster** [KjellKod/g3log#357]
libfmt is really nice, fast and safe library for string formatting, and it would be amazing to have it as string formatter instead of printf.
I know that g3log wants to be without any external dependencies, but this can be as optional dependency / feature.

Cheers

**Comment by KjellKod** [comment]
Yup I know of it. It would be a breaking change however for the LOGF users. 

If a g4log would be created then it’s something I would look into

**Comment by gamelaster** [comment]
Cool! Should I keep this issue opened?

**Comment by KjellKod** [comment]
No need. I don’t have that planned anytime soon and it would be a different repo
