### ISSUE TITLE
Multi-process, multi-thread, single file

### ISSUE THREAD

**Issue by aglabman** [KjellKod/g3log#364]
I have integrated g3log into a service that handles calls from multiple processes and spawns multiple threads that ultimately log to a single ascii log file. Things run well when I run a single process, ie. from a GUI interface, but when my service handles many processes, I begin to see jumbled output in my file when heavy logging occurs. 

Is this scenario possible using the g3log? I have been digging around and many posters suggest not using a single file to capture log data for multiple processes.

Would you use 1 sink per process? 

Part 2 of my integration relates to LogRotate. I give the user control to set the size and number of backup log files. With the multi-multi scenario, I sometimes see my trace archive file path message written after a number of messages instead of on line 1. I assume this relates to my issue above.

Thanks for your feedback.

**Comment by KjellKod** [comment]
Hi, if you have a single process owning the g3log and the other processes are sending the log to it then it should be fine. G3log handles multiple threads calling to it with `LOG` calls - this should not make things garbled. 

The problem I suspect is that you have **one** file for log writing across multiple processes with each one using a g3log logger and writing to the same file. If that's the case then it is up to the OS to define the behavior for the writing. 

Using g3log in each process with their own unique filename to write to is likely the easiest solution. You can use as many sinks as you want per g3log instance of course (but each sink should only touch their own file)

**Comment by aglabman** [comment]
Got it. Thank you for the prompt response. This is a great logger.
