### ISSUE TITLE
Add new log level

### ISSUE THREAD

**Issue by MarineChap** [KjellKod/g3log#379]
Dear, 

**Bug report** : Documentation bug related

**Description** :  I have been following the API documentation by creating my own loglevel.hpp file, I am not sure what is the next step after that to use it. Furthermore, this [doc](https://github.com/KjellKod/g3log/blob/5dd714b62619fd4bb498c9d8617453079a088e5d/src/g3log/loglevels.hpp#L78) in the code is very confusing. 
First example, we need to have addLogLevel and the second example not, with both time the G3_DYNAMIC_LOGGING option enabled. I am not sure to understand when we need it or not.  Could you explain me more please ? 
Thank you ! :) 

**Some context**: The falcon project had been using the g2log for a long time in interne. For our new version, we are switching on the g3log version by using cmake FetchContent to fetch from online.

**Comment by KjellKod** [comment]
1. When dynamic logging option is enabled then a default set of logging levels are enabled and anything else is disabled. Dynamic logging option makes it possible to turn on and off logging levels whenever 
2. If dynamic logging levels is NOT enabled then any logging levels will be enabled. 

If the logging levels provided are not enough you can add your own logging levels to your own logging levels file (I don’t recommend adding to the g3log logging levels file). 

Example of how adding logging levels is done: 
https://github.com/KjellKod/g3log/blob/master/test_unit/test_io.cpp#L633

**Comment by KjellKod** [comment]
I have updated the text. I hope this will make it clearer: 

https://github.com/KjellKod/g3log/blob/master/src/g3log/loglevels.hpp#L64

**Comment by KjellKod** [comment]
I will consider this issue closed. Please let me know if you have any other questions.

**Comment by MarineChap** [comment]
Thanks for your fast answer ! :) 
Ok I did not understood that I need to iclude my own log level file each time I want to use the my own level. It is working now.

**Comment by KjellKod** [comment]
Make sure to check also the API.markdown doc if you have future questions. I try to put more detailed API knowledge there. 
https://github.com/KjellKod/g3log/blob/master/API.markdown
