### ISSUE TITLE
linking fails when install in user home directory

### ISSUE THREAD

**Issue by tesla1060** [KjellKod/g3log#380]
**Describe the bug**
I have successfully compiled the lib following below, because I have no permission on /usr/local, I am having a linking error
but exact code can build on a `root` previlidged machine by install lib in /usr/local

Below are the details on the error

```
cmake .. -DCMAKE_INSTALL_PREFIX=/home/myname/opt
make 
make install
```
This has successfully installed lib in /home/myname/opt/lib64

> ls /home/myname/opt/lib64/
> cmake  libg3logger.so  libg3logger.so.1.3.0-0

my `CMakeList.txt` can find the lib with no problem, and I can print out `{G3LOG_LIBRARIES}`

```
# CMakeList.txt
cmake_minimum_required (VERSION 3.11)
project(test)

set(g3logger_DIR "/home/myname/opt/lib64/cmake/g3logger")
find_package(g3logger CONFIG REQUIRED)
message(${G3LOG_INCLUDE_DIRS})
message(${G3LOG_LIBRARIES})
include_directories(${G3LOG_INCLUDE_DIRS})

if (CMAKE_BUILD_TYPE MATCHES Debug)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17 -O0 -g -ggdb -Wall -pthread")
elseif (CMAKE_BUILD_TYPE MATCHES Release)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17 -O3 -Wall -pthread")
else()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17 -O3 -Wall -pthread")
endif()
add_executable(test_logger logger_test.cpp)
target_link_libraries(test_logger g3logger)
```
`make VERBOSE=1` gives the following output,

> make VERBOSE=1
> /usr/bin/cmake3 -H/home/myname/test -B/home/myname/test/build --check-build-system CMakeFiles/Makefile.cmake 0
> /usr/bin/cmake3 -E cmake_progress_start /home/myname/test/build/CMakeFiles /home/myname/test/build/CMakeFiles/progress.marks
> make -f CMakeFiles/Makefile2 all
> make[1]: Entering directory `/home/myname/test/build'
> make -f CMakeFiles/test_logger.dir/build.make CMakeFiles/test_logger.dir/depend
> make[2]: Entering directory `/home/myname/test/build'
> cd /home/myname/test/build && /usr/bin/cmake3 -E cmake_depends "Unix Makefiles" /home/myname/test /home/myname/test /home/myname/test/build /home/myname/test/build /home/myname/test/build/CMakeFiles/test_logger.dir/DependInfo.cmake --color=
> Dependee "/home/myname/test/build/CMakeFiles/test_logger.dir/DependInfo.cmake" is newer than depender "/home/myname/test/build/CMakeFiles/test_logger.dir/depend.internal".
> Dependee "/home/myname/test/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/myname/test/build/CMakeFiles/test_logger.dir/depend.internal".
> Scanning dependencies of target test_logger
> make[2]: Leaving directory `/home/myname/test/build'
> make -f CMakeFiles/test_logger.dir/build.make CMakeFiles/test_logger.dir/build
> make[2]: Entering directory `/home/myname/test/build'
> [ 50%] Building CXX object CMakeFiles/test_logger.dir/logger_test.cpp.o
> /usr/bin/c++   -isystem /home/myname/opt/include  -std=c++17 -O3 -Wall -pthread   -std=gnu++14 -o CMakeFiles/test_logger.dir/logger_test.cpp.o -c /home/myname/test/logger_test.cpp
> [100%] Linking CXX executable test_logger
> /usr/bin/cmake3 -E cmake_link_script CMakeFiles/test_logger.dir/link.txt --verbose=1
> /usr/bin/c++   -std=c++17 -O3 -Wall -pthread   CMakeFiles/test_logger.dir/logger_test.cpp.o  -o test_logger -Wl,-rpath,/home/myname/opt/lib64 /home/myname/opt/lib64/libg3logger.so.1.3.0-0 -lpthread
> CMakeFiles/test_logger.dir/logger_test.cpp.o: In function `CustomSink::ReceiveLogMessage(g3::MoveOnCopy<g3::LogMessage>)':
> logger_test.cpp:(.text._ZN10CustomSink17ReceiveLogMessageEN2g310MoveOnCopyINS0_10LogMessageEEE[_ZN10CustomSink17ReceiveLogMessageEN2g310MoveOnCopyINS0_10LogMessageEEE]+0xc4): undefined reference to `g3::LogMessage::DefaultLogDetailsToString(g3::LogMessage const&)'
> logger_test.cpp:(.text._ZN10CustomSink17ReceiveLogMessageEN2g310MoveOnCopyINS0_10LogMessageEEE[_ZN10CustomSink17ReceiveLogMessageEN2g310MoveOnCopyINS0_10LogMessageEEE]+0xcc): undefined reference to `g3::LogMessage::toString(std::string (*)(g3::LogMessage const&)) const'
> collect2: error: ld returned 1 exit status
> make[2]: *** [test_logger] Error 1
> make[2]: Leaving directory `/home/myname/test/build'
> make[1]: *** [CMakeFiles/test_logger.dir/all] Error 2
> make[1]: Leaving directory `/home/myname/test/build'
> make: *** [all] Error 2

**Comment by KjellKod** [comment]
Hmm. `g3logger` should be `g3log`.  That’s the only thing that stands out to me. 

It was called `g3logger` previously which was confusing and it got changed. The name change is on master and not yet on an official release but possibly you could have an issue due to this if you have the old “g3logger” installed elsewhere?

**Comment by KjellKod** [comment]
I realize there can be some gotchas when integrating the logger. 
Thanks for calling this out. I have created an example integration repo that shows how you can do this. Please take a look. 
https://github.com/KjellKod/g3log_example_integration

**Comment by tesla1060** [comment]
> I realize there can be some gotchas when integrating the logger.
> Thanks for calling this out. I have created an example integration repo that shows how you can do this. Please take a look.
> https://github.com/KjellKod/g3log_example_integration

strangely, both dynamic and static lib still gives me undefined reference when `cmake --build .`  even though my `CMakeList.txt` print out the correct lib path

> -- Found G3LOG: /home/myname/opt/include
> g3log package:
>     found: TRUE
>     include dir: /home/myname/opt/include
>     libraries: /home/myname/opt/lib64/libg3log.so.2.1.2-119;Threads::Threads

still undefined reference,

> CMakeFiles/test_logger.dir/logger_test.cpp.o: In function `CustomSink::ReceiveLogMessage(g3::MoveOnCopy<g3::LogMessage>)':
> logger_test.cpp:(.text._ZN10CustomSink17ReceiveLogMessageEN2g310MoveOnCopyINS0_10LogMessageEEE[_ZN10CustomSink17ReceiveLogMessageEN2g310MoveOnCopyINS0_10LogMessageEEE]+0xc4): undefined reference to `g3::LogMessage::DefaultLogDetailsToString(g3::LogMessage const&)'
> logger_test.cpp:(.text._ZN10CustomSink17ReceiveLogMessageEN2g310MoveOnCopyINS0_10LogMessageEEE[_ZN10CustomSink17ReceiveLogMessageEN2g310MoveOnCopyINS0_10LogMessageEEE]+0xcc): undefined reference to `g3::LogMessage::toString(std::string (*)(g3::LogMessage const&)) const'
> collect2: error: ld returned 1 exit status
> gmake[2]: *** [test_logger] Error 1
> gmake[1]: *** [CMakeFiles/test_logger.dir/all] Error 2
> gmake: *** [all] Error 2

**Comment by KjellKod** [comment]
Try to build the example that I made available, with no changes and follow the README instructions. Does that work?

**Comment by tesla1060** [comment]
No I follow the exact instruction, still not working.
this is my `cmake -DCMAKE_PREFIX_PATH=/home/myname/opt ..` output when cmake the example
>  cmake -DCMAKE_PREFIX_PATH=/home/myname/opt/ ..
> -- The C compiler identification is GNU 7.2.0
> -- The CXX compiler identification is GNU 7.2.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> -- Found G3LOG: /home/myname/opt/include
> g3log package:
>     found: TRUE
>     include dir: /home/myname/opt/include
>     libraries: /home/myname/opt/lib64/libg3log.so.2.1.2-119;Threads::Threads
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/myname/temp/g3log_example_integration/build
> 

and then when I run `cmake --build .`, here comes the undefined reference,

> Scanning dependencies of target example
> [ 50%] Building CXX object CMakeFiles/example.dir/example_main.cpp.o
> [100%] Linking CXX executable example
> CMakeFiles/example.dir/example_main.cpp.o: In function `main':
> example_main.cpp:(.text+0x279): undefined reference to `g3::LogWorker::addDefaultLogger(std::string const&, std::string const&, std::string const&)'
> example_main.cpp:(.text+0x2e9): undefined reference to `g3::FileSink::fileName()'
> example_main.cpp:(.text+0x329): undefined reference to `g3::FileSink::overrideLogDetails(std::string (*)(g3::LogMessage const&))'
> example_main.cpp:(.text+0x33c): undefined reference to `g3::LogMessage::FullLogDetailsToString(g3::LogMessage const&)'
> example_main.cpp:(.text+0x39b): undefined reference to `g3::FileSink::overrideLogHeader(std::string const&)'
> collect2: error: ld returned 1 exit status
> gmake[2]: *** [example] Error 1
> gmake[1]: *** [CMakeFiles/example.dir/all] Error 2
> gmake: *** [all] Error 2
> [ 50%] Linking CXX executable example
> CMakeFiles/example.dir/example_main.cpp.o: In function `main':
> example_main.cpp:(.text+0x279): undefined reference to `g3::LogWorker::addDefaultLogger(std::string const&, std::string const&, std::string const&)'
> example_main.cpp:(.text+0x2e9): undefined reference to `g3::FileSink::fileName()'
> example_main.cpp:(.text+0x329): undefined reference to `g3::FileSink::overrideLogDetails(std::string (*)(g3::LogMessage const&))'
> example_main.cpp:(.text+0x33c): undefined reference to `g3::LogMessage::FullLogDetailsToString(g3::LogMessage const&)'
> example_main.cpp:(.text+0x39b): undefined reference to `g3::FileSink::overrideLogHeader(std::string const&)'
> collect2: error: ld returned 1 exit status
> gmake[2]: *** [example] Error 1
> gmake[1]: *** [CMakeFiles/example.dir/all] Error 2
> gmake: *** [all] Error 2

**Comment by KjellKod** [comment]
Hmm. That is bizarre. What OS are you using? Sometimes oddities can show up
between OSX and Linux.
My testing so far is on Linux although I  the CI is running both on Ubuntu
and on OSX:
https://github.com/KjellKod/g3log_example_integration/runs/960913423

Not sure why this is failing for you:
Some other options.
1) Can you try the static build instead? (see the README)
2) A variation of 1 can be seen here:
https://github.com/KjellKod/g3log_example_integration/issues/1
<https://github.com/KjellKod/g3log_example_integration/issues/1> in general
a static build is often a little bit easier to work with.

**Comment by tesla1060** [comment]
I think i have narrow down the problem.
`gcc 7.2.0` seems to give the linking error
>  /usr/bin/c++ --version
> c++ (GCC) 7.2.0

I have another `gcc 7.3.0` works fine

> /usr/local/bin/c++ --version
> c++ (GCC) 7.3.0
once i let cmake use gcc 7.3.0, everything works fine.
