### ISSUE TITLE
why g3log seems to running slower than simple write to file, am I using it incorrectly?

### ISSUE THREAD

**Issue by tesla1060** [KjellKod/g3log#381]
Hi, I have performed the following simple benchtest using `g3log` agains simple `fout`, the result seems to be slower for `g3log`, I am wondering if I am using the log the wrong way? As I understand `g3log` is asynchronous, so each time it is called it pass the log string to another thread for writting to log file?

my simple code as per below,

```
#include <g3log/g3log.hpp>
#include <g3log/logworker.hpp>
#include <g3log/logmessage.hpp>
#include <chrono>
#include <fstream>
#include <vector>
#include <string>
#include <iostream>
#include <memory>
using namespace std;
using namespace std::chrono;
using namespace g3;

int main() {
    vector<string> str_list;
    int count = 1000000;
    //prepare the string to be written to log
    for (auto i = 0; i < count; i++) {
        string str = "str_" + to_string(i);
        str_list.push_back(str);
    }

    std::shared_ptr<g3::LogWorker> logworker{ g3::LogWorker::createLogWorker() };

    auto default_handle = logworker->addDefaultLogger("log", "./");
    initializeLogging(logworker.get());
    // time g3log
    auto log_start = system_clock::now();
    for (auto i = 0; i < count; i++) {
        LOG(DEBUG) << str_list[i];
    }
    auto log_stop = system_clock::now();
    cout << "g3log:" << duration_cast<std::chrono::milliseconds>(log_stop - log_start).count() << endl;

    ofstream fout;
    fout.open("./file_log.txt", std::ofstream::out);
    // time simple file write
    auto f_start = system_clock::now();
    for (auto i = 0; i < count; i++) {
        fout << str_list[i] << endl;
    }
    auto f_stop = system_clock::now();

    cout <<"simple file:" << duration_cast<std::chrono::milliseconds>(f_stop - f_start).count() << endl;

}
```

my result is :

> g3log:1910
> simple file:1252

**Comment by KjellKod** [comment]
I believe ofstream is buffering internally
Once in a blue moon it’ll flush it to disk. 

Typically you would then have one LOG call that takes a veeery long time but on average it’ll be pretty fast (depending on how frequently it flushes). This is exactly how Googles glog works. 

G3log does a handover to a background task. The overhead is essentially the mutex protection to ensure multiple threads can write to the logging sink and ensure FIFO order. 

Essentially you are benchmarking a threadsafe struct vs a non-threadsafe struct. The non-threadsafe ofstream  doesn’t have to pay for synchronization.

**Comment by tesla1060** [comment]
> I believe ofstream is buffering internally
> Once in a blue moon it’ll flush it to disk.
> 
> Typically you would then have one LOG call that takes a veeery long time but on average it’ll be pretty fast (depending on how frequently it flushes). This is exactly how Googles glog works.
> 
> G3log does a handover to a background task. The overhead is essentially the mutex protection to ensure multiple threads can write to the logging sink and ensure FIFO order.
> 
> Essentially you are benchmarking a threadsafe struct vs a non-threadsafe struct. The non-threadsafe ofstream doesn’t have to pay for synchronization.

i see, how can I make this benchmark more realistic? my aim is to compare `g3log`'s asynchrnous to synchronous writing to a file?

**Comment by KjellKod** [comment]
1. If you write with multiple threads to ofstream it’ll just be garbage output (undefined behavior)

2. You could use your own lock free mechanisms or mutex protected handover to the writing to ofstream. 

3. You could compare with another logger. 
G3log is not the fastest logger right now. It was when it was made but not anymore. It still stands out has having similar performance for each LOG call vs lock-free ones that can have tremendous latency spikes for SOME calls but on average will be faster.  Of course the crashhandling of G3log is also nice. 

I’ve debated making a g4log which would use lock free technology but without or minimized latency spikes but it’s simply not enough motivation (zero $) for me to take that on within the foreseeable future.

**Comment by tesla1060** [comment]
> 1. If you write with multiple threads to ofstream it’ll just be garbage output (undefined behavior)
> 2. You could use your own lock free mechanisms or mutex protected handover to the writing to ofstream.
> 3. You could compare with another logger.
>    G3log is not the fastest logger right now. It was when it was made but not anymore. It still stands with having similar performance for each LOG call vs lock-free ones that can have tremendous latency spikes for SOME calls but on average will be faster.  Of course the crashhandling of G3log is also nice.  There are at least 4-5 lock free, faster, loggers of various quality (some I would absolutely discourage from in case you are working with safety or mission critical software)
> 
> With sensible logging (log when it matters not overwhelmingly) ive seen G3log working with 10Gbps line rate packer analyzers and the performance was never an issue. “The fastest” is nice but might come at a price. Figure out what’s acceptable and what features are needed or not needed and make your choice then.
> 
> Figure out what’s acceptable in speed. Is acquiring a mutex lock acceptable for a LOG call? The “fastest” is nice but might come with some caveats. I’ve seen G3log used with 10 Gbps line rate network packet analyzers with no issues or dropped packages when doing sensible amount of log calls (even fairly aggressive - but never tested ludicrous amount)
> 
> I HAVE debated making a g4log which would use lock free technology but without or minimized latency spikes but it’s simply not enough motivation (zero $) for me to take that on within the foreseeable future.

understand. thanks for the advice.

**Comment by KjellKod** [comment]
No problem. There are several advantages and a few caveats with synchronous logging. Maybe that’s still the best for you. 

PRO: 
1. You know that if you make sure each log entry is flushed to disk that you’ll see all of them even if your app has a fatal, unplanned, exit/crash. 

2. It’s simple to setup and you don’t need a library to do it. 

CONS: 
1. You can’t write to the same file from multiple threads 

2. Depending on your buffer strategy and medium you are writing to the disk flushes may be little to overwhelming. HDs, SSDs, SD, Network etc all have an I/O latency that is unique to their domain. 
—- of course with buffering PRO/1 isn’t guaranteed unless you catch fatal exits with a signal handler
