### ISSUE TITLE
DEBUG is already defined elsewhere which clashes with G3Log's log level DEBUG

### ISSUE THREAD

**Issue by nnWhisperer** [KjellKod/g3log#385]
Hi,
When I try to build my project with gcc compiler, using the -DDEBUG flag, g3logger gives me error saying:

"DEBUG is already defined elsewhere which clashes with G3Log's log level DEBUG"

In my project, I use, g3logger with version 1.3.2-20190205, gcc 5.4.0 on an amd64 cpu, include the g3log directory to compilation search with -I$(g3log_folder_location) and link with -lg3logger. Am I misusing the flag or is "-g" flag sufficient?
Thank you,

**Comment by KjellKod** [comment]
Glad you managed to resolve it
