### ISSUE TITLE
macOS time drift / inaccuracy 

### ISSUE THREAD

**Issue by karololszacki** [KjellKod/g3log#386]
**Describe the bug**
Log entries on macOS can have a time delay.
We suspect this is connected to "system sleep", as mac users tend to just close the lid on their macbooks with our app open.
That way they run our app for several days, even weeks, and logs drift apart from real time.

We've seen discrepancies of even 80 hours:
app was started on 2020-08-31--20-43-39 (taken from our log name), 
there were several "system sleep" events (user simply not using their macbook for prolonged time),
and on 2020-09-07--09-49-00 (so a week later from app start) logs were reporting time of 2020-09-04--01-30-01

**To Reproduce**
macOS 10.15 Catalina, both for compilation and for user of our app.
There isn't really a code snippet I can give, we simply log some actions taken in app like in description:

```
LOG(INFO) << "something";
```

**Additional context**
I guess the issue has something to do with PRs #137 and #200.
Time points for each log go through the `to_system_time` method, which uses `static const` initialization for internal variables.
If there was a way to change them (via i.e. some exposed method) we could update both values (`hrs_now` and `sys_now`) on macOS wake-up events.

I know this report is somewhat vague but I tried my best to describe the situation.
I can share a log and video privately, if needed.

**Comment by KjellKod** [comment]
I think your bug report was spot on. Thanks for providing detailed analysis and calling out the PRs that made the change. 

One workaround would be to use your own sink (either copy  from g3sinks or the default one) and for the formatting step get the time stamp without calling into the `to_systemtime` function as that is causing you troubles.

**Comment by KjellKod** [comment]
At this point I'm not planning to take on this work.
