### ISSUE TITLE
No output to stdout/stderr

### ISSUE THREAD

**Issue by xgdgsc** [KjellKod/g3log#391]
**Is your feature request related to a problem? Please describe.**
Is there an option not to print anything to stdout/stderr? Now it prints the start and end like: `Exiting, log location: /tmp/simp/simp.log`
**Describe the solution you'd like**
An option not to print to stdout/stderr at all.

 
**Additional context**
This output would cause vscode testmate extension fail to parse google test output. https://github.com/matepek/vscode-catch2-test-adapter/issues/221

**Comment by KjellKod** [comment]
My suggestion would be to use your own logging sink. It could be as easy as just creating a carbon copy of the existing sink, name it something else and keep track of it in your own code base. 

Another option is to put up a pull request to address this - to choose to turn off this behavior

**Comment by KjellKod** [comment]
Path forward is laid out above
