### ISSUE TITLE
crashed on windows 10.

### ISSUE THREAD

**Issue by zh1an** [KjellKod/g3log#395]
**Describe the bug**
#387 (comment).

My g3log dll is managed by `vcpkg`. But I've modified it.

>  Is g3log using the default sink or through g3sinks? Are the logs too big (default log will write forever to the log, starting a new one for each process start, it's up to the user to manage it. G3sinks can manage the size of the logs)

No, I changed this function. I've checked the log size, it's 121MB. Sometimes it's more 500MB even 1GB. And the log file is logged in everyday not each process start.

**To Reproduce**
system: windows 10
compiler: msvc2015 with update 3

**Additional context**
The debug info:

![image](https://user-images.githubusercontent.com/30436038/103145077-35885080-476f-11eb-904b-07f0457b2cc4.png)

![image](https://user-images.githubusercontent.com/30436038/103145090-5badf080-476f-11eb-82f0-5438ecf55d45.png)

**Comment by KjellKod** [comment]
Please provide more context. As it is now this issue provides little context and is impossible to really understand. 

Maybe a super simple hello world that exhibits this problem. I've run W10 before without issues but haven't run VS2015 in a long time. It might be some issues there. 

please also know that master on g3log is now on C++17. If VS2015 doesn't support that then you need to use an older release of g3log. See the release information for more context.

**Comment by gir489** [comment]
It’s crashed on trying to access the mutex that sounds like thread safety issues. You mentioned a DLL so I’m assuming you’re referring to some kind of injected or dependency program. Does that program call code that is thread unsafe? That could cascade in to a crash in an irrelevant area of your DLL. I get crashes all the time from GTA inside of our JSON library and NTDLL. You have to check what’s on the call stack to see what it was the thread was doing at that particular moment to see if it really did crash there. If not the log is useless.

**Comment by KjellKod** [comment]
Interesting. 

Agreed. I’ve seen the difficulties with developers handling threaded structures inside DLLs. Yes, I wouldn’t be surprised if that’s it. 

Here are some unsafe thread practices that  I’ve seen in the past - sometimes even a combination of these. Some of these can work on one platform (although it’s undefined behavior) but will immediately fail on other platforms 

1) The DLL is owning the g3log instance through a static setup —> Fix: the main program needs to own the G3log instance

2) The G3log (thread) initialization call is handled in the “pre” startup hook routine 
—> on all platforms (OSX, Linux,Windows)  this is unsafe as these pre start routines must never have threaded construct / mutex etc in them 

3) The G3log shutdown call or destruction of the instance is handled in the “post” hook routine. Same issue here as in the 2) above

4) Although not a DLL issue per say, it’s similar in nature. Using forking (is it even possible in Windows?) and threaded structures is a recipe for disaster
