### ISSUE TITLE
Statically linked and stack dump

### ISSUE THREAD

**Issue by clauderobi** [KjellKod/g3log#397]
I am statically linking my applications, which prevents backtrace_symbols to report the function names. They are useful when looking at a stack dump....

An alternative is to use libunwind. There may be other alternatives but I've given it a try in a test program and it works perfectly. I did not test in the context of an exception but I am guessing that the nature of it makes it suitable for such context.

What is the best way to use it in g3log? This introduces a dependency hence my question as there are differents ways of doing this; take over the signal(s), modify stackdump in crashhandler_unix.cpp, etc.

**Comment by KjellKod** [comment]
It’s public domain so my recommendation would be to either fork it and adjust it as needed OR 
Using cmake options to disable the signal handler and use your own signal handler and crash mechanism. You can still hook in fairly easily the G3log shutdown and log flushing mechanisms

**Comment by KjellKod** [comment]
I see no action here on my end. best of luck
