### ISSUE TITLE
Include rename?

### ISSUE THREAD

**Issue by sbrkopac** [KjellKod/g3log#40]
Hi There,

Not sure if it's a typo or a name change. But in the instructions you have:

#include "g3log/g3logworker.hpp"

This file doesn't exist, should it actually be:

#include "g3log/logworker.hpp"

**Comment by KjellKod** [comment]
Thanks. Yup that's a typo. Thanks for catching it.

Can you make a pull request for it?

**Comment by KjellKod** [comment]
fixed in https://github.com/KjellKod/g3log/commit/7d2741c9a8a9862797026114799f5c885499ac29
