### ISSUE TITLE
LogWorker thread dies before stack generation completes (windows)

### ISSUE THREAD

**Issue by hoditohod** [KjellKod/g3log#400]
**Describe the bug**
We have applications running on Windows Server 2016, which are sometimes killed by the OS with illegal instruction exception. G3log kicks in (Vectored Exception Handler) to generate the stack and during this the process dies again, now with Access violation. 

The function that causes the Access Violation is g3::LogWorker::fatal, this is the point where the fatal log message is passed to the logworker thread. In the Windows crash dumps we see that at the time of the exception the neither the logworker nor the sink threads are existing. Sometimes only the faulting thread exists, sometimes few other threads as well (not all) but g3log is not there. 

So the questions are:
- have you seen such behavior so far?
- what could cause the g3log threads to terminate before the stack trace is written to the sink?

We're more or less familiar how the faulting thread is stopped while the logs are written to the sink on linux. But windows is a different world, any documentation on the topic would also help.

**To Reproduce**
OS: Windows Server 2016
Compiler: MS Visual Studio 2017
g3log version: Post 1.3.2, 9b5527d 
g3log is configured with a custom file writer sink, but it doesn't play any role in the above scenario.

No short reproduction code present at the moment.

**Additional context**
N/A

**Comment by KjellKod** [comment]
Interesting. Maybe you could clarify the picture a bit? 

Are you just now introducing G3log to the code base or have you successfully had it integrated and catching issues with G3log for some time? 
—> I have seen roughly similar behavior before in Windows and other platforms when 
A) G3log is  not instantiated correctly 
B) dll usage / ownership of G3log is used (I.e really A)

**Comment by KjellKod** [comment]
Windows/Linux works the same from a G3log perspective part from the specific fatal signal handling which is a weird beast on the Windows OS

the actual shutdown should work the same across all platforms. 

Fatal events/ Signal handling could also be adjusted to not catch certain things if you rather have Windows OS handle this and create dump information without G3log stack data in it. Ref: CMake options in G3log

**Comment by hoditohod** [comment]
Thanks for the quick answer.  
We're using g3log for quite some time now (~2 years) on windows and linux, without much of an issue. On windows it's built as a dll, which is used by the executable and other dll's. It is the executable's responsibility to initialize logging on startup, other modules may start using it after. G3log has crash handling enabled and produces correct stacks on crash. This setup works fine in our local development and test environments. 

The above issue is reported from a customer site and it's new for us as well. That's why started gathering information here, whether the issue is a known for the community (common misuse or misconfiguration of g3log)?

As a next step I'll try reproduce and isolate the problem.

**Comment by KjellKod** [comment]
Candidate for closing if there's no update on this ticket soon

A short example program would be helpful.  I'm suspecting this has to do with wonky initialization of g3log but it's impossible to say with the information available.

**Comment by KjellKod** [comment]
Closing due to lack of response
