### ISSUE TITLE
How to disable automatically added newline character?

### ISSUE THREAD

**Issue by shelllet** [KjellKod/g3log#406]
LOG macro will automatically add newline charactor to the output message. how to disable it?

**Comment by shelllet** [comment]
![image](https://user-images.githubusercontent.com/16729017/114840805-c1e77d80-9e09-11eb-9dc8-6aba317f900f.png)
![image](https://user-images.githubusercontent.com/16729017/114840826-c744c800-9e09-11eb-95dd-b18dfe96bfce.png)


the code `out.append(msg.message() + '\n');`  seems to be a problem. it cause a repeated message. 

if a message is : "(5,5)"  . then the final message will be :  "(5, 5)(5,5)\n"


related api link: https://github.com/KjellKod/g3log/blob/master/API.markdown#override-the-log-formatting-in-the-default-sink

**Comment by KjellKod** [comment]
The log macro doesn’t add it. The code above adds it. 

For custom formatting reasons (and more) g3log is made to be extensible with custom made sinks. Please read the documentation about this 

you can then format the output any way you like. A simple solution would be to have the existing default logger and copy-and-adjust it to your specific needs. 

To have custom formatting the logging sink should receive the logging message and not a std::string. Ref the docs + unit tests
