### ISSUE TITLE
Strange linking observed. Can't find a proper way to handle it.

### ISSUE THREAD

**Issue by HikariS97** [KjellKod/g3log#409]
```
# G3LOG
find_package(g3log CONFIG)
if (G3LOG_FOUND)
    include_directories(${G3LOG_INCLUDE_DIRS})
    list(APPEND libraries ${G3LOG_LIBRARIES})
else ()
    message("G3LOG not found error.")
endif ()

link_directories(${PROJECT_SOURCE_DIR}/runB/build)

include_directories(${PROJECT_SOURCE_DIR}/include)
add_executable(SomeTest main.cpp g3logger.cpp)
target_link_libraries(SomeTest pthread /usr/local/lib/libg3log.so.1 Boost::system)
```

If I omitted Boost::system, then I got this. 
libg3log.so.1 => not found

But if I append Boost::system in target linking process, linker works fine:
libg3log.so.1 => /usr/local/lib/libg3log.so.1 (0x00007ff5116da000)

It really confuse me.....................(However, same script works fine in OSX OMG.......Plz help!)

**Comment by KjellKod** [comment]
Not sure what's going on. g3log doesn't have any connections with Boost. 
I'd suggest printing out the information you have from the g3log cmake package when it's discovered and verify it's correct 


nitpicking: `g3logger.cpp` doesn't exist unless that's your own file or it's some old version of the g3log repo?

**Comment by HikariS97** [comment]
@KjellKod Yes, that is my own file.

Below is the output of 
` ls -l /usr/local/lib | grep g3log`
```
lrwxrwxrwx  1 root root       13 May 14 23:02 libg3log.so -> libg3log.so.1
lrwxrwxrwx  1 root root       21 May 14 23:02 libg3log.so.1 -> libg3log.so.1.3.2-132
-rw-r--r--  1 root root   299176 May 14 23:02 libg3log.so.1.3.2-132
```
And the output of `message(${G3LOG_LIBRARIES})` is 
`/usr/local/lib/libg3log.so.1.3.2-132Threads::Threads`
Wether if I append Boost::system or not, I got the same output of `G3LOG_LIBRARIES` ( and, as I mentioned above, I got linker worked fine in OSX)
If I append the path to libg3log.so.1 ( nether libg3log.so or libg3log.so.1.3.2 could work) in target_link_libraries, then linker can work.

I'm currently working on WSL2, maybe it's a special strange bug under WSL platform?
Here below is my whole `CMakeLists.txt ` content. ( vacant main function without any `include` in main.cpp)
```
cmake_minimum_required(VERSION 3.10)
project(SomeTest)

set(CMAKE_CXX_STANDARD 17)
set(libraries)

# BOOST
find_package(Boost REQUIRED COMPONENTS system)
if (Boost_FOUND)
    include_directories(${Boost_INCLUDE_DIRS})
    list(APPEND libraries Boost::system)
else ()
    message("Boost not found error.")
endif ()

# G3LOG
find_package(g3log CONFIG)
if (G3LOG_FOUND)
    include_directories(${G3LOG_INCLUDE_DIRS})
    list(APPEND libraries ${G3LOG_LIBRARIES})
else ()
    message("G3LOG not found error.")
endif ()

include_directories(${PROJECT_SOURCE_DIR}/include)
add_executable(SomeTest main.cpp g3logger.cpp)
target_link_libraries(SomeTest pthread ${G3LOG_LIBRARIES})
```


Have no idea about what's going on :))))))))))))

**Comment by KjellKod** [comment]
Candidate for closing if there's no update on this ticket soon.

**Comment by KjellKod** [comment]
Closing due to lack of response
