### ISSUE TITLE
Overriding LogRotateFilter throws 'std::logic_error'

### ISSUE THREAD

**Issue by bugAssassin007** [KjellKod/g3log#410]
![image](https://user-images.githubusercontent.com/80806418/120916995-71cebe00-c6ca-11eb-880c-2b5fffa962ad.png)

**Comment by KjellKod** [comment]
Can you setup a minimalistic example, one file, which has the same problem as you describe above?
I've not been able to recreate the situation you describe above.

**Comment by KjellKod** [comment]
I've added a unit test for the previous uncovered (doh!) `overrideLogDetails`, you an always build on something similar if you prefer to show the issue in a failing unit test? 

https://github.com/KjellKod/g3sinks/pull/115

**Comment by KjellKod** [comment]
I think I've one the error in your code. `MyCustomFormatting` should be using `msg` but instead it's using `logObj` which is not passed into the function. Not sure why the std::logic_error is being cast but this seem regardless to be an error with the code you describe in your screenshot.

I'm closing this ticket unless you have a follow-up. 
<img width="733" alt="Screen Shot 2021-06-07 at 9 29 06 PM" src="https://user-images.githubusercontent.com/331742/121118794-b1370080-c7d7-11eb-850b-f3a5c1e4c259.png">

**Comment by bugAssassin007** [comment]
I tried to use the same code as above for a single node/thread and it worked. However, when I'm using the same code for multiple threads, it gives me a segmentation fault.

**Comment by KjellKod** [comment]
Please address the bug that I called out. Ref screenshot and description

**Comment by KjellKod** [comment]
candidate for closing if I don't hear back in a couple of days

**Comment by bugAssassin007** [comment]
> I think I've one the error in your code. `MyCustomFormatting` should be using `msg` but instead it's using `logObj` which is not passed into the function. Not sure why the std::logic_error is being cast but this seem regardless to be an error with the code you describe in your screenshot.
> 
> I'm closing this ticket unless you have a follow-up.
> <img alt="Screen Shot 2021-06-07 at 9 29 06 PM" width="733" src="https://user-images.githubusercontent.com/331742/121118794-b1370080-c7d7-11eb-850b-f3a5c1e4c259.png">

I used logObj here as I dint want to change the library, but create a function part of a class that will pass the string for formatting the log. It seemed to have worked. It dint work earlier due to the reason that my code separated the initialisation and invoking of the sink and some threads invoked the service without initialising the sink in the first place. I corrected that. Thank you for your time and spontaneous help.
