### ISSUE TITLE
Warning calling find_package(g3log) in newer CMake

### ISSUE THREAD

**Issue by gmackey** [KjellKod/g3log#413]
**Describe the bug**
g3log is built and installed, and I'm using find_package() like below to include it in a different CMake project.

```
find_package(g3log PATHS <actual paths> REQUIRED)
```

This uses config mode.  With CMake 3.19.8, the following warning is issued:

```
CMake Warning (dev) at /opt/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args` (G3LOG) does
  not match the name of the calling package (g3log).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /Users/greg/Software/Installed/gems-tpls/lib/cmake/g3log/g3logConfig.cmake:74 (find_package_handle_standard_args)
  CMakeLists.txt:498 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**To Reproduce**
I'm running on macOS Big Sur, but after some searching it seems this warning was added to CMake in version 3.17 and people have encountered this on other OSes including ubuntu.  It's probably reproducible in any environment as long as the CMake version is 3.17 or higher.

**Additional context**
This is just a warning, and I can suppress it, but it would be nice if the issue were fixed.  Thanks for the work on this software!  It's a great package for logging.

**Comment by KjellKod** [comment]
Yup it’s benign, still a good warning.  Thanks for calling it out 

G3log is community driven so unless there’s a severe bug I am mostly helping out with code reviews and feature discussions 

I would suggest that you create a PR to resolve this issue and I’ll review it promptly

**Comment by KjellKod** [comment]
Reopening (to later close it hopefully) with the pending PR.

**Comment by KjellKod** [comment]
thanks to @zjeffer for addressing this in https://github.com/KjellKod/g3log/pull/457 and for @gmackey  who reported it in https://github.com/KjellKod/g3log/issues/413
 
 Update in g3sinks will happen shortly as well: https://github.com/KjellKod/g3sinks/pull/125
