### ISSUE TITLE
[Question] g3log does not show stack dump correctly when using in google c++ test framework TEST_F

### ISSUE THREAD

**Issue by Umair-Anwar** [KjellKod/g3log#414]
### In stack dump, it is showing only the class name not call stack (function names)
Here is my pseudo code
```
class TestClass : public TestDevOpsApiTraceCmds {
protected:
...
};

TEST_F(TestClass, traceCtrlAndExtractCMFwData_5_2) {
  traceCtrlAndExtractCMFwData_5_2(); // It calls many function inside before exception occurs that's for sure.
}
```
And when an exception occurs, it shows the following stack dump
```
***** FATAL SIGNAL RECEIVED ******* 
Received fatal signal: SIGFPE(8)	PID: 718

***** SIGNAL SIGFPE(8)

*******	STACKDUMP *******
	stack dump [1]  /usr/lib64/libg3log.so.2.1.2-138+0x1a600 [0x7fdcd6479600]
	stack dump [2]  /usr/lib64/libpthread.so.0+0xf630 [0x7fdcd5df7630]
	stack dump [3]  /var/umair/TestClass() [0x4209f7]
	stack dump [4]  /var/umair/TestClass() [0x413424]
	stack dump [5]  /var/umair/TestClass() [0x582579]
	stack dump [6]  /var/umair/TestClass() [0x57d368]
	stack dump [7]  /var/umair/TestClass() [0x55ff52]
	stack dump [8]  /var/umair/TestClass() [0x560789]
	stack dump [9]  /var/umair/TestClass() [0x560dab]
	stack dump [10]  /var/umair/TestClass() [0x56ad6b]
	stack dump [11]  /var/umair/TestClass() [0x58356d]
	stack dump [12]  /var/umair/TestClass() [0x57e068]
	stack dump [13]  /var/umair/TestClass() [0x5699a8]
	stack dump [14]  /var/umair/TestClass() [0x4143e6]
	stack dump [15]  /var/umair/TestClass() [0x41348e]
	stack dump [16]  /usr/lib64/libc.so.6__libc_start_main+0xf5 [0x7fdcd521c555]
	stack dump [17]  /var/umair/TestClass() [0x413185]

Exiting after the fatal event  (FATAL_SIGNAL). Fatal type:  SIGFPE
Log content flushed successfully to sink
```
### I want stack dump to show function calls as well.
Using try-catch, I have tried printing stack using `g3::internal::stackdump()` it shows the same stack dump with no function details.

I would like to have a pointer on what I am missing, or where I should look first. Any pointer towards a solution will be apprecitaed. Thanks

**Comment by KjellKod** [comment]
My guess is that  your project isn’t linked with the symbols so the symbol translation fails

**Comment by KjellKod** [comment]
It’s outside of the scope of support Intend to give to the community but this section of the cmake file can likely be used to do printouts and use it to debug why the “demangling” of symbols is failing for your project 

https://github.com/KjellKod/g3log/blob/master/Build.cmake#L105

**Comment by KjellKod** [comment]
Since I haven’t heard back this issue is soon to be closed
