### ISSUE TITLE
[Question] what is "wait" mean??

### ISSUE THREAD

**Issue by leechangyo** [KjellKod/g3log#416]
Hi Kjellkod! 

I try to use g3log and I'm following your example to write my log.

but I'm not sure what is "call" and "wait" mean here

```c++
   // Exmple of overriding the default formatting of log entry
   auto changeFormatting = handle->call(&g3::FileSink::overrideLogDetails, g3::LogMessage::FullLogDetailsToString);
   const std::string newHeader = "\t\tLOG format: [YYYY/MM/DD hh:mm:ss uuu* LEVEL THREAD_ID FILE->FUNCTION:LINE] message\n\t\t(uuu*: microseconds fractions of the seconds value)\n\n";
   // example of ovrriding the default formatting of header
   auto changeHeader = handle->call(&g3::FileSink::overrideLogHeader, newHeader);

   changeFormatting.wait();
   changeHeader.wait();
```

and one more, I want to save log files separately for each function. 
for example :

when some modules are running,  I want to save logs of some classes at different file names while other function save at some specific files. (this mean I want to use two or three files to save each function's log, not one. 

maybe my English or programmer skills are not good enough to understand your code and build mine.

that's why I directly ask you those questions. 

thank you for reading. I appreciate your work and looking forward to hearing from you soon.

**Comment by KjellKod** [comment]
Please see the source code for sink handle 
https://github.com/KjellKod/g3log/blob/master/src/g3log/sinkhandle.hpp

To avoid race conditions explicit calls to the sink will return a std::future. 

Other calls, through the LOG API are more of asynchronous nature

**Comment by KjellKod** [comment]
If you want logging files per function or per module then you would have to write that logging sink yourself. 

If you feel that it’s a good contribution, please consider adding it to the community’s contribution of sinks, which can be found at 

https://github.com/KjellKod/g3sinks

You can start with an extending sink, either the default here or some at g3sinks. Writing a sink is really simple - see the docs for it

**Comment by KjellKod** [comment]
From time to time I do take on paid work to help with g3log integration or forked and increased functionality. I haven’t done that though for some time and it’s probably a few $K USD for me to consider it. If that’s of interest you can always email me

**Comment by KjellKod** [comment]
Apart from that G3log is 99% community driven at this point

**Comment by leechangyo** [comment]
thank you so much for your kind answers :)!
