### ISSUE TITLE
No coredump generated for PID1 process on linux

### ISSUE THREAD

**Issue by hoditohod** [KjellKod/g3log#418]
**Describe the bug**
This is linked to #269.

Quick recap of #269: g3log apps fail to exit on crash if they are containerized. They flush the logs (with stacktrace) and hang. Reemitting the fatal signal from the logworker thread doesn't work as the default sigaction for fatal signals sent by other processes is to ignore them in case of PID1 (kernel originating signals work as usual). Because of this execution passes over kill() on https://github.com/KjellKod/g3log/blob/master/src/crashhandler_unix.cpp#L232 and hang in exit(). For non-PID1 processes kill() effectively terminates the process and execution never reaches `exit()`.

In the issue I suggested using `_exit()` instead of `exit()` as it doesn't hang, and you suggested several options, but mostly adding an application side signal handler before g3log is inited. Since `_exit()` was working fine for us, and spared adding a singal handler in each of our applications, we used it for years. No hang occured (yay!), but since Windows was more in focus, we missed an important point: `_exit()` hinders coredump generation.  

So back to the roots. I restored `_exit()` to `exit()` as in stock g3log, and added a custom application defined signal handler for fatal signals (before g3log init). But no matter what I did the application failed to terminate with coredump as PID1. It mostly hung, and in case of `_exit()` in the sighandler the same happened as above: proper exit, but no coredump. I tried numerous combinations of restoring default sigaction, prev-sigaction, no doing anything at all, calling `exit()`; none worked. The application BTW was the most basic logging example, so no special magic was involved. 

The only way I could get this working is to unblock the signal handler on the faulting thread in g3log after the flush is complete. See this commit: https://github.com/GEHC-SimonTemplar/g3log/commit/e86709dd098ee06ca8b927849a448ed91ee77f72

This builds on the existing g3log mechanism that is used on windows, and once in place the application properly exits both in container and as normal process with a proper coredump. No need for adding an application defined signal handler. It doesn't really impact the non-PID1 behavior of g3log, since changing the atomic is after `kill()` which is the last executed statement for non-PID1 processes.

Overall I see this as a cleaner way to exit the application in case of crash (the fault handler is not stuck in an infinite loop), and linux seems to like it better as well. What do you think, should this be included in stock g3log?

**Comment by KjellKod** [comment]
Great explanation, thank you. 
It seems to be a clean approach and from the pointed commit, seems to handle both PID1 and non-PID1. 

yes, this would be great to have added to g3log, please put up a PR for it and we can test it out.

**Comment by KjellKod** [comment]
Solved by https://github.com/KjellKod/g3log/pull/419
