### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by DlubalSmidJaroslav** [KjellKod/g3log#428]
**Describe the bug**
filesinkhelper.ipp, function g3::internal::createLogFile, in the failure cause, unique_ptr::release is called instead of unique_ptr::reset, which leaks the allocated std::ofstream object - release returns the internal pointer and sets unique_ptr to nullptr WITHOUT deleting the object (i.e. transfers ownership).
See [here](https://en.cppreference.com/w/cpp/memory/unique_ptr/release) for reference.

**Comment by KjellKod** [comment]
Good find. In this error case it should of course do `reset`. Please create a pull request that addresses this issue. 

_g3log is community driven_
