### ISSUE TITLE
log file content is null bytes

### ISSUE THREAD

**Issue by zh1an** [KjellKod/g3log#432]
**Describe the bug**
![image](https://user-images.githubusercontent.com/30436038/155670404-c408935f-bd4d-405b-8962-7bf1967cae7f.png)

**To Reproduce**
- What system, compiler etc was used to run this? 
 Windows 10 64Bit msvc 2015 with update
g3log C++11 branch, the latest.
- Is something done differently on your setup than what the documentation specifies?
 None
- Have you provided a code snippet that can be tested?

**Additional context**

**Comment by KjellKod** [comment]
Interesting. Haven’t seen this before. 
My thoughts is that it’s something in the system setup or integration with G3log that is wonky 

some thoughts about what to follow up on. Maybe start with .4 first? 

1. Run all the unit tests and verify they work 
2. Run all the examples and verify they work 
3. Make sure that you have integrated according to the documentation 
4. C++11 seems suspect. I believe G3log is on C++-14/17 so I’m honestly baffled it even compiled. For C++11 please see older released versions
