### ISSUE TITLE
Mac Os stack dump is not correctly demangled because of different format 

### ISSUE THREAD

**Issue by gglowacki** [KjellKod/g3log#461]
https://github.com/KjellKod/g3log/blob/5adecb5ad96b94b426a5d00ca49285ceac973cf0/src/crashhandler_unix.cpp#L160

See https://stackoverflow.com/questions/52693431/backtrace-info-different-on-macos-v-s-linux for an example of mac os vs Linux.

Looking for parenthesis in the string does not work so demangling will also not work.

**Comment by KjellKod** [comment]
Interesting. I don't see a solution in the forum you pointed too however. Just that it's "different" 

G3log is community driven. If you believe you can update it for a better way to handle stackdumps on OSX it would be a great contribution. Please add a pull request and we will review it

**Comment by gglowacki** [comment]
PR for this issue - https://github.com/KjellKod/g3log/pull/473
