### ISSUE TITLE
[Question]Logging to specific sink only

### ISSUE THREAD

**Issue by Marwan-imverse** [KjellKod/g3log#472]
We have a complex software architecture, with multiple modules interacting with each other. I wish to create a sink for each module, so that each has it's own independent log (i.e. logging in it's own file). Just using multiple `logworker->addDefaultLogger()` should be fine, I think.

I just can't figure out how to address a specific sink when logging. What would be the best way to achieve this?

Should I just keep a `sinkHandle `and use `sinkHandle->call(&MyLoggingFunction, message)` instead of the `LOG()` macros?

**Comment by Marwan-imverse** [comment]
I see this has been discussed in #153 and it more or less aligns with what I was thinking. But [this comment](https://github.com/KjellKod/g3log/issues/153#issuecomment-397898355) makes this solution... non optimal.

**Comment by KjellKod** [comment]
The last comment that you mention is regarding what the caveat would be to ignore all of g3log's architecture, threadsafe handling, crash handling and only use a logging sink (no queues or signal handler). 

So yeah. It would be as writing straight to disk

**Comment by KjellKod** [comment]
Usually when I see a request like this I'm thinking that they are logging way too much information 

I've worked on very large server systems and if you aren't conservative on your log usage that can become a performance issue (regardless if G3log or something else is used). 

It's not the answer you are looking for of course. 

As you already see, there are workarounds. All with their own caveats. 

Honestly, I'd suggest to either rethink how you do logging or choose another logger that is better suited for this purpose

**Comment by KjellKod** [comment]
Last comment. 

Please check G3sinks repo 
It has a sink with filtering. I think it can be adjusted fairly easily to use filtering on location instead of levels 

(Of course, you can make custom log levels and do levels that way too "MYMODULE_Warning" level etc)

**Comment by Marwan-imverse** [comment]
Thanks for your answer, but actually going with our own sink with tagged lines in a single file might be ok.

But we're facing another bigger problem (please tell me if I need to open a new issue or rename this one).

Working in Windows, we have a "toolkit" DLL that contains, among other things, the logger. For now, I have a pretty straightforward class.
Header:
```
class IMGTK_API ImLogger
{
public:
  ImLogger();
  ~ImLogger();

  void init(const char* _file_prefix, const char* _folder);

private:
  std::unique_ptr<g3::LogWorker> m_log_worker;
};
```

Implementation:
```
ImLogger::ImLogger() : m_log_worker(g3::LogWorker::createLogWorker()){}
ImLogger::~ImLogger(){}

void ImLogger::init(const char* _file_prefix, const char* _folder)
{
  if (g3::internal::isLoggingInitialized())
    return;

  m_log_worker->addDefaultLogger(_file_prefix, _folder, "imverse");
  g3::initializeLogging(m_log_worker.get());
  LOG(INFO) << "Logging started";
}
```

And, using it from an executable that links with the DLL:
```
ImLogger logger;
IM_CALL(logger.init("test_log", "./"));
LOG(DEBUG) << "Debug Log test";
```
 
 The log file is correctly created, and the first `LOG(INFO)` works as expected. But the `LOG(DEBUG)` line in the exe produces a `LOGGER NOT INITIALIZED` error.

I'm assuming this is because the logger is maintained as a global variable in the DLL's context and does not exist in the exe's context. 

Am I doing something wrong? Is there any way to work around this problem? Is it a design problem?

**Comment by KjellKod** [comment]
I haven't worked much with Windows  but limitations here are  likely due to
limitation with DLLs context. This is a C++ language/Windows-system
limitation, not a g3log issue.

From your description, it sounds like you are initializing and owning the
instance of g3log inside the Windows executable so I'm not sure what's
wrong here unless you are calling it before it's initialized.

My recommendation, as laid out in the docs, is to initialize g3log in the
main() part of the program before setting up other threads and
initialization - i.e. as early as possible.

My understanding is that static instantiations that are internal to g3log
cannot be shared across DLL.
DLL static initialization and destruction are a mess. I've helped one
company to overcome it but I don't think I've access to that solution
anymore. I'll look into my notes tonight and see if I can find what
solution I ended up, that works for that company

**Comment by KjellKod** [comment]
@Marwan-imverse anything else to follow-up on here or can this question be closed?

**Comment by Marwan-imverse** [comment]
I'm sorry to say we finally went with spdlog that implements access to the logger instance differently.

I'll close this question, sorry to have kept it dangling.

**Comment by KjellKod** [comment]
Nothing to be sorry about. I’m glad it’s working out for you Sent from my iPhoneOn Jan 13, 2023, at 1:04 AM, Marwan ***@***.***> wrote:﻿
I'm sorry to say we finally went with spdlog that implements access to the logger instance differently.
I'll close this question, sorry to have kept it dangling.
