### ISSUE TITLE
Supporting MUSL

### ISSUE THREAD

**Issue by clauderobi** [KjellKod/g3log#477]
**Is your feature request related to a problem? Please describe.**
I just need to the support for MUSL in order to run on Alpine Linux. Actually, I need to compile fully static, which glibc can not...

**Describe alternatives you've considered**
I do not see any alternative....unless it is possible to disable the backtrace function. But I could not find anything else this this: ENABLE_FATAL_SIGNALHANDLING: "OFF"m, which I already set to off....

**Additional context**
The source file crashhandler_unix.cpp includes execinfo.h, which simply does not exists in MUSL. Well at least I did not find it in my cross toolchain. And Goolging confirm that musl does not have this support.

PS This post https://github.com/KjellKod/g3log/pull/294#issue-398804307 indicates that musl is supported but does not say how.

**Comment by KjellKod** [comment]
@BenjaminBeichler can you share some insights into the musl build chain? It seems you got it to work previously

**Comment by KjellKod** [comment]
@clauderobi potentially you could have something like this in your source code and it'll just work 

https://github.com/ronchaine/libexecinfo

**Comment by BenjaminBeichler** [comment]
Yes, @KjellKod I used back the days the alpine package libexecinfo-dev to get the relevant header.

**Comment by BenjaminBeichler** [comment]
Maybe you could use some lines with ``CheckIncludeFile`` and emit a message about installing libexecinfo or similar. Or really do a flag, which disables the backtracing. Unfortunately, I'm not able to do a pull-request for this.

**Comment by KjellKod** [comment]
@clauderobi maybe the alpine package or the repo I pointed you to is what you need to move forward. 

I don't see G3log changes needed at this time

**Comment by clauderobi** [comment]
As Kjell, you are quick to reply here!!

I am trying to add the library fro the repo you pointed to. I am able to compile it and generate the .a file I will need to linked with. But I failed at adding the include to g3log. I was expecting that simply adding CMAKE_LIBRARY_PATH would suffice but I get this message while configuring

Manually-specified variables were not used by the project:
  CMAKE_LIBRARY_PATH

I Googled looking for other ways to add custom "system" libraries but did not find much.

**Comment by BenjaminBeichler** [comment]
That's simply not the cmake way of doing this. The variable you mention is to give search paths for ``find_library``. This function will set the given variable to the path of the library you searched for, but for actual linking you need put something like

``target_link_libraries(g3log PRIVATE ${libexecinfo_path}``

after the ``add_subdirectory(g3log)`` in your projects CMakeLists.txt.

**Comment by clauderobi** [comment]
I am just trying to compile g3log. For the final linking with my own stuff, well, I am using make....and I am covered on that front.

So what I am looking for is a way to tell g3log's cmake, which I drive explicitly in my build system, is a way to add another location for looking for includes. I just tested with CMAKE_INCLUDE_PATH without success. (But I do see the correct path in g3log's CMakeCache.txt)

**Comment by BenjaminBeichler** [comment]
Mhh, it's not that easy to do it only by setting cache variables, therefore, I would suggest for your project a very slim CMakeLists.txt doing what you need to change for g3log.

Mixing different build systems is not the easiest thing to do and cmake is not that well prepared for that.

Nonetheless, even if you try to do it with the cache variables, you must not forget about linking the library (and not only adding the header files)

**Comment by clauderobi** [comment]
Well, I made it compile using CMAKE_CXX_FLAGS to add the location of execinfo.h But this is a hack I am not proud of...

I know that I must take care of linking the libexecinfo lib, but that is the easy part. I do that for all the 3rd party libraries I use (and precompile before into .a files).

**Comment by clauderobi** [comment]
Just to confirm that I was able to use libexecinfo, musl and produce a fully static linked binary. Now, does it *ALWAYS* work remains to be seen. But that is definitely outside g3log's realm.

**Comment by clauderobi** [comment]
Specifically for linexecinfo, the main things are
- look at the Makeifle it provides; as it is, the native platform compiler is used. Since I was cross-compiling and already setting CC (and AR) all I add to do is comment out the same in its Makefile
- Hopefully the crosstool-ng guys will be able to pullin this libexecinfo. 

Beside this, my main take away has nothing to do with g3log, musl or even cross compiling. Behind the scene, cmake builds executables (lots of them) and even though you setup cmake for generating static libraries it still needs the dynamic libraries (for the libraries that a project or a library depends on) in order for the small test executable to be produced.
