### ISSUE TITLE
[Question] What is the best way to condition based on LogLevel in a sink?

### ISSUE THREAD

**Issue by broken** [KjellKod/g3log#485]
I have a simple sink which performs different actions based on the severity of the log level.

```
class StdoutFileSink : public g3::FileSink {
public:
  StdoutFileSink(const std::string &log_prefix, const std::string &log_directory, const std::string &logger_id="g3log")
  : g3::FileSink(log_prefix, log_directory, logger_id) { }

  void log(g3::LogMessageMover msg) {
    if (msg.get().wasFatal() || !msg.get().level().compare(WARNING.text)) {
      std::cerr << msg.get().toString() << std::endl;
      fileWrite(msg);
    } else {
      std::cout << msg.get().toString() << std::endl;
    }
  }
};
```

Is there a better way to conditionalize on the log level? I would prefer to be able to make use of the value of the log level rather than string matching, something along the lines of `if (msg.get().level().value >= WARNING.value)`, but it doesn't look like this is available with the current API. Is this correct, or did I overlook a more canonical approach?

**Comment by KjellKod** [comment]
https://github.com/KjellKod/g3log/blob/master/src/g3log/loglevels.hpp

The log levels is a plain struct so you can access the value

**Comment by broken** [comment]
Right, but I was referring to how to access the level from the message. I completely overlooked that `_level` is not actually private last night. So `if (msg.get()._level.value >= WARNING.value)` works.

**Comment by KjellKod** [comment]
It should work. Since it's a POD there aren't functions around it.
