### ISSUE TITLE
CMake not generating install project

### ISSUE THREAD

**Issue by sbrkopac** [KjellKod/g3log#49]
When I generate visual studio project files I'm not seeing a install project getting generated. The library will build but I can't "install" it.

**Comment by KjellKod** [comment]
That's correct.  As of now g3log install packages are experimental. I've tried it, with success on Linux but for Windows, for now, g3log has to be incorporated in your code base or you have to install it yourself. 

Since Windows is not my number 1 platform I will not fix this myself.  I will mark this as "need help" and if you have a resolution for it then please submit a pull request.

**Comment by sbrkopac** [comment]
Do you have any experimental packages that were for windows that I could use as a starting base? I can take a crack at the install packages for windows.

**Comment by KjellKod** [comment]
Take a look at  https://github.com/KjellKod/g3log/blob/master/CPackLists.txt and how it is used. 

There should be information what to do for Windows and CPackLists but I have not dug into it.

**Comment by duedal** [comment]
For Linux and OS X it would be nice to get rudimentary install target support, so we can do `make install`, without hacking the CMakeLists.txt.
Also requested by homebrew: https://github.com/Homebrew/homebrew/pull/48318

**Comment by KjellKod** [comment]
Agreed. Great suggestion. It's started in the cpackage part but it's in beta stage and only tested on Linux.

The best way to promote this is to do a pull request

**Comment by duedal** [comment]
I've added a basic install target. Eventually it would be nice to do some cleanup of the CMake definitions, and add continuous integration, ie. Travis-CI.org so we get automated testing.

**Comment by KjellKod** [comment]
1. Linux install implemented by duedal and merged
2. OSX not yet started
3. Windows not yet started

**Comment by KjellKod** [comment]
Linux install done
OSX install exists through brew
Windows: not yet started

**Comment by AndreasSchoenle** [comment]
Among a few other cmake things, this is part of pull request #135. Starting from there it would of course be nice to also have install(EXPORT ...) called to have a cmake script for properly importing the installed targets.

**Comment by KjellKod** [comment]
too old but at least partial improvement.
