### ISSUE TITLE
CString’s are printed wrong

### ISSUE THREAD

**Issue by alex0598** [KjellKod/g3log#497]
**Describe the bug**
A CString string is always printed only with the first char.  Conversion to LPCTSTR has the same effect.

**To Reproduce**
- Windows C++17 v142
- Just print a CString

**Comment by KjellKod** [comment]
Not sure what you mean with CString 

Please provide a code example

**Comment by KjellKod** [comment]
I see. 

This is not supported. Please see the documentation for how to use G3log 

Stick to standard C++ and not OS specifics string handling and it'll work
