### ISSUE TITLE
API.md documentation out of date after PR #471

### ISSUE THREAD

**Issue by ethanhschwartz** [KjellKod/g3log#498]
**Describe the bug**

docs/API.md says:

```
The default file sink will flush each log entry as it comes in.
```

However PR #471 changed the behavior of the default FileSink so it only flushes every 100 log entries.  As a user I was confused by this because it looked like logs weren't getting flushed at all until my program exited and I didn't know about the new buffering behavior.  Probably the docs should be updated.

**Comment by KjellKod** [comment]
Good catch. This will correct it. https://github.com/KjellKod/g3log/pull/499
