### ISSUE TITLE
Is g3log compatible with C++ 14 or C++ 17

### ISSUE THREAD

**Issue by wluter** [KjellKod/g3log#501]
The home page for g3log says "G3log is made with plain C++14 (C++11 support" but it calls the template function std::invoke_result_t which is available only from c++ 17.

I am having difficulty compiling it with an MFC application due to version compatibility problems.

**Comment by KjellKod** [comment]
Hi. Thanks for calling that out. I need to clear that up in the documentation 

Please check the release information for the last release that supported C++14

**Comment by wluter** [comment]
Thanks for the quick response

**Comment by wluter** [comment]
I took a look at updating and submit PR but wasn't sure how to change the web page where the error is.

**Comment by KjellKod** [comment]
That’s just one of the markdown files. You can use the search to find it Sent from my iPhoneOn Sep 11, 2023, at 13:41, wluter ***@***.***> wrote:﻿
I took a look at updating and submit PR but wasn't sure how to change the web page where the error is.

**Comment by wluter** [comment]
I have searched through every .md document and also performed a general search for “C++14” and “About” and I must be dumb. I cannot find the “About” abstract on the code tab:
***@***.***

Regards,
Bill

**Comment by KjellKod** [comment]
completed in https://github.com/KjellKod/g3log/pull/502

**Comment by KjellKod** [comment]
@wluter I can recommend [githelpers](https://github.com/nbroslawsky/githelpers) as a much nicer way to search in git repos, alternatively, just looking at their aliases and use something similar
