### ISSUE TITLE
Incorrect code to detect MSVC

### ISSUE THREAD

**Issue by kroeckx** [KjellKod/g3log#531]
At https://github.com/KjellKod/g3log/blob/c1dd801e4213ab46ac6c648d2e3d464ce4dd13e5/src/logcapture.cpp#L88 and https://github.com/KjellKod/g3log/blob/c1dd801e4213ab46ac6c648d2e3d464ce4dd13e5/src/logcapture.cpp#L98 you seem to try to detect using Microsoft Visual Studio. However, the code as written also used the MSVC code path for other environments. I suggest you use the _MSC_VER define instead to detect it.

**Comment by KjellKod** [comment]
https://github.com/KjellKod/g3log/pull/534/files tried this quickly but since I don't have Microsoft OS at home and can only run this through the github actions CI toolchain I'm not planning to troubleshoot it further. 

If you have this OS and this is an issue for you then put up a pull request.

**Comment by KjellKod** [comment]
The code is correct, although I agree it could be cleaned up. With the above information I am closing this issue. 
If you feel that cleaning up this statement is of interest to you then you have the opportunity to do so.
