### ISSUE TITLE
sizeof() on pointer instead of strlen()

### ISSUE THREAD

**Issue by kroeckx** [KjellKod/g3log#532]
At https://github.com/KjellKod/g3log/blob/c1dd801e4213ab46ac6c648d2e3d464ce4dd13e5/src/logcapture.cpp#L91 you seem to want to check the size of a message. But since finished_message is either a `char *` or `char []`, you're getting the size of a pointer, which is probably not what you want. I suspect you want to do strlen() instead.

**Comment by KjellKod** [comment]
Good catch, lease put up a pull request so we can review it

**Comment by KjellKod** [comment]
Hi @kroeckx I throught about this for more than a second and can confirm that the code is correct as it is. 

here's a test snipped you can try to run to verify this for yourself. 
```
#include <iostream>
using namespace std;
 
int main() {
	char finished_message[123];
    size_t finished_message_len = sizeof(finished_message); // Correct for static arrays
    std::cout << "Message length: " << finished_message_len << std::endl; /// output gives 123
	return 0;
}
```

Thanks through for reviewing the code even if it this time wasn't an accurate call out.

**Comment by KjellKod** [comment]
FYI, I can understand the confusion however as if you don't pay attention to the ugly #ifdef handling you might believe that the `int finished_message_len = sizeof(finished_message);` can refer to a dynamic sized array. If you look at the #ifdef's you see that it only handles the situation when `G3_DYNAMIC_MAX_MESSAGE_SIZE` is set to false.
