### ISSUE TITLE
shared_queue consuming higher memory 

### ISSUE THREAD

**Issue by nand2023** [KjellKod/g3log#540]
**Describe the bug**
We have 5 Sink objects and our application is crashing due to out of memory. The shared_queue shows count around 131071 in the crash dump. We are on 2.4 version of g3log.

- Windows 10, Visual Studio 22, C++ 17, build x86

![shared_queue_size](https://github.com/user-attachments/assets/c35d0767-c3e7-4e85-8d4b-fd59665934ef)

Is this a bug or bad configuration please suggested?

**Comment by KjellKod** [comment]
While there are custom setups out there that have restrictions of the queues usage the default is that it doesn't restrict 

It does seem to be a lot of objects in the queue. 

There's lots of unknowns here 
1. What type of logging philosophy is followed -- is this a case of logging too much and simply overwhelming the system? 

2. 5 sinks is more than I typically see, I'm assuming these are custom sinks. What type and what differences are there between the sinks 

3. Have you diagnosed them to make sure none of them is blocked? A blocked sink, or a sink moving slow in a situation where logs aren't restrictive and its full throttle will lead to a continuously growing queue.

**Comment by nand2023** [comment]
Thank you very much for your prompt response. I apologize for the delayed reply on my part.

1. Not exactly; we're simply pushing data to the G3Log queue with a specific delay, and we use our own wrapper class for this purpose.  
2. Our use case involves five different sinks, each logging to a separate custom file, with the files being archived once a certain count threshold is reached.  
3. We discovered this in the crash dump but did not find any blocked threads.

**Comment by KjellKod** [comment]
Hi @nand2023  since you closed it, I figure it's resolved. 

it would be great if you could share the root cause in case other people run into some similar scenario in the future.

**Comment by nand2023** [comment]
Hi @KjellKod We are continuing our investigation into this issue and have not yet identified the resource-intensive module in our project.

The reasons for considering this bug resolved are as follows:
1. Based on your observation, the custom sinks might be the root cause in our case, which seems valid. We are further exploring this possibility.
2. Given the queue count of 131,071, and assuming a maximum log data size of 300 bytes, the total size amounts to approximately 40 MB. This suggests that another component may be consuming the remaining process memory.

If we identify a bug in the G3Log code, we will certainly share a patch.

Thank you for your insights and support.
