### ISSUE TITLE
G3_DYNAMIC_LOGGING and MSVC compilation fail

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3log#62]
It seems that msvc 2013 does not like the operator =

    internal::g_log_level_status = {{g3::kDebugVaulue, true}, {INFO.value, true}, {WARNING.value, true}, {FATAL.value, true}};

Can easily fix it by going back to insert... or by

    internal::g_log_level_status = std::map<int, atomicbool>{{g3::kDebugVaulue, true}, { INFO.value, true }, { WARNING.value, true }, { FATAL.value, true }};

All good in 2015

**Comment by KjellKod** [comment]
sounds good. Can you please move that to a pull request?

**Comment by KjellKod** [comment]
closed with pull request https://github.com/KjellKod/g3log/pull/63
