### ISSUE TITLE
Multiple levels of DEBUG logs

### ISSUE THREAD

**Issue by aloukissas** [KjellKod/g3log#70]
This could be very similar to the VLOG(x) macros in google-glog. For those not familiar, this translates to having a global verbosity level (e.g. with levels 0-5), which is modifiable at runtime, and logs everything from the current set level and below. For instance, when the verbosity level is set at 2, VLOG(0-2) will be logged and VLOG(3-5) will not.

In a project I'm working on, we've utilized this to approximate the "per-class" or the "per-module" logging, which I noticed is another feature request for g3log.

**Comment by KjellKod** [comment]
@aloukissas do you know about the custom logging levels in g3log? 
And that logging levels can be turned on/off at runtime?

I.e you can create your own logging levels say
ALOUKISSAS_1
ALOUKISSAS_2
etc

At runtime they would by default be disabled (if dynamic logging levels is enabled)
 but can be enabled with
`g3::only_change_at_initialization::setLogLevel(ALOUKISSAS_2, true)`

Please see
src/g3log/LogLevels.hpp and test/test_io.cpp for usage 

@aloukissas, would this satisfy what you are looking for?

**Comment by KjellKod** [comment]
Close due to lack of activity and non responsiveness from https://github.com/aloukissas
