### ISSUE TITLE
unresolved symbol (stacktrace_windows.obj)

### ISSUE THREAD

**Issue by Mellnik** [KjellKod/g3log#71]
^Get this message after compiling and linking to my project.

Build Command X64 VS12 Shell:
``cmake -DCMAKE_BUILD=Release -G "Visual Studio 12 Win64" .``
``msbuild g3log.sln /p:Configuration=Release`` 

I am linking g3logger.lib in my project. What's the cause?

**Comment by KjellKod** [comment]
Most likely it's due to that it does not have the symbol library.

By default that is generated when building in Debug

When building in Release you have to set that up yourself in Visual Studio. So far I have not found a way to generate the symbol library using cmake

**Comment by Mellnik** [comment]
Oh ok, added DbgHelp.lib to my project then.

**Comment by KjellKod** [comment]
Does it work?

**Comment by Mellnik** [comment]
Yes, without errors.
