### ISSUE TITLE
g3log is much faster with G3_DYNAMIC_LOGGING

### ISSUE THREAD

**Issue by wonder-mice** [KjellKod/g3log#73]
Hi, I' measuring performance of different logging libraries with null-sink (to exclude IO overhead). While doing that, I found that g3log library is much faster when built with `-DUSE_DYNAMIC_LOGGING_LEVELS:bool=ON`.

Results **without** G3_DYNAMIC_LOGGING:

|                                |  Easylogging++  |    g3log    |     glog    |     spdlog    |      zf_log     |
| ------------------------------ | ---------------:| -----------:| -----------:| -------------:| ---------------:|
|  Call site size: string        |          304 B  |      384 B  |      160 B  |        352 B  |         **48 B**|
|  Call site size: 3 integers    |          856 B  |      392 B  |      320 B  |        312 B  |         **72 B**|
|  Executable size: 1 module     |      208.84 KB  |  178.94 KB  |  137.37 KB  |    133.69 KB  |     **18.33 KB**|
|  Module compile time           |      7.066 sec  |  0.914 sec  |  0.632 sec  |    5.125 sec  |    **0.029 sec**|
|  Executable link time          |    **0.034 sec**|  0.043 sec  |  0.045 sec  |    0.039 sec  |    **0.029 sec**|
|  Speed: 1 threads, string      |        410,725  |    401,891  |    402,970  |    2,040,505  |    **5,353,777**|
|  Speed: 1 threads, 3 integers  |        315,130  |    504,637  |    332,237  |    1,327,384  |    **3,139,682**|
|  Speed: 1 threads, fmti-off    |      3,336,611  |    225,285  |    313,838  |   66,931,871  |  **501,996,937**|
|  Speed: 4 threads, string      |        127,895  |    137,740  |    196,734  |      196,566  |    **9,028,591**|
|  Speed: 4 threads, 3 integers  |        110,711  |    134,843  |    203,563  |      181,888  |    **4,787,315**|
|  Speed: 4 threads, fmti-off    |        231,895  |    128,444  |    232,791  |  108,821,120  |**1,122,918,236**|

Results **with** G3_DYNAMIC_LOGGING:

|                                |  Easylogging++  |    g3log     |     glog    |    spdlog    |     zf_log    |
| ------------------------------ | ---------------:| ------------:| -----------:| ------------:| -------------:|
|  Call site size: string        |          304 B  |       360 B  |      160 B  |       352 B  |       **48 B**|
|  Call site size: 3 integers    |          856 B  |       384 B  |      320 B  |       312 B  |       **72 B**|
|  Executable size: 1 module     |      208.84 KB  |   183.73 KB  |  137.37 KB  |   133.69 KB  |   **18.33 KB**|
|  Module compile time           |      8.867 sec  |   1.330 sec  |  0.736 sec  |   5.965 sec  |  **0.035 sec**|
|  Executable link time          |    **0.038 sec**| **0.039 sec**|**0.037 sec**|   0.043 sec  |  **0.034 sec**|
|  Speed: 1 threads, string      |        390,720  |   1,186,287  |    391,711  |   1,771,734  |  **4,361,606**|
|  Speed: 1 threads, 3 integers  |        315,744  |   1,050,792  |    308,528  |   1,227,801  |  **2,837,152**|
|  Speed: 1 threads, fmti-off    |      4,273,666  |  59,134,081  |    323,128  |  44,458,644  |**463,829,585**|
|  Speed: 4 threads, string      |        109,407  |   1,708,094  |    197,924  |     229,861  |  **7,640,825**|
|  Speed: 4 threads, 3 integers  |        112,646  |   1,182,649  |    210,790  |     253,685  |  **3,968,987**|
|  Speed: 4 threads, fmti-off    |        212,187  |  77,160,921  |    223,495  |  95,371,758  |**783,723,842**|

Am I doing something wrong? I would expect it to be faster without that option. Why it's not a default then? Source code for my tests could be found [here](https://github.com/wonder-mice/zf_log/blob/master/tests/perf/test_switch.h#L160).

**Comment by ctapmex** [comment]
if you define
```c
#ifdef TEST_LOG_OFF
		#define _XLOG_INIT_LEVEL() \
			g3::only_change_at_initialization::setLogLevel(INFO, false)
```
then extra work is not done.
also I noticed this in own project

**Comment by wonder-mice** [comment]
Thanks for attention to this issue, ctapmex. The line you referring to is specifically there to test performance of a case when particular log level was turned off.

However, I observed increased performance in both cases - when INFO level is ON and OFF.
From my tables:
Speed: 1 threads, string: 401,891 (**no** G3_DYNAMIC_LOGGING)
Speed: 1 threads, string: 1,186,287 (G3_DYNAMIC_LOGGING)
Speed: 1 threads, fmti-off: 225,285 (**no** G3_DYNAMIC_LOGGING)
Speed: 1 threads, fmti-off: 59,134,081 (G3_DYNAMIC_LOGGING)

Note: "fmti-off" means that INFO log level was turned off.

**Comment by KjellKod** [comment]
Hi @wonder-mice 

I'm just speculating here but...
It might be an artifact of your hardware platform. With all threads on the same CPU socket the atomic communication is cheap but will add enough let-off to minimize the mutex overhead on the shared_queue

On another system, say with 2 sockets and the threads are on both sockets the atomic synchronized communication will be much more expensive

**Comment by wonder-mice** [comment]
Ok, nothing better to do than close this one then.
