### ISSUE TITLE
make the .g3log in the log filename optional

### ISSUE THREAD

**Issue by jkhoogland** [KjellKod/g3log#75]
Hi,
it would be nice if the ".g3log" added to the log filename is made optional

https://github.com/KjellKod/g3log/blob/master/src/filesinkhelper.ipp#L90

Any reason that is not possible ?
Thanks
Jiri

**Comment by KjellKod** [comment]
Sounds like a fine idea.
You can make it an API change so people can choose whatever they want. 

Will you put up a pull request?

**Comment by jkhoogland** [comment]
Added a pull request.
Cheers
Jiri

**Comment by KjellKod** [comment]
fixed in: https://github.com/KjellKod/g3log/pull/76 which was later replaced by https://github.com/KjellKod/g3log/pull/82/files?w=1
