### ISSUE TITLE
Redirect g3log to standard streams 

### ISSUE THREAD

**Issue by agirault** [KjellKod/g3log#85]
Hello,

I just started using `g3log` for a medical simulation toolkit which handles multiple threads for visualisation, external device clients, simulation loop etc. It looks like g3log is handling the job perfectly so far.

However, it is convenient to visualise the log on the fly (in terminal or IDE) for debug purposes, so I was wondering if there was a way to easily redirect LOG(INFO/DEBUG) to `std::cout `and LOG(WARNING/FATAL) to `std::cerr`.

The best would actually be to get both: display in standard output on the fly and log stored in the g3log log file with Data and Level information.

Is this an existing feature?

Thanks

**Comment by KjellKod** [comment]
It is through the "add sinks" feature. A simple sink can be as easy as wrapper to cout/cerr.

Here's an example of doing just that but using colored output depending on logging level

https://github.com/KjellKod/g3sinks/tree/master/snippets

**Comment by agirault** [comment]
Thank you, that's exactly what I needed.
I used this to only display the message of the logEntry in cout/cerr, and keep the full logEntry in my file sink.
