### ISSUE TITLE
How do i wait an application when all consumed for log messages?

### ISSUE THREAD

**Issue by jhlee8804** [KjellKod/g3log#88]
Hi, 

I want to wait application until logger save all log messages,
How do i have??

Thanks.

**Comment by KjellKod** [comment]
Not sure I understand. 

Do you want to wait with shutting down the application until the logger has written all log messages to disk?

That should happen automatically unless you kill your process with an "exit" call or similar.

Feel free to write a snippet of code to illustrate what the issue is.

**Comment by KjellKod** [comment]
Closing this due to lack of response

**Comment by jhlee8804** [comment]
Sorry for delay and don't speak english well.
Your speaking is correct and follow link is too.
https://github.com/KjellKod/g3log/issues/91

Here is my code.
```
namespace {
static std::once_flag g_initLogger;
static std::unique_ptr<g3::LogWorker> g_logger;
static std::unique_ptr<g3::FileSinkHandle> g_loggerHandle;
} // namespace

void InitializeLogging(const std::string& logPrefix, const FilePath& logDir, bool timed) {
  std::call_once(g_initLogger, [&]{
    if (!DirectoryExists(logDir))
      CreateDirectory(logDir);

    std::string logPath = SysWideToNativeMB(logDir.AsUTF16Unsafe());
    g_logger = g3::LogWorker::createLogWorker();
    g_loggerHandle = g_logger->addDefaultLogger(logPrefix, logPath, timed);
    g3::initializeLogging(g_logger.get());
  });
}

bool IsLoggerEnabled() {
  return g3::internal::isLoggingInitialized();
}

void ShutdownLogging() {
  g3::internal::shutDownLogging();
  g_logger.reset();
}
```

and used them
```
BOOL MFCSample::InitInstance() {
  // ....
  InitializeLogging(L"MFCSample", "some_path", true);
}

int MFCSample::ExitInstance() {
  ShutdownLogging();
  return CWinAppEx::ExitInstance();
}
```

**Comment by KjellKod** [comment]
Thanks jhlee8804, this will be useful I hope for https://github.com/KjellKod/g3log/issues/91

**Comment by KjellKod** [comment]
I will add your example to the Wiki I think if that's OK with you?

**Comment by KjellKod** [comment]
FYI: 

The g_logger.reset() is the only thing you need to do when shutting down.

Internally the destructor will call g3::internal::shutDownLogging();

**Comment by jhlee8804** [comment]
OK, I will try it.
