### ISSUE TITLE
timestamp logs misleading

### ISSUE THREAD

**Issue by BobIV** [KjellKod/g3log#9]
When the log details are generated in g2logmessage.cpp, it creates the following output:

2015/03/12 14:21:43.27000	INFO [processframework.cpp L: 138]	"IPAddress read: 127.0.0.1"

Reading the timestamp and a high level view of the source code, I interpret the timestamp as:

year/month/day hour:min:sec.microsecond   ....

From a single log entry it is not clear that the microsecond counter starts at the time g3log was initialized and counts up from there.

When using these log statements, the microsecond portion of the timestamp should be extracted from the rest of the timestamp for use in any sort of measurements.

I think it is best to separate these two components of the time stamp to highlight that they should not be interpreted as a fraction of the seconds from the system time seconds.

**Comment by KjellKod** [comment]
Unfortunately this is a c-library issue. 
The finest granularity you get on ```std::time_t``` is seconds.  To be able to differentiate between the entries that end up in the same second timeframe it is handy to have the microseconds counter. 

I'm closing this since it's a c-library limitation and not a g3log bug. 

Feel free to do a pull request in case you come up with a great way of solving this.

**Comment by BobIV** [comment]
It's not the granularity that is the issue. It's the concatenation of the two numbers that creates inaccurate numbers. 

<div>-------- Original message --------</div><div>From: Kjell Hedstrom <notifications@github.com> </div><div>Date:05/14/2015  3:56 PM  (GMT-05:00) </div><div>To: KjellKod/g3log <g3log@noreply.github.com> </div><div>Cc: BobIV <bobflynn4@comcast.net> </div><div>Subject: Re: [g3log] timestamp logs misleading (#9) </div><div>
</div>Unfortunately this is a c-library issue. 
The finest granularity you get on std::time_t is seconds. To be able to differentiate between the entries that end up in the same second timeframe it is handy to have the microseconds counter.

I'm closing this since it's a c-library limitation and not a g3log bug.

Feel free to do a pull request in case you come up with a great way of solving this.

**Comment by KjellKod** [comment]
It can be easily changed to whatever formatting you like. 

g3log was made to support custom sinks. What formatting and how to output the logs can be done from a custom sink. Adding a custom sink is very easy. Please see the unit tests as well as the README for this repo: https://github.com/KjellKod/g3log


If you want to achieve custom formatting using your own sink, then you should choose to have the log receiving function receive a ```g2::LogMessageMover``` message instead of a ```std::string```. This way you can do your own formatting on the log output. 


For how to use your own custom time formatting, please see
src/g2time.hpp/cpp 
```std::string localtime_formatted(const std::time_t& time_snapshot, const std::string& time_format) ;```
src/g2filesink.hpp/cpp ::```changeLogFile()```  
src/g2filesinkhelper.hpp/cpp (more examples here)

**Comment by BobIV** [comment]
Your code is very well done and straight forward to customize, you did a great job.  

This particular topic was a slight problem that had a significant impact to some work I was  doing. I felt the need to share the issue, but I think I am having trouble making my point clear. 

I would like to continue to try to explain this issue, but will refrain from continuing this thread unless you are interested. 

Your utilities are quite useful, and your efforts are appreciated. 

Thanks 
Bob 

<div>-------- Original message --------</div><div>From: Kjell Hedstrom <notifications@github.com> </div><div>Date:05/14/2015  4:54 PM  (GMT-05:00) </div><div>To: KjellKod/g3log <g3log@noreply.github.com> </div><div>Cc: BobIV <bobflynn4@comcast.net> </div><div>Subject: Re: [g3log] timestamp logs misleading (#9) </div><div>
</div>It can be easily changed to whatever formatting you like.

g3log was made to support custom sinks. What formatting and how to output the logs can be done from a custom sink. Adding a custom sink is very easy. Please see the unit tests as well as the README for this repo: https://github.com/KjellKod/g3log

If you want to achieve custom formatting using your own sink, then you should choose to have the log receiving function receive a g2::LogMessageMover message instead of a std::string. This way you can do your own formatting on the log output.

For how to use your own custom time formatting, please see
src/g2time.hpp/cpp 
std::string localtime_formatted(const std::time_t& time_snapshot, const std::string& time_format) ;
src/g2filesink.hpp/cpp ::changeLogFile()

src/g2filesinkhelper.hpp/cpp (more examples here)

**Comment by KjellKod** [comment]
Feedback is always welcome

Feel free if you want to contact me off line. Hedstrom at kjellkod dot cc

**Comment by KjellKod** [comment]
Fixed in https://github.com/KjellKod/g3log/pull/16

**Comment by KjellKod** [comment]
@BobIV true timestamp and not just a time counter is addressed in this pull request: https://github.com/KjellKod/g3log/pull/104

It gives the user/sink the option of using millisecond, microsecond or nanosecond as a true timestamp. The default will be microseconds. 

So far it is implemented for OSX and Linux. The pull request will only be merged when it is fixed for Windows also.  For OSX and Windows the granularity is so far not as great as nanosecond.
