### ISSUE TITLE
g3log does not flush on terminate

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3log#91]
It seems that I am never getting the final shutdown time in the log.
What I get is
g3log file shutdown at: 
I saw that If I force a crash then it is written correctly.
g3log file shutdown at: 11:36:27

Have not investigated as to why it happens but thought of putting it up here till I have the time to do so.
I think it is also worth changing so it also writes the date.

Note that this could be related to the fact that I had to do acrobatics in an MFC app where there is no main and thus had to have  a global variable
auto worker = g3::LogWorker::createLogWorker();

**Comment by KjellKod** [comment]
In this case you have to make sure that the worker is destroyed before you exit.

How /where do you create the worker now?
In the MFC WinMain() function?

Do you have an exit handler that can trigger the destruction of the worker? I.e MFC ExitInstance() overloading. 
https://msdn.microsoft.com/en-us/library/e4zc2h84.aspx

How is the process exiting? What triggers it to exit?

**Comment by KjellKod** [comment]
Please see the code example provided by @jhlee8804 https://github.com/KjellKod/g3log/issues/88#issuecomment-219030139

**Comment by cstamatopoulos** [comment]
Will test it soon.
I am doing the same thing except for resetting the logger which destroys
the worker as you proposed.

**Comment by KjellKod** [comment]
OK. The important thing is to destroy the worker. In the example provided by @jhlee8804 g_logger.reset() is the only thing you need to do when shutting down.

Internally the destructor will call g3::internal::shutDownLogging();
It is not that call but the actual destructor that will make sure that all internal queues till that point are flushed to the logging sinks before exiting.

Ref:
![image](https://cloud.githubusercontent.com/assets/331742/15248575/35c90226-18d8-11e6-92ff-f894f48df1b2.jpeg)

**Comment by cstamatopoulos** [comment]
Resetting the logger does the trick
