### ISSUE TITLE
A way to flush the log manually

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3log#92]
I am not sure if that is possible or make sense due to the asynchronous nature but consider this.
When the app offers a GUI you can offer to submit a log for debugging.
In that case I want to flush the file to disk so that I know that everything is up to date.

PS. Note that the Logrotate class offer a flush() function but from what I have seen it is not really flushed.

**Comment by KjellKod** [comment]
Check the unit tests for it. It should work

**Comment by cstamatopoulos** [comment]
The tests are definitely passing yet for my case it fails, will have to find why it happens.

It would be nice if the worker could just flush all instead of doing it through the logrotate.
No big deal feel free to close it.

**Comment by cstamatopoulos** [comment]
I think the unit test is not ideal since it never fails even without the flush.
Even with a 2Mbyte entry in the log file and checking the last line it is all good

Yet if you do what I do, that is use the file itself it fails.
Not sure if you have the <filesystem> stuff but I think you should... so if you do even after a flush

```
namespace fs = std::tr2::sys;
auto filesize = [&](const std::string& filename)
{
	std::ifstream in(filename, std::ifstream::ate | std::ifstream::binary);
	return in.tellg();
};

fs::copy_file(logfilename, "test2.log", fs::copy_options::overwrite_existing);
bool checkfilesize = filesize(logfilename) == filesize("test2.log");
```
the checkfilesize fails. I should add it as a test case.

This does not belong here of course as I was just after a method to flush all sinks in the disk if needed.

**Comment by cstamatopoulos** [comment]
that exaplins my issues
From the C++ runtime's point of view, it should have been written to disk. From an OS perspective it might still linger in a buffer, but that's only going to be an issue if your whole machine crashes.

Then I also found this
https://support.microsoft.com/en-us/kb/148505
It has a way to force the OS to flush

**Comment by KjellKod** [comment]
@cstamatopoulos please consider using https://github.com/KjellKod/g3sinks/blob/master/logrotate/src/g3sinks/LogRotate.h instead since that has flushing policy built in.

**Comment by KjellKod** [comment]
Closing this since I is tested with flushing policy to work on at least OSX and Linux, ref: https://github.com/KjellKod/g3sinks/blob/master/logrotate/src/g3sinks/LogRotate.h
