### ISSUE TITLE
Support for Xenomai3?

### ISSUE THREAD

**Issue by will2142** [KjellKod/g3log#95]
We've recently ported our project to Xenomai3 and we're having problems using g3log.  I think it probably has to do with g3log's use of std::thread and std::mutex instead of the pthread variants.  

Do you have a sense of how difficult it would be for me to switch to using all pthread calls?

Thanks.
Will

**Comment by KjellKod** [comment]
Good question. If you don't have full c++11 support then you might want to consider using g2log instead.

That one is pretty frequently ported to just using pthreads and posix

**Comment by KjellKod** [comment]
This is the reply I gave to another user who asked

```
I would like to use g3logger but I am stuck in ancient compiler environment,
 the old sun compiler on Solaris 10. This is C++98 and unfortunately this is 
not going to change. So I was wondering, would you consider making 
g3logger available for C++98 compilers?
```

My reply was 
-->

> G3log,  and G3sinks are commonly using some of the latest language features in C++11 and now moving towards C++14. 
> 
>  For older compilers I recommend using g2log instead. If C++11 is not available then it is not a big deal to remove the C++11 features and replacing them for pthread, posix equivalents or similar functionality accessible in other libraries. 
> 
> You can find g2log here  https://bitbucket.org/KjellKod/g2log
> 
> A slightly modified version (more C++11 stuff) can be found here: https://bitbucket.org/KjellKod/g2log-dev
> An even more modified version, which relies on boost, and has natively log rotation (which otherwise can be used in g3log + g3sinks) can be found here: https://bitbucket.org/vrecan/g2log-dev
> 
> 
> There are several versions of g2log existing without C++11 and instead using Qt, pthread, boost or similar. Unfortunately I do not have any repository that I can point you to since the developers that did that transformation chose to not reveal the repo's location, or kept it private :(
> 
> The process is fairly straightforward though. I might have forgotten something but in short details you should look at: 
> The active.h/cpp is using some C++11 constructs as well as shared_queue.h all these should be replaceable for similar versions in the libraries I mentioned above.
> 
> g2future and logworker is using a std::future. To just get going I would suggest to just remove the std::future parts. Comment them out. Once all the rest is working you can always work with enabling them again using whatever favorite or available C++ library that will do the trick for you. 
> 
> Let me know how it goes, 
> Cheers
> Kjell

**Comment by will2142** [comment]
Thanks Kjell,

I'll look into this.  We're using gcc, so we do have access to C++11 constructs, but the threading and concurrency appears to need to use the pthread api.

**Comment by KjellKod** [comment]
@will2142 I'm leaving this one open for a bit longer. Let me know if you have any questions that I can help you out with.

**Comment by KjellKod** [comment]
@will2142 any new status here? Should I close this?

**Comment by will2142** [comment]
Thanks @KjellKod. 

We may have a solution that doesn't require any code changes to g3log.  If we're successful, I'll update with details.

**Comment by will2142** [comment]
@KjellKod I'm going to close this issue for now.  I'll update you if/when we have a solution.
