### ISSUE TITLE
ExternalProject_Add fail on Windows with MinGW

### ISSUE THREAD

**Issue by LePelicaN** [KjellKod/g3log#97]
Hello,

I'm using g3log for logging purpose on Linux and it works great.
This week, I start a new Windows project with Qt (MinGW version) and I tried to use the same cmake project skeleton but I've got link errors on DbgHelp functions:
```
../ext/g3log/g3logger/src/project_g3log-build/libg3logger.a(stacktrace_windows.cpp.obj):stacktrace_windows.cpp:(.text+0x8e): undefined reference to '_imp__SymCleanup@4'
../ext/g3log/g3logger/src/project_g3log-build/libg3logger.a(stacktrace_windows.cpp.obj):stacktrace_windows.cpp:(.text+0x4d1): undefined reference to '_imp__SymFromAddr@20'
../ext/g3log/g3logger/src/project_g3log-build/libg3logger.a(stacktrace_windows.cpp.obj):stacktrace_windows.cpp:(.text+0x586): undefined reference to '_imp__SymGetLineFromAddr64@20'
[...]
```

I tried compiling the g3log project alone and succeed without any issue so I'm wondering if I'm doing something wrong or if I'm missing something.

I'm using CMake for my project.
The root CMakeLists.txt only mention a g3log subdirectory:
```
ADD_SUBDIRECTORY(ext/g3log)
```

And here is the full CMakeLists.txt of this subdirectory:
```
CMAKE_MINIMUM_REQUIRED(VERSION 2.6)

project(g3log_builder C CXX)
include(ExternalProject)

ExternalProject_Add(
        project_g3log
  GIT_REPOSITORY https://github.com/KjellKod/g3log.git
        CMAKE_ARGS -DCMAKE_BUILD_TYPE=Debug
        PREFIX "${CMAKE_CURRENT_BINARY_DIR}/g3logger"
	INSTALL_COMMAND ""
)

# Specify include dir
ExternalProject_Get_Property(project_g3log source_dir)
set(G3LOG_INCLUDE_DIRS ${source_dir}/src PARENT_SCOPE)

# Specify MainTest's link libraries
ExternalProject_Get_Property(project_g3log binary_dir)
set(G3LOG_LIBS_DIR ${binary_dir}  PARENT_SCOPE)
```
In my main, I link this way:
```
ADD_EXECUTABLE(${PROJECT_NAME} main.cpp)

INSTALL( TARGETS ${PROJECT_NAME}
         DESTINATION /usr/sbin
         COMPONENT exe_files )


TARGET_LINK_LIBRARIES(${PROJECT_NAME}
                      src
                      ${G3LOG_LIBS_DIR}/libg3logger.a
)
```

Do you have any idea what could lead to this discrepancy?

Additionally, here is the log of the g3log configuration, it has warning not available when I compile it simply by cloning the main repository alone:
```
[  8%] Performing configure step for 'project_g3log'
A 32-bit OS detected
-DUSE_DYNAMIC_LOGGING_LEVELS=OFF
-DCHANGE_G3LOG_DEBUG_TO_DBUG=OFF 	(Debuggin logging level is 'DEBUG')
-DENABLE_FATAL_SIGNALHANDLING=ON	Fatal signal handler is enabled
-DENABLE_VECTORED_EXCEPTIONHANDLING=ON			Vectored exception handling is enabled
-DDEBUG_BREAK_AT_FATAL_SIGNAL=OFF			Break point for fatal signal is disabled




COMPILE_DEFINITIONS:  
End of COMPILE_DEFINITIONS
Generated src/g3log/generated_definitions.hpp
******************** START *************************
// AUTO GENERATED MACRO DEFINITIONS FOR G3LOG

/** ==========================================================================
* 2015 by KjellKod.cc. This is PUBLIC DOMAIN to use at your own risk and comes
* with no warranties. This code is yours to share, use and modify with no
* strings attached and no restrictions or obligations.
* 
* For more information see g3log/LICENSE or refer refer to http://unlicense.org
* ============================================================================*/
#pragma once

// CMake induced definitions below. See g3log/Options.cmake for details.


******************** END *************************
-- - MSVC: Set variadic max to 10 for MSVC compatibility
cmake for GCC 

Windows: Run cmake with the appropriate Visual Studio generator
The generator is one number below the official version number. I.e. VS2013 -> Generator 'Visual Studio 12'
I.e. if VS2013: Please run the command [cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 12" ..]
if cmake finishes OK, do 'msbuild g3log.sln /p:Configuration=Release'
then run 'Release\g3log-FATAL-*' examples

-DADD_FATAL_EXAMPLE=ON		[contract][sigsegv][fatal choice] are examples of when g3log comes in handy
-DADD_G3LOG_BENCH_PERFORMANCE=OFF
-- Configuring done
-DADD_G3LOG_UNIT_TEST=OFF



      *******************************************************************
      Please do 'make clean-cmake' before next cmake generation.
         It is a good idea to purge your build directory of CMake
         generated cache files
      *******************************************************************
       
-- Generating done
```

Do you have any idea what is happening here?

Thanks,
Jonathan

**Comment by KjellKod** [comment]
The missing functions are due to that dbghelp is not linked in. Add that to your project and you should be fine

I have not tested it yet but potentially you can add it to your g3log CMake file:
I.e similar to: 
https://github.com/KjellKod/g3sinks/blob/04946648b1ded3d22291b324b33d3f92083d8de1/logrotate/test/Test.cmake

Let me know how it goes. Thanks

**Comment by LePelicaN** [comment]
Thanks for the quick response.

I tried your solution without success.
I understand that the issue is with dbghelp not being linked but I'm wondering if the issue is that the library is missing or is that it shouldn't be link when using MinGW to begin with.
I mean, in your example, you only link with dbghelp when dealing with Visual Studio:
```
IF (MSVC)
    target_link_libraries(${TestRunner} ${LIBRARY_TO_BUILD} ${G3LOG} gtest_170_lib dbghelp [...]
```

Thanks for your help,
Jonathan

**Comment by KjellKod** [comment]
So perhaps it's an issue with linking using minGW, not specifically for g3log.  I know other people are using minGW and g3log on Windows so without having used that combination myself I believe it should work

Let's just start ruling out the obvious:

1) Are you exporting all symbols?
Ref: http://stackoverflow.com/questions/16024539/undefined-reference-to-function-but-defined-in-header-and-linked-with-library

2) is the minGW build working in general without g3log? If not then maybe the installation is bad: http://www.mingw.org/wiki/Building_a_program_giving_me_error_messages

3) Are you including and  linking the right libraries?
There might be a pragma or #ifdef include macro that does not happen for minGW. I would suggest verifying in stacktrace_windows.cpp/h that what you expect to be included actually is included.

**Comment by LePelicaN** [comment]
The first solution did the trick! So using "Wl, --export-all-symbols" make the compilation successful.
I'm not sure why I need to do this here but thanks a lot anyway.

(Should I close this issue or you prefer to take charge of this?)

**Comment by KjellKod** [comment]
The best would be if you can make a pull request that improves the Windows CMake part. 

Or just send me the diff

**Comment by LePelicaN** [comment]
For now, I only succeed to make it work with modification on my side.
I'm going to try to modify the CMakeLists on g3log side and keep you posted.

**Comment by LePelicaN** [comment]
Hi,

First I need to make an apology: I remove the "-Wl..." this morning and it still works perfectly fine. I don't know what I've been doing from Monday to Wednesday but I was clearly doing something wrong. So only adding dbghelp to my target_link_libraries was enough to make it works.
Thus, I'm very sorry for all the time lost answering me.

But the issue of having to add "dbghelp" dependencies in my project is still a little strange for me.
I would have through that cmake would chain the dependency like it does normally:
```
ADD_LIBRARY(lib_test test.cpp)
TARGET_LINK_LIBRARIES(lib_test pthread)
ADD_EXECUTABLE(main_exe main.cpp)
TARGET_LINK_LIBRARIES(main_exe lib_test)
=> main_exe link with pthread
```
But it's not the case with ExternalProject_Add. And it seems that there is no clean solution : http://stackoverflow.com/questions/28240849/cmake-static-library-dependencies-not-propagating-with-externalproject-add. I find this quite disappointing.

But be sure I'm not blaming you on this. Again, sorry for the inconvenience and thanks a lot for your project. It's great.

**Comment by LePelicaN** [comment]
Ok I wasn't crazy. The issue is back.
But now, I know that it's not an issue with g3log nor my configuration. If I have to guess, I would bet on a cache issue between CMake and MinGW.

**Comment by KjellKod** [comment]
You can always  remove the CMake cache files in between re-builds. Depending on your build environment it can be automated which reduces the chance of removing too much by accident

**Comment by KjellKod** [comment]
I'm interested to know what the resolution will be, please let me know how it goes. 

thanks

**Comment by LePelicaN** [comment]
Hi,
Sorry for the delay, I wanted to make sure to understand everything before answering you.
Thus, I've run more test and I've got a final (I hope) answer.

And again, I was wrong, it wasn't a cache issue.
It was a problem of dependency inclusion order. dbghelp should be include after libg3logger.a.
So this configuration works:
```
TARGET_LINK_LIBRARIES(src
                      pthread
                      ${G3LOG_LIBS_DIR}/libg3logger.a
                      dbghelp)
```
And this one fails:
```
TARGET_LINK_LIBRARIES(src
                      pthread
                      dbghelp
                      ${G3LOG_LIBS_DIR}/libg3logger.a)
```

Thank you for all your help on this.

**Comment by KjellKod** [comment]
No worries. I'm glad it worked out

**Comment by samhartlebury** [comment]
I know it's an old closed post but another way I found for any mingw make that wont build is to add -ldbghelp to cmake cxx libs if using cmake gui. Works perfect
